### ISSUE TITLE
Disabling DASH playback doesn't buffer video when paused

### ISSUE THREAD

**Issue by sfaisal2005** [ParticleCore/Particle#105]
**Browser Name:** Google Chrome

**Browser Version:** 46.0.2490.71

**Operating System:** Windows 7

**Software Type:** Userscript

**Software Version:** 0.7.5

**Userscript Manager:** Tampermonkey

**Userscript Version:** 3.11

**Problem Description:** Disabling DASH playback is supposed to buffer the whole video even when it is paused. But it isn't happening. It's true for any video I tried.

**Steps to reproduce:** Tick "Disable DASH playback" in Video > Player settings. Save it. Play any video. Pause it at any position. Buffering stops.

**Additional details:** I tried to reproduce the same issue in Firefox using Greasemonkey (both latest available version) but the problem didn't occur in Firefox. It seems to be Chrome specific. I also tried with a fresh Chrome profile but the problem persisted.

**Comment by ParticleCore** [comment]
This is the result of a recent Chrome update, there is nothing I can do to force the constant buffering, the browser is handling the download directly and if the video is not playing then the browser will not fetch for more video (won't buffer as it did before).

Another change in the recent Chrome update is that you can no longer open auto-playing videos in new tabs, they will only start playing when you click on that tab.

As far as I can see there is nothing I can do to fix it, if I happen to come up with a solution I will definitely implement it.

**Comment by Eisys** [comment]
> Another change in the recent Chrome update is that you can no longer open auto-playing videos in new tabs, they will only start playing when you click on that tab.

> As far as I can see there is nothing I can do to fix it, if I happen to come up with a solution I will definitely implement it.

I hope you make it an option if you do find a way. I prefer this behaviour. Similar to YTC's 'Only One Player Instance Playing' feature.

**Comment by ParticleCore** [comment]
@sfaisal2005 I conducted a thorough test comparing the buffering behavior with the current and previous Chrome versions, buffering wasn't working in the previous Chrome version either, it would stop once the video was paused. Do you remember when the buffering stopped working like before? Was this a recent change or was it already going on like this for some time?

@Eisys Fragmentating features is not something I'd be willing to do, either the "fix" exists to restore the previous behavior or it doesn't, I do not want to create a setting that works just for Chrome. But I wouldn't be worried, there doesn't seem to be a way to do this because the control is on the browser side, out of YT+ control.

**Comment by sfaisal2005** [comment]
@ParticleCore Sorry I cannot confirm that. I just started using your script yesterday. Before that I was using YTC. I just noticed that YTC now has this problem too. As far as I can remember, I didn't have this issue in Chrome 44 with YTC. For the time being I have switched back to Firefox.

**Comment by ParticleCore** [comment]
@sfaisal2005 Chrome 44 is a version that I can't find to test it out so it is possible that it was changed with that version or it might have actually be on YouTube's side, according to what a user told me, but I really doubt it because we would otherwise be seeing the same thing in Firefox as well.

Thanks for the information.

**Comment by q1k** [comment]
@ParticleCore 
There are links for older chrome versions on www.neowin.net

**Comment by ParticleCore** [comment]
@q1k Thank you for the tip! This will be very useful, this way I am more capable of telling exactly which version brought the change OR if it is indeed a YouTube change.

**Comment by ParticleCore** [comment]
Sadly every single installer is now connecting to the Chrome servers and downloading the most recent version of the browser, so the files linked in Neowin are completely useless. It doesn't make any difference, I was only curious to pinpoint exactly the cause of the change.

**Comment by q1k** [comment]
@ParticleCore 
most new features they add are first introduced to Chrome, and later propably in a few months to other browsers.
Same was when they made the 3D view, only worked on Chrome at the beginning.
