### ISSUE TITLE
Autoplay disabled if tab inactive

### ISSUE THREAD

**Issue by markreg** [ParticleCore/Particle#117]
It would be awesome to have the option to disable autoplay if the tab is inactive. This is helpful when the browser is restarted and multiple youtube video tabs are open.

**Comment by ParticleCore** [comment]
It has already been requested before, see https://github.com/ParticleCore/Particle/issues/52

**Comment by markreg** [comment]
Oh, didn't see that. Btw, awesome wiki page! The example pics made it very easy to quickly go through all the options.

**Comment by Habetdin** [comment]
@markreg You could use UserJS from my fork to get this feature.
@ParticleCore Could you add implementation to your branch? :smile:

**Comment by ParticleCore** [comment]
@Habetdin Please stop doing this, feel free to fork but don't make use of this issue tracker to publicize it.

**Comment by Habetdin** [comment]
@ParticleCore should i forget and don't use issues and PRs?

**Comment by ParticleCore** [comment]
Not at all, keep it up, just don't use this issue tracker to advertise your fork.

**Comment by Habetdin** [comment]
@ParticleCore oh, ok. Deleted ad and waiting for any implementation of this feature if it's working and doesn't trigger Chrome issue described in 2nd post of this issue.

**Comment by ParticleCore** [comment]
The issue is when users do want the video to play in the background and it doesn't play unless the tab is active on load start because of the recent Chrome change which affects this behavior, previously announced back in August: http://www.ghacks.net/2015/08/27/chrome-defers-media-playback-in-background-tabs/

I am not that interested in adding a feature that will not work very well in one browser base. On the other hand, auto pausing the video when changing tabs is a different thing and that is a feature I might implement some day.

**Comment by Habetdin** [comment]
May be it's realisable to make Firefox-only option then?

**Comment by ParticleCore** [comment]
That is not an option. It has to work correctly on both browsers, otherwise I would have just released it for one and I have no interest in making features that work correctly for one brower and not for another.

**Comment by Habetdin** [comment]
@ParticleCore my Firefox doesn't defer media in background tabs and that's why i made that option.

**Comment by ParticleCore** [comment]
YT+ is not being used just by Firefox users and I explained that the problem is when Chrome users don't want the videos to pause and the browser itself will pause it even though they disabled the YT+ option.

The problem is not in pausing the videos, the problem is having an option that controls the video pause turned off and it still pauses. It won't work correctly due to the Chrome change, that is why I will not be adding this feature.

**Comment by Habetdin** [comment]
Why FF support is described in README? It's even in the AMO. Firefox users use UserJS too.

So the problem is with current 'Autoplay videos' and not with the suggested feature? :disappointed:

**Comment by Habetdin** [comment]
Why FF support is described in README? It's even in the AMO. Firefox users use UserJS as mee too.

So the problem is with current 'Autoplay videos' and not with the suggested feature - so why not to add it at least? :disappointed:
May be make combined option like «'Autoplay videos': 'Default' / 'Disable for all' / 'Disable for background only'» or in other words: «'Disable autoplay for': 'All tabs' / 'Background tabs'»?

**Comment by ParticleCore** [comment]
I already explained that YT+ supports both FireFox and Chrome. To add a new feature first it has to work correctly on both and I will not add features just for one browser and not another.

**Comment by Habetdin** [comment]
It's not new feature at all, it's more like improvement of current one. It also works fine on both.
Current feature is like 'look how cool can be autoplay disabled' and it's really awesome but its only usable as option for all tabs... So people that want it for background tabs only (cos Firefox doesn't defer media in them) can't afford that :disappointed:

Current option (in 0.7.7) is «'Disable autoplay for all tabs': 'Yes'/'No' checkbox», why not to remake it as «'Disable autoplay for': 'All tabs' / 'Background tabs'»?

**Comment by markreg** [comment]
The feature in the ghacks article would solve the problem of videos playing in inactive tabes when chrome is restarted. However the article says that it's only in **chrome dev** for now. When it comes in stable you can revert @Habetdin 's patch.

**Comment by ParticleCore** [comment]
@markreg The article is from August and was related to a change that has already been launched in the recent stable Chrome versions.

**Comment by markreg** [comment]
Ah, you're right, it has been implemented in chrome stable
