### ISSUE TITLE
Playlist autoplay should make video play immediately even when videos normally start paused

### ISSUE THREAD

**Issue by lewisaronmilne** [ParticleCore/Particle#123]
What's the point in automatically going to the next video in a playlist when that video starts paused anyway (I mean that it doesn't autoplay (the fact that the two systems interacting here are both called autoplay is really annoying)).

If you turn on playlist autoplay the video should play immediately.

**Comment by SW1FT** [comment]
Yeah, this as also been bothering me quite a bit.

**Comment by ParticleCore** [comment]
I have explained why it currently works the way it does here: https://github.com/ParticleCore/Particle/issues/48#issuecomment-125728945

In short, if users want the playlist to change to the next video but not have the video playing automatically they can't if I change it to the way you want because this option would not exist. They would be forced to have playlist autoplay on and playing the videos automatically with no alternative other than playlist autoplay off.

**Comment by SW1FT** [comment]
Make an option for this behavior, if it's selected, it behaves how we are wanting, if not, it behaves how it currently is.

**Comment by lewisaronmilne** [comment]
I disagree with this but I'm not gonna press the issue.

**Comment by ParticleCore** [comment]
>Make an option for this behavior, if it's selected, it behaves how we are wanting, if not, it behaves how it currently is.

It wouldn't be a bad idea if YouTube only had playlists. How would the behavior be if the user is watching a single video but the playlist autoplay was active? Should the single video autoplay as well or not? And what if the user has playlist autoplay controlling video autoplay and during a playlist he wants to disable video autoplay? What should happen then?

These are the few problems with doing what you sugggested. I've already thought about this for quite some time when I was still developing YT+ and any solution I found would generate more problems so I decided to leave it like this.
