### ISSUE TITLE
add a way to download the given youtube video

### ISSUE THREAD

**Issue by sangohan** [ParticleCore/Particle#124]
YoutubeCenter used to have the `download` option for a video - this is especially useful for people on slow connections who still wish to view the high definition version of a video (which otherwise would just buffer, fail to load, and various other error cases). 

There are other services to download youtube, but it's just much more convenient to have it right in the UI of this Add-On. Also, sites that offer youtube download tend to be very shifty, and have ads that resemble the download, but is actually malware/spamware etc. It's much safer to have the link right in an addon that is already trusted.

I hear that google really dislike a download option, and will actively try to take the addon off the chrome store - i think the way to work around that is to have a separate downloadable version of the .crx file for the advanced users who wish to work around the stupid policies of google.

**Comment by ParticleCore** [comment]
It has already been requested before, see https://github.com/ParticleCore/Particle/issues/32

Even if I were to make a different version outside the webstore, they would very likely still ban in the webstore because the extension homepage links lead to a place with a version providing the download ability. Aside from the other problems mentioned in the previous link, the risk itself is just not worth it.
