### ISSUE TITLE
TypeError: menu.getElementById is not a function

### ISSUE THREAD

**Issue by Domochevsky** [ParticleCore/Particle#128]
Bit of a shot in the dark here, since I know that Pale Moon is not supported. Forgive my impertinence.
However! According to Firebug, clicking on the non-functional settings button (in Pale Moon x64) in the top right causes this error to appear on the console:

menu.getElementById is not a function

Searching through the script in the editor the only instance of that method call is...

list = menu.getElementById("blacklist");

Is it possible that this erroneous option causes the entire menu to cancel loading?

Test-wise I replaced that particular line with list = null;
Clicking on the button after that causes the following error message on the console

TypeError: pWrapper.getElementById is not a function

and is called via 

pWrapper.getElementById("P-container").appendChild(template("GEN"));

I can't easily replace that with a null, since it's not involved in an if-check.
Thus I have not investigated deep enough at the moment to tell what either menu or pWrapper actually are and do and whether or not these issues in particular cause that button to not react when clicked in Pale Moon.

Can I get further opinions on this?

**Comment by Domochevsky** [comment]
Relatedly I found this -> https://stackoverflow.com/questions/6409505/document-getelementbyid-is-not-a-function which speaks of bugs in getElementById in some browsers.

**Comment by ParticleCore** [comment]
The link you provided is not a bug, the user was using an incorrect name for the function, the last letter of `getElementById` was incorrectly set with a capital `D`.

The problems with Pale Moon are not related to `getElementById`, they are very likely related to the new methods of loading settings implemented in past versions, which are failing to work because of some incompatibility.

This has already been reported in https://github.com/ParticleCore/Particle/issues/102
