### ISSUE TITLE
Subscription grid broken

### ISSUE THREAD

**Issue by Cyguard** [ParticleCore/Particle#129]
just noticed after updating to FF42 that the subscription grid was broken. disabling the plugin fixes this. not sure if this can be fixed or not.

**Comment by SW1FT** [comment]
It was a youtube update, not FF as I'm using FF44.

**Comment by AccountOneOff** [comment]
[Turn off the user script/extension and put your subscriptions to list view then turn it back on and reload.](https://streamable.com/9t8a) That worked for me.

**Comment by ParticleCore** [comment]
I haven't received the update in either browsers, but I was aware that YouTube has been testing a grid layout and you might have received it because it has been recently been released: https://www.reddit.com/r/youtube/comments/3rnoai/my_subscription_feed_in_youtube_now_has_a_default/

There's nothing I can do about, this grid is now native in YouTube so to "fix" what is broken simply disable the Grid subscriptions layout in YT+.

Or try what AccountOneOff suggested, although it is redundant to change from list to grid in YouTube only to enable the grid again in YT+.

The feature will be removed on the next release since it is no longer needed.

**Comment by Cyguard** [comment]
apparently it fixed itself somehow anyway so i guess the post is moot.

**Comment by SW1FT** [comment]
Same for me, it fixed itself.

**Comment by ParticleCore** [comment]
YouTube rolled back their grid layout, it is very likely it will return soon.
