### ISSUE TITLE
Different behaviour in Firefox and Chrome

### ISSUE THREAD

**Issue by Habetdin** [ParticleCore/Particle#133]
If I enable 'Autoplay videos' option in YT+'s settings it works fine in Firefox - videos play automatically everywhere. But in Chrome's background tabs it doesn't autoplay :cry:
Reason: http://www.ghacks.net/2015/08/27/chrome-defers-media-playback-in-background-tabs/
Solution: execute alert() if browser is Chrome and tab is background - alert will make tab active and media will not be deferred.

**Comment by Habetdin** [comment]
Solution №2: rename option to 'Disable autoplay' and make it selectable between 'No' (so leave default behaviour), 'Yes' (current realisation for all tabs) and 'Yes for background tabs only'.

**Comment by ParticleCore** [comment]
Solution one is too intrusve, solution two is not a solution at all since the problem of not playing in the background tabs remains unfixed. At the moment there is no solution, the closest one would be to make the autoplay feature as `Autoplay:` `Default` or `Off`, however this would conflict with the autoplay shortcut toggle in the advanced options. Still, this will stay under consideration but won't be implemented for now.

**Comment by Habetdin** [comment]
Autoplay: Default or Off - why not allow Off not for all tabs too? :cry:
