### ISSUE TITLE
Is there a way to disable 60fps?

### ISSUE THREAD

**Issue by MyNameIsNotOrbit** [ParticleCore/Particle#137]
I know you don't accept any more requests and this isn't really one anyways.
I'm just wondering if there is any way to disable 60fps. 
My internet can handle 1080p just fine but is struggling with 60fps 1080p videos.
I could disable DASH or just pick 720p as the default quality since 720p60 works fine. But then im missing out on a higher quality on other 1080p videos that aren't in 60fps.
So if there is some hack or userscript or something, I would love to know about it.
I'm on Chrome if that helps.

And thanks for an awesome addon. YT+ is a blessing.

**Comment by ParticleCore** [comment]
Sorry but this is just something that cannot be done. The 1080p 60fps streams, when they exist, are the only ones available, there's no other alternative other than disabling DASH or the creator not encoding in 60fps.

A long shot would be to ask the content creators to upload non-60fps versions as an option for users in your situation.

**Comment by q1k** [comment]
if you are using flash player, not the html5 player, there is no 60fps.

you could try forcing the flash player and see if that works out for you.

**Comment by ParticleCore** [comment]
@q1k Thanks for the info, seems like there are still some fallback streams being provided without 60fps for the flash player. @MyNameIsNotOrbit you can follow q1k's suggestion, but be warned that plenty of YT+ features will not work with the flash player because they are incompatible.

**Comment by ParticleCore** [comment]
I've confirmed what I suspected, YouTube is still serving non-60fps streams with 60fps streams, so in theory it might be possible to "turn off" high frame rate streams with a userscript. I might try to create this feature for YT+, my dying laptop would benefit a lot from this.

**Comment by ParticleCore** [comment]
@MyNameIsNotOrbit I have released the new YT+ version 0.7.9 with the option to [turn off 60fps](https://github.com/ParticleCore/Particle/wiki/Features#hfr_off), let me know if it works for you.

**Comment by MyNameIsNotOrbit** [comment]
Wow. Yeah, it works perfectly. Thank you so much.

**Comment by q1k** [comment]
is it by any chance possible to add those streams in the quality settings menu, instead of replacing the 60fps ones with them.?

**Comment by ParticleCore** [comment]
@q1k That's what I was trying to do for the past 2 days, but I couldn't find any way other than creating the entire HTML5 player from scratch.

If I find a way to make something like this happen I will try to enhance it, unfortunately for now it will have to be like this.

**Comment by q1k** [comment]
so you are replacing them, correct?

the options are inside div.ytp-menu.ytp-quality-menu
i don't know if it would be possible to add the corresponding stream below the 60fps one, but it may be easier to just add all ~30fps streams above all the others.

**Comment by ParticleCore** [comment]
No, there's no replacing, this change is not done at the DOM level, it is strictly javascript manipulation.

**Comment by ColonelGerdauf** [comment]
On this subject, I wonder if the vice-versa is true in the case of 480P and below. Although I highly doubt it, it could be possible for YouTube to be hiding a 480P 60FPS option, for example. 

The reason I have this hypothesis is my observation of 60FPS YouTube support on the IPhone 4S, of which the native resolution (640P) is not all that great by YouTube standards.

**Comment by ParticleCore** [comment]
@ColonelGerdauf There aren't any low quality HFR streams on YouTube as far as I could find. There's only 60fps for 720p, 1080p, 1440p and 4k options.

**Comment by SpeedRider** [comment]
yes there is you will need chrome and this extension Enhancer for YouTube™ the very first setting is the one you click i just found it out to day

**Comment by trlkly** [comment]
Any way you could honor this setting even on embedded videos? Thought I'd ask here first before filing an actual Issue, since you mention not taking any more feature requests. But you did take this one, so maybe...

**Comment by ParticleCore** [comment]
@trlkly YT+ already has a feature that allows you to disable 60fps: https://github.com/ParticleCore/Particle/wiki/Features#hfr_off

But YT+ is only restricted to videos on YouTube pages. It will not apply to embedded videos.

**Comment by trlkly** [comment]
I know. That's why I asked if you could add it. I asked if you could make
the feature work on embeds as well.

If that was your way of saying no, it was not very clear and rather
frustrating, telling me things I would already have to know to ask the
question.

**Comment by ParticleCore** [comment]
I thought you didn't know it was already implemented, especially because "even" carries the idea of implementing the feature in normal videos and even on embedded videos.
Regarding the embeds, as I said YT+ is only for videos in YouTube pages, it is not meant for external videos such as embedded videos and there are no plans of doing that. Just because it appears to be relatively simple , in this case it is not and on top of that I am simply not interested in that, at least for now.

Regarding feature requests, feel free to make any, they will always be considered whenever I have the time and possibility, until then they are archived and the user is informed of my current limitations so no expectations are made.

**Comment by aitte2** [comment]
@ParticleCore 

Hi there, I would like to help people with old laptops on every browser (not just chrome) by making a standalone Userscript which only has the "disable HFR" feature. But I don't fully understand how you are injecting the change to 30fps?

I tried to dissect YT+ and from what I can see it edits the "adaptive_fmts" array, before the page/player finishes loading. It removes the 60fps options, but I am not entirely sure how.

I know how overworked you are so I waited a month to even ask you about this... but please, if you have a little bit of time, could you please explain how the process works? I'd love to help people with old laptops that lag to hell when YouTube believes they support 1080p60 but they really don't. :/

**Comment by ParticleCore** [comment]
@aitte2 
https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L1669

Split all dash streams
Iterate through each one check if it either has no FPS (means it is an audio stream) or if the FPS value is lower than 31 (which excludes streams with FPS higher than 30)
Save all the streams that satisfy that condition
Replace the original list with the one you just curated

Please keep in mind the [license](https://github.com/ParticleCore/Particle/blob/master/LICENSE)

**Comment by aitte2** [comment]
@ParticleCore Ahh thanks, that's where I went wrong. I tried to edit the "fps=60" to say "fps=30". I should have deleted those streams altogether.

Thank you so much for the explanation. I'll get to work. And don't worry, I will not use any of your code/functions, but I will credit you with finding the method. Thanks a lot! :)

**Comment by aitte2** [comment]
@ParticleCore Thanks, I am practically done... but I spent 2 hours trying to find an injection point on my own since I didn't want to annoy you again. And now I have a headache. Haha.

Well, I was able to make it all work, by watching the DOMNodeInserted event. That was the only way to edit the adaptive_fmts array early enough to affect the player.

I can see that your own script uses a maze of injection points and events...

Which brings me to the questions: 1. Is there a better injection point than DOMNodeInserted? 2. How did you make it affect the new player arguments when the player is in fullscreen and the user plays the next autoplay video? For my script, that means the next video will be in 1080p60, since I am not able to catch that "swapped video" event.

```javascript
// ==UserScript==
// @name         Force YouTube HD to 30FPS
// @namespace    SteveJobzniak
// @version      1.0
// @description  Replaces all high-FPS HD videos on YouTube with 30FPS versions, to allow old computers to watch high-resolution videos without stutter.
// @author       SteveJobzniak
// @match        *://www.youtube.com/*
// @exclude      *://www.youtube.com/tv*
// @exclude      *://www.youtube.com/embed/*
// @run-at       document-start
// @grant        none
// @noframes
// ==/UserScript==

(function () {
    'use strict';

    function YouTubeInjector( config ) {
        function removeHighFPS()
        {
            var i, new_fmts, available_fmts, matches;

            if( config.args && config.args.adaptive_fmts ) {
                new_fmts = [];
                available_fmts = config.args.adaptive_fmts.split( ',' );
                for( i = 0; i < available_fmts.length; ++i ) {
                    // Only keep streams without a framerate (audio streams) and ones with fps <= 30.
                    // This throws away the 60fps sources, which forces YouTube to always use 30fps.
                    //
                    // Credit goes to the YouTube+ project for originally figuring out this trick:
                    //   https://github.com/ParticleCore/Particle/issues/137
                    matches = available_fmts[i].match( /fps=(\d+)/ );
                    if( !matches || matches[1] <= 30 ) {
                        new_fmts.push( available_fmts[i] );
                    }
                }
                config.args.adaptive_fmts = new_fmts.join( ',' );
            }
        }

        function main()
        {
            removeHighFPS();
        }

        main();
    }

    // Inject at the earliest possible point that the YouTube player object is available.
    // NOTE: In my testing, only "DOMNodeInserted" was able to perform the injection early enough to affect the player.
    // FIXME: This doesn't work if the user watches the new autoplay video in fullscreen mode. Is a fix for that possible?
    var is_injected = false;
    function waitForYouTubeConfig() {
        if( !is_injected && window.ytplayer && window.ytplayer.config ) {
            YouTubeInjector( window.ytplayer.config );
            is_injected = true;
        }

        // Clean up the listeners since they are no longer needed.
        if( is_injected ) {
            document.removeEventListener( 'DOMNodeInserted', waitForYouTubeConfig, false );
            document.removeEventListener( 'readystatechange', waitForYouTubeConfig, false );
            document.removeEventListener( 'DOMContentLoaded', waitForYouTubeConfig, false );
            document.removeEventListener( 'load', waitForYouTubeConfig, false );
        }
    }
    document.addEventListener( 'DOMNodeInserted', waitForYouTubeConfig, false );
    document.addEventListener( 'readystatechange', waitForYouTubeConfig, false );
    document.addEventListener( 'DOMContentLoaded', waitForYouTubeConfig, false );
    document.addEventListener( 'load', waitForYouTubeConfig, false );
    waitForYouTubeConfig();
})();
```

**Comment by ParticleCore** [comment]
I am sorry but this isn't a place to explain how to make userscripts. It would take too long to explain the multiple injection points you will have to create through different player states. Please make these kinds of questions in more appropriate forums.

**Comment by aitte2** [comment]
@ParticleCore I know, that is why I spent 2 hours trying to solve it before asking you. I didn't want to bother you again. Unfortunately there doesn't seem to be anyone else who has figured out the player state changes, so there was nowhere else I could ask.

I'll just leave the script as-is. Not worth releasing it since it doesn't handle fullscreen autoplay. :\

**Comment by aitte2** [comment]
I solved it in a different way, by making the browser report that it only supports 30FPS or less. I've posted an extension for those who just want to remove 60FPS videos:

https://greasyfork.org/en/scripts/23323-force-youtube-to-30fps

(Maybe this code is of interest to you too, since I'm patching the MSE codec check instead of YouTube's player. Depending on your viewpoint, this is either cleaner or less clean than your "adaptive_fmts" hack.)

**Comment by ParticleCore** [comment]
I have no problems with that, as long as people aren't purely using the issue tracker for the sole purpose of advertising another product.
It is a very interesting solution you found and far simpler than the complications you would have if you'd follow through with the multiple injection points that YT+ requires for other features.
Just a suggestion in case you want it, if you use a name related to "disable 60FPS" it will be found by far more users looking for your script than the current name it has. Even this issue here is related to disabling 60FPS instead of forcing 30FPS, which is the most common search used.

**Comment by aitte2** [comment]
Thanks for the help, and for inspiring me with your incredible extension. :) You're definitely right that YT requires multiple injection points, so I started looking around to see how it determines what formats to show to the user, and found that it queries the Media Source Extensions. You're welcome to use this method too, if you ever feel like it.

Oh and I've changed the name and updated my link above, since you are right that it's better for SEO. I think YouTube will be adding 120fps in the future, but hey, 60fps is probably going to be an accurate name for a long time. ;)

Take care and thanks for everything!
