### ISSUE TITLE
Player shortcuts always active

### ISSUE THREAD

**Issue by Mike-Correa** [ParticleCore/Particle#150]
Browser Name: Chrome

Browser Version:  46.0.2490.86 m (64-bit)

Operating System: Windows 10

Software Type: Extension

Software Version: 0.8.2

Problem Description: When "Player shortcuts always active" is enabled it's not possible to select text on the description box.

Steps to reproduce: Enable "Player shortcuts always active", open a any video, open description box and try to select the text.

**Comment by ParticleCore** [comment]
It is a side effect of having that feature working. It makes the player to stay always active as if you clicked on it, this way any player shortcuts will be ready to process. When you select text you are making it loose focus, meaning that the shortcuts will no longer work, so it forces the player focus again.

If you need to copy text with this feature enabled then select the text you want to copy and don't let go of your mouse button when you are selecting the text, copy it and paste as needed.

**Comment by Mike-Correa** [comment]
The problem is that the text is not selected at all on the description box. It would only be possible to copy it without releasing the mouse button if the text was actually selected, which doesn't happen.

On the other hand, i can select text without problems on the comments section. Even if i release the mouse button the text keeps selected, but of course the shortcuts lose focus to the player. Then, once i click anywhere on the page, even on the selected text for the selection to disappear, the focus of the shortcuts immediately return to the player.

This is the expected behavior for the description box too, but for some reason it is not possible to select anything there.

**Comment by ParticleCore** [comment]
I actually just confirmed that the selection is working and stays selected with the same configuration as yours with this feature activated. This was tested in any text area, including the description box, and the same test was done in Firefox with the same working results.

Post your YT+ settings (no need to include the blacklist) so that I can try to replicate the problem using your exat YT+ settings, and make sure you follow the troubleshooting guide as well in case this is being caused by something external to YT+: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Mike-Correa** [comment]
I have done all the troubleshooting before. I even tried using te extension on icognito mode, but with these settings the problem persisted.
[Youtube+ Settings.txt](https://github.com/ParticleCore/Particle/files/44376/Youtube.Settings.txt)

I noticed some particularities. 
I can select description preview text, meaning the text that appears when the full description is not open. The behavior is the same as when i select any other text on the page, like the comments. As soon as i cancel the selection the shortcuts for the player return. 

The problem happens when i open the description box. To work this around i realized i have to open description, select something else on the page like the title of the video, and then select description. I remember this exact same problem happened in some old developer version of YTC too.

Well, the problem is not a big deal, since i found a simple work around, so if you can't find a solution that won't be a problem, i just felt like reporting it to you. I thanks for the attention.

**Comment by ParticleCore** [comment]
>As soon as i cancel the selection the shortcuts for the player return.

I just realized I forgot to open the description box when I was testing... Yes I can replicate the problem, will try to see if there is something that can be done but don't expect this to be fixed because I doubt there is a solution.

**Comment by ParticleCore** [comment]
Looks like this is restricted to Chrome only, I already had a method to prevent this from happening and is working correctly in Firefox even in the open description box as well as in Chrome, except in the open description box. For some unknown reason Chrome has changed the way it handles events which is causing problems in this specific chain of actions, it is not something that can be easily solved.

Hopefully they will eventually revert whatever change they made to cause this, otherwise users will have to handle it however they can.

**Comment by ParticleCore** [comment]
@Mike-Correa I think I managed to solve this problem in version 0.9.3, let me know if it is fixed for you as well.

**Comment by Mike-Correa** [comment]
Fixed, thank you!
