### ISSUE TITLE
"Player always visible when reading comments" shows when navigating back one page.

### ISSUE THREAD

**Issue by Yoiink** [ParticleCore/Particle#155]
As title states, repro:
1) https://www.youtube.com/
2) Click a video
3) Scroll to comments
4) Go back a page.
5) Video still in view.

Edit: After updating Firefox & the addon, the issue seems to have gone.

**Comment by ParticleCore** [comment]
I assume this issue was invalid since you closed it.

**Comment by Yoiink** [comment]
I can't replicate after updating Firefox & newest addon version, so I guess so.

**Comment by ParticleCore** [comment]
Glad to hear that, if you have any other problem just let me know!

**Comment by Yoiink** [comment]
Will do, keep up the good work :+1:

**Comment by Eisys** [comment]
It still happens for me. Has been happening for a while but I never bothered to report since it's such a minor glitch.
I'm doing the steps above but instead of the homepage, I choose a video from a channel's videos.
After I scroll down and go back, this is what shows: http://prntscr.com/9caj7n

I'm on Chrome Version 48.0.2564.41 beta-m (64-bit) using the 0.8.3 usercript version with Tamper.

**Comment by ParticleCore** [comment]
@Eisys I cannot replicate it following your steps with the same setup, can you share your YT+ settings and try to be as precise with your steps so that I can try to replicate the problem?

Another thing, make sure you test this with everything disabled except YT+ to rule out the possibility of a conflict with another extension or userscript.

**Comment by Eisys** [comment]
Settings: http://pastebin.com/CXWPVWw5

Tested with everything disabled except Tamper and the script. Still happens.

And I don't think I can be much more accurate.
I go to a channel, either from my bookmarks or clicking their name under a video in the sub page, which leads me straight to their videos and not home. Then click a video, scroll down for the small video to pop up, hit the back button and there it is.
If I then click another video, and scroll down and go back again, it's gone.

**Comment by ParticleCore** [comment]
Still can't make it happen on my side, the script is correctly removing the floating player configuration every time the user navigates to another page (triggered by the SPF api), regardless of the destination page or the direction (going back).

I can't fix something that I cannot replicate, but the other user mentioned this was happening until he updated the browser and YT+, it is possible that somehow you are stuck with an old YT+ version inside Chrome because your issue was one that existed quite a few versions back and I remember that I had fixed it.

I can only suggest that you try the last step in the troubleshooting guide https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

This will make sure that you have a clean test profile with only YT+ and nothing else that might interfere, such as bugged YT+ settings in the Chrome folders, outdated CSS, etc.

**Comment by Eisys** [comment]
Well what can I say. It still happens even with a brand new profile. Only installed Tamper and YT+

Default YT+ settings so I tried disabling options onebyone to see what might be causing it. The only thing that fixed it was when I disabled autoplay. I tried again with default settings and only messed with autoplay; with it on, it happens, with it off it doesn't. It doesn't happen regardless of whether I go back right away w/o starting the video or start it and then go back.

I just tried it on my laptop as well(but with chrome extension version) for a 2ndary source of info, also happens.

**Comment by ParticleCore** [comment]
I finally managed to replicate it, but only because you mentioned the autoplay option. Only when it is enabled then the problem can be replicated.

Also I only noticed just now that you did not share your YT+ settings, but the language instead. Doesn't matter now because I was finally able to make it happen and will try to fix it as soon as possible!

**Comment by Eisys** [comment]
Yes, I just noticed that mistake myself, so sorry about that one xD
The buttons are right next to eachother and the text looks similar.

**Comment by ParticleCore** [comment]
It should be fixed now, the problem was really hard to identify even by inspecting the code, but I think I got it.

Let me know if it works for you as well.

**Comment by Eisys** [comment]
Yep, it's fixed. 
Thank you.

**Comment by ParticleCore** [comment]
Great to hear that, and thank you for staying along to help me find the problem!
