### ISSUE TITLE
YT+ not working correctly with "Whitelist channels" scripts for ad blocking.

### ISSUE THREAD

**Issue by Betsy25** [ParticleCore/Particle#162]
Hi,
For some reason, when I enable YT+,  the correct way of trailing the username to any YT video is not being respected, while with YT+ disabled, the [whitelist channels in uBlock Origin userscript](https://greasyfork.org/en/scripts/13226-youtube-whitelist-channels-in-ublock-origin) would add the string ***&user=[USERSTRING]***, when I enable YT+ it almost always adds ***&user=videos***

Example Links:
https://www.youtube.com/watch?v=XHCVmDkXc70
https://www.youtube.com/watch?v=q2qNWk9G4qo

Tools & Scripts used
================
- Firefox v42
- [YT+ 0.8.8 (userscript)](https://github.com/ParticleCore/Particle/raw/master/src/Userscript/YouTubePlus.user.js)
- [uBlock Origin 1.4.1b2](https://github.com/gorhill/uBlock)
- [whitelist channels in uBlock Origin userscript](https://greasyfork.org/en/scripts/13226-youtube-whitelist-channels-in-ublock-origin)

**Comment by ParticleCore** [comment]
Hello Betsy, YT+ has a feature that allows you to customize which channel tab you wish to land on by default when clicking on a YouTube channel/user name: https://github.com/ParticleCore/Particle/wiki/Features#channel_page

Have you tried changing it to `default` instead of `videos` ?

**Comment by Betsy25** [comment]
@ParticleCore Yes, I had it on *videos*, switching it to *default* seems to have fixed this misbehavior.
Actually, I (and most probably most users) tend to click on video's from within their subscription page, but once I do want to check out a users channel, I prefer to land on the *videos* tab by default, that's why I switched it.
Thanks for the workaround :)

**Comment by ParticleCore** [comment]
Glad that it worked out. I am also one of those users, which is why the feature exists.

But you should know that YT+ has a feature that only allows ads for the channels you are subscribed to: https://github.com/ParticleCore/Particle/wiki/Features#subs_ads_on

So you can disable uBlock on YouTube, use the YT+ internal ad blocker and enable the above setting.

This way you can still have ads only for the channels you are subscribed to and use the default channel page feature to land on the channel video tab.

However this will only work for channels you are subscribed to, you can't pick them individually through YT+
