### ISSUE TITLE
Latest updates lost some compatibility

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#175]
First of all let me just say that you are doing an amazing job with the script and keeping it updated.

The latest updates, however, have stopped one of my other absolutely needed addons from working properly. I'm talking about [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en)

In said addon, I have it set so that the numpad plus and minus keys change the speed and the * key changes speed to default. It has worked perfectly for a long time with YT+ but after updating to 0.9.7, those keys have stopped working when the focus is outside the video. They work if I click on the video.
I know this is caused by a YT+ update because when I disable 'player shortcuts always active' the keys start working again.
There is a workaround, if I change the shortcuts to be on the main part of the keyboard, for example the , . - keys, then it all works again but I'm so used to pressing the + and -  since they're so close to my mouse.

So, I'm wondering if you could maybe bring back the compatibility. Of course it would be even better if you brought over the functionality of speed controller to YT+ but I don't see that happening.

**Comment by ParticleCore** [comment]
I am sorry but the new method had to be implemented because the previous one was not working reliably, especially in Chrome due to a bug they have never fixed. I will try to restrict the shortcut mapping to alphanumeric, arrows and spacebar keys only, hopefully that will prevent situations like yours.

**Comment by ParticleCore** [comment]
@Eisys I just found out that the YouTube player has an inbuilt shortcut to change video speed and it is compatible with YT+ feature.

Hold `Shift` and press `.` (dot) to increase speed, hold `Shift` and press `,` (comma) to decrease speed.

I am testing which shortcuts the player has natively and so far I don't think I will be able to reduce the key mapping, there are quite a few shortcuts that would not work if I reduced it further, in fact I might have to increase since a few appear to use keys I have excluded.

For now this will not be fixed seeing that your situation is already solved by YouTube's default shortcuts which are compatible with YT+.

I will still continue to look at it to see if there is anything else I can do to make it better without adding bulk.

**Comment by ParticleCore** [comment]
Further analysis indicates that most of the shortcuts are actually already natively functional in the global context of the page, except a few (spacebar, arrow keys, home/end, etc.) so I will instead limit the key map just to those few and leave all the others for the player to handle by itself as it already does.

**Comment by ParticleCore** [comment]
This should be fixed in version 0.9.8, let me know if it works for you.

**Comment by Eisys** [comment]
Yes it is fixed. Thank you!!
