### ISSUE TITLE
Cannot Edit Videos with Addon Enabled

### ISSUE THREAD

**Issue by RibShark** [ParticleCore/Particle#183]
When using YouTube Plus, attempting to edit uploaded videos in the Enhancement tab doesn't work. Instead of a video preview, there is a broken player that says an error has occurred, and no edit functions will work. I am using the latest version of Firefox 64-bit on Windows 10.

**Comment by ParticleCore** [comment]
That's because the enhancements tab is only using the flash player for video editing features (unexpected since HTML5 is already fully capable of the changes they offer).

I also found that the same problem is present in the Audio and Annotations tab, will try to work on a fix for it, but for now the only solution is to disable YT+ while editing.

**Comment by ParticleCore** [comment]
This should be fixed in version 1.0.1, let me know if it works for you too.

**Comment by RibShark** [comment]
Works for me. Thanks for fixing it so quickly!
