### ISSUE TITLE
Config button not aligned with title

### ISSUE THREAD

**Issue by Greck98** [ParticleCore/Particle#186]
I have the chrome extension "Ink for Google", that gives some colors to google's sites. With it the config button (at the top right of the website) isn't aligned with the title of Youtube etc.

Here one image: http://s22.postimg.org/4cok5ev69/Captura.png

**Comment by ParticleCore** [comment]
Sorry but that is not a YT+ problem because it is working correctly without that extension. It is that extension that is causing the problem and should fix it since it is processing the button incorrectly, which is normal since it is only accounting for the standard YouTube buttons and ignores others.
