### ISSUE TITLE
Youtube freezes the browser (not the player)

### ISSUE THREAD

**Issue by snintendog** [ParticleCore/Particle#187]
I have a rather large amount of subscriptions so whenever i reload any youtube page it loads all of my subscriptions in the Guide bar subscription box and bogs down the pages as it loads all the links and avatars in the guide made a css (#guide-subscriptions-section{display: none;}) that hides it but it still loads it but stops the avatar loading and the pages still freeze on load shortly. Is there any way to limit the max number of items in the list or remove it before it loads? Thank you for your time.
![problem with guide](https://cloud.githubusercontent.com/assets/5448989/12102164/06975e3a-b307-11e5-9b21-a4f55c020586.png)

**Comment by ParticleCore** [comment]
As you might have already guessed, this is a known problem when there's lots of subscriptions on YouTube on Firefox browser: https://www.reddit.com/r/youtube/comments/3lcxvj/firefox_started_freezing_on_youtube_a_lot_in/

Your CSS patch already took care of a big load, but the requests are still being made, as you clearly indicated.

For removing the subscription list from the guide menu you can try this makeshift userscript: https://gist.github.com/Yonezpt/3246b0570b384298b38d

It should prevent any image load from the subscriptions since it immediately removes the entire list as soon as it can.

Be aware that no support for this will be given, if you want to continue any discussion related to that userscript you should follow up on the gist comments.

**Comment by snintendog** [comment]
Thank you very much.
