### ISSUE TITLE
Settings reset to default

### ISSUE THREAD

**Issue by grenzor** [ParticleCore/Particle#189]
It seems that YT+ Settings reset to default after a logout/restart/shutdown. Upon new session, YT+ asks me to customize settings again.

Opening and closing FF doesn't reset the settings but doing any of the 3 mentioned above does. Using FF 43.0

**Comment by ParticleCore** [comment]
If this is happening between computer sessions and not between browser restarts then the problem lies outside YT+.

By your description it sounds like you have a software that is removing Firefox data or a setting that is causing this problem, CCleaner, Cookie remover, etc.

To rule out the possibility of this being caused by something in your browser try repeating the steps with a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager) and only YT+ installed with some settings changed other than the default ones.

If it keeps happening then you might have some software that is causing this problem, anti virus, "speed booster", etc.

Knowing which Operating System you are using could be helpful.

**Comment by grenzor** [comment]
On Liinux Mint x64, no software are running that would cause that to happen. Possibly addons - i'll try a fresh profile and see.

**Comment by grenzor** [comment]
OK, just tested - it seems it might be addons but it's a little weird:

Installed only YT+ in a fresh profile, logged out, clicked YT and settings were saved. 

But here's a weird part:

I went back to check my default profile and settings were saved as well (i.e. the didn't reset like previously). Logged out and back in to check settings on default profile - they were still saved.

Then I manually changed settings again just to test, logged out, checked default profile settings and this time settings reset to default.

For some reason it seems using the fresh profile, then my default profile did not reset the settings even after a log out which makes me wonder what's the reason for this.

**Comment by ParticleCore** [comment]
If you want to find out what the cause of this might be then try with the add-ons first (if you don't have too many), turn one by one and test the problem each time until it returns.

The other test is the Firefox settings that you might have changed, you can find the most important changes that have been made in `about:support` under the table titled `Important Modified Preferences `. Start looking for settings that might sound like ones to cause this problem, such as cache control, history size, data purge, etc. and then try changing those in your new profile that you used to test and see when the issue returns again.

Problem is, if you can't find it easily at first then it will be a tedious task because your issue occurs between sessions.

If you happen to find out the cause of it do share, it will be very helpful for any other users in your situation, even if it isn't related to this extension.

**Comment by grenzor** [comment]
OK I seem to have found the problem:

It's the way Firefox is closed. If FF is closed properly with my settings saved then I log out, log in and open firefox then visit Youtube, my settings are saved.

BUT

If I have Firefox open with a Youtube tab and logout with properly closing Firefox, log back in, open Firefox it then reloads the youtube tab and it asks for me to customize YT+ settings.

**Comment by ParticleCore** [comment]
That's really strange because it suggests that your browser is failing to ship data to the add-on once it loads in that situation, causing it to load as if it was a new installation. I have tried replicating on two different machines, both running Win7, and nothing of this kind happened so either it is related to your setup or to something else.

And you can replicate it with the new profile as well or just with the old one?

**Comment by grenzor** [comment]
I can confirm that I can reproduce this with fresh profile with only YT+ installed.

Try this to reproduce it:

1) Open Firefox clean (no tabs), then open Youtube with no YT+ settings saved (so it asks you to customize)
2) Import settings, click save and load, click save
3) Reload youtube.com in same tab and visit any youtube video
4) While video is playing, log out/restart the computer
5) Log back in, open Firefox and it should automatically reload the Youtube tab

See if then it asks you to customize settings again

**Comment by ParticleCore** [comment]
Tried log off and restart, no problems showed up, even tried with the Chrome and Userscript versions. When your issue happens open both the web console (Ctrl + Shift + K) and browser console (Ctrl + Shift + J), if there are no errors then I am afraid there is nothing else that I can do.

From your details I can only assume that the Firefox version you are using has some sort of problem with retaining the settings when shutting down that way.

One last thing you can try is check for the settings file, see if it is missing after restarting/logging off. It should be located in the following path: `C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<yourprofilename>\jetpack\particle@particlecore.github.io\simple-storage`

Obviously this is for the Windows system, but it should help guide you on Linux. In that folder it should have the settings saved in a file named `store.json`, see if it is missing after you log on and before you open Firefox again. If it is then something is definitely removing it at a certain point and this is not something I coded my add-on to do, if it is still there check its contents and see if it contains the settings you saved or just the default ones.

**Comment by grenzor** [comment]
Using the above steps to reproduce does seem to wipe out the settings in store.json

I'm not sure what could be causing this, possibly something to do with the OS + file/folder permissions. 

This seems to be a lingering issue and similar to: #76
Where the YT+ icon wouldn't show up at all but you seem to have fixed it and now it does show up.

**Comment by ParticleCore** [comment]
The store.json file remains there but only empty inside? I can't think of anything that might cause that. The only thing left that I can think of is to try the userscript version with Greasemonkey, if the problem doesn't happen there then it should be a good alternative to the current problem. I will still pay attention to the code to see if I can find anything that might be causing this, but for now there's nothing else I can think of.

**Comment by grenzor** [comment]
store.json still exists but it's empty. i'm out for ideas as well. 

Maybe looking at the code will help as it did with those icon bugs. 

I'll keep a lookout to see any obvious causes of this too.

**Comment by ParticleCore** [comment]
I've been trying to replicate this problem on Ubuntu but the settings are all being kept saved while replicating your steps. What type of Linux are you using (distro, name, version), if you don't mind me asking?

**Comment by grenzor** [comment]
On Mint 17.3

**Comment by ParticleCore** [comment]
[Another user](https://www.reddit.com/r/firefox/comments/43i2v2/this_addon_youtube_plus_always_loses_its_settings/) also reported the same issue on Mint as well, I think we can rule safely that this is restricted to Firefox on Mint only. I will try to find a way to get Mint on portable USB with persistence enabled so that I can try to replicate the problem and see if a fix can be found.

**Comment by ParticleCore** [comment]
@grenzor I've updated YT+ to 1.0.5 with a fix that should prevent this situation from happening again, let me know if it works for you as well.

**Comment by grenzor** [comment]
Unfortunately, it still resets. Also now it seems upon opening FF after logout/restart the icon on the yt page disappears when you first visit youtube.com and you have to refresh a few times for the icon to come back (which then still asks me to customize settings).

**Comment by ParticleCore** [comment]
It appeared to be working between logouts, but does not survive a restart. I have been trying to find what causes it with no luck, this is a bug with Firefox just on Mint. I even tried removing any method of modifying the settings file to see if that was the cause and yet the file would still go empty in the same way. The only solution is to use the userscript version with Greasemonkey since this problem doesn't appear to affect db files, which is how GM saves its settings.
