### ISSUE TITLE
"Memorize audio volume" either doesn't work or it did nothing special compared to Youtube default behavior

### ISSUE THREAD

**Issue by fireattack** [ParticleCore/Particle#191]
Since youtube already be able to memorize your last volume, I initially guess this one can memorize volumes of different videos.

But test shows there is no difference from the Youtube's default behavior: if you change volume to 80 on one video , it will be saved. So when you open another video, it will still be 80. No matter if I turn on this option or not.

Is there anything I missed?

Thanks.

**Comment by ParticleCore** [comment]
This feature is mostly for users that have cookies disabled. Since YouTube saves this setting in a cookie, the next time these users open YouTube it doesn't remember which volume it was set to because the cookie is not there anymore.

Additionally, even for other users, this cookie expires after a certain time. With this feature none of these problems occur.

**Comment by fireattack** [comment]
Thanks!
