### ISSUE TITLE
"Video quality" information missing if you picked a higher one in "Default video quality" than the possible one

### ISSUE THREAD

**Issue by fireattack** [ParticleCore/Particle#192]
To repo:

1. Set default video quality to 4K.
2. Open this https://www.youtube.com/watch?v=8G5UnDo2pRM
3. Click on the gear icon on the right bottom corner.

What happened: in the "quality" row, nothing shows up.

What it should do: it should still show 1080p60, since it's the quality the video has. It helps if user want to check the quality of the video. The fact that your setting is higher than possible resolution shouldn't matter here (player picks the highest resolution anyway).

**Comment by ParticleCore** [comment]
It is defaulting to the highest possible one or lowest (depending on the default quality selected) whenever this occurs but it is not showing its label in the quality button, this bug is on the YouTube side ever since they made the change to the HTML5 player. 

If you right click on the player and select `Stats for nerds` you will see that it is playing the highest available quality in the `Resolution` line despite not showing it on the quality button.

This bug should be reported to the YouTube team instead via the "Send feedback" link found at the bottom of any YouTube pages, it is not something I can fix on my end without adding a large and unnecessary overhead to the extension.

**Comment by fireattack** [comment]
@ParticleCore I didn't get it, since Youtube itself doesn't even provide the option to lock "default quality", their player surely won't know what to display if you choose force one that does not exist? Why it should be fixed on their end? I mean, a simple logic should be fix it (e.g. looking for quality of the video first, then compare it to user's setting, and choose the closest existing one). Other similar scripts seem don't have this problem (e.g YouTubeCenter).

**Comment by ParticleCore** [comment]
>I mean, a simple logic should do the trick

That simple logic is not so simple when you try to implement it on the extension, which is why I said it would require an unnecessary large overhead.

Other scripts do not use the same method that YT+ does when starting the player with the predefined quality, that is why at first the videos will always start with a lower quality and only after they start playing they change to the selected quality.

>Why it should be fixed on their end?

They had the fully functional quality handler in the beginning, both on the Flash and HTML5 players, eventually when they finally made the switch to HTML5 default they did not continue with the function that was working previously.

The fact that it defaults to the highest available quality is already enough to show that the player can play the correct quality if the selected one is not available, as it used to do before, only now the correct label is missing.

Otherwise how would the `suggestedQuality` option even work for the [embedded videos](https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player) if this function did not exist? The player is exactly the same as the one on YouTube, only the parameters change.

**Comment by fireattack** [comment]
Got it, fully understand that you want to keep this extension concise and fast.

Thanks again!

**Comment by ParticleCore** [comment]
Exactly, otherwise if the trade-off was small I would already have implemented a patch on my end. I do still try to find a better way to work around this issue now and then, but so far the solutions I have found impact performance negatively which does not make it a worthwhile solution.

**Comment by ParticleCore** [comment]
Now that I am testing it -because of this conversation- I see that the YouTube "Auto" quality choice set to the selected quality appears to be stable, unlike before, meaning that it is not starting playback with a lower quality and then changing to the one the user chose.

I will continue testing it further to see if this behavior is stable and consistent across both browsers, if it is I will implement it in the next version update.
