### ISSUE TITLE
Stop loading if using the "Pop Out" mode

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#208]
The main video still loading, and now I have 2 videos loading at the same time, and my internet speed isn't that good to deal with it.

Firefox 44.0.1
GreaseMonkey - UserScript

![load](https://cloud.githubusercontent.com/assets/13389907/12947975/5a13bfda-cfe6-11e5-899f-97cfa87212eb.PNG)

**Comment by ParticleCore** [comment]
I can try stopping the video instead of pausing, it is the only way I can see for now that prevents the continued loading, however every time you open it in pop out mode the main video will change into cued mode:

![ss](https://cloud.githubusercontent.com/assets/9222661/12948372/2f668708-cff1-11e5-8d3c-a793656a397e.png)


Other than that, are you enjoying the pop-out mode? No problems with it so far? (besides the one you mentioned)

**Comment by mauriciocolli** [comment]
The Pop-out mode is very good, and I'm using with the "Always on Top" extension, and it makes perfect, it's like the panel feature on Chrome.
![sni](https://cloud.githubusercontent.com/assets/13389907/12948694/d22a53f4-cfea-11e5-880a-be64507b5c7b.PNG)

And yes, no more problems so far. Good work!

**Comment by ParticleCore** [comment]
I've implemented a fix for this in version 1.1.0, the main player should also remember where it was playing in case you want to resume playback on it, as well as not load any more data once you open in pop-out mode.

Let me know if it works well for you.

**Comment by mauriciocolli** [comment]
Thanks for the quick fix, now it works like a charm!
