### ISSUE TITLE
[Firefox] Not updating automatically 

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#22]
Probably because the addon's author name is Yonez instead of Particle, so the addon doesn't recognize the account the addon is registered to at AMO?

Also, it's pretty difficult to find Youtube Plus just by searching it on Google or even AMO, which means it might not get enough visibility for what's worth. Maybe you could consider a name change or do something to promote the addon (if you want to, of course).

Thanks for your work!

**Comment by ParticleCore** [comment]
This is a problem caused by AMO itself. Until they review and approve my add-on, its installation has to be manual and that is also why they won't show my add-on when searching for it, sadly. The author name doesn't have any impact on this aspect.

[Their reviewing queue times are excruciating](https://www.omniref.com/blog/blog/2014/09/08/writing-extensions-for-firefox-is-barely-worth-the-trouble/) (after already 10 versions updated, I am still 169th in the queue out of 246, but I am hopeful that with the upcoming signing system this issue will be improved.

The original name of the software is Particle, which I will change to in case problems merge due to the use of YouTube in the current name, changing it now is not something I have the need to do. I've already made a small promotion of it on reddit and people are noticing it. If it becomes popular then it will become a relevant result in any search result, the same thing happened with softwares with similar vague names.
