### ISSUE TITLE
Video navigation/time bar now only shows NaN:NaN

### ISSUE THREAD

**Issue by keLston** [ParticleCore/Particle#221]
Browser Name: Firefox

Browser Version: 44.0.2

Operating System: Windows 7 x64

Software Type: Addon

Software Version: 1.1.5

Userscript Manager: N/A

Userscript Version: N/A

Problem Description: With Youtube+ enabled, there is no longer a working video playing status bar (the red thingy) or any video player controls. The time when mousing over the bar that is stuck on the left side is now only showing -NaN:NaN

Steps to reproduce: Just play any video with Youtube+ enabled. Disabling it seems to restore player controls.

Additional details: Screenshot of the issue: http://i.imgur.com/A8LQIdU.png

**Comment by mauriciocolli** [comment]
Do you have any other extension or UserScripts?
Here is working perfectly, both addon and usercript, try to wipe your browser cache.

**Comment by ParticleCore** [comment]
I am unable to replicate this issue on the same setup, please disable any other add-on and userscript you might have installed and leave only YT+ enabled, restart Firefox and see if the issue still persists.

**Comment by keLston** [comment]
Okay so here's where this gets interesting.

When I got the email updates saying neither of you could replicate it, the first thing I did was change nothing and load up a Youtube video and... found I also couldn't replicate it. I loaded a bunch of Crash Course videos and lo and behold, everything was fine and I thought I was an idiot.

So I decided to directly go into my history and go to the video I first noticed it on: https://www.youtube.com/watch?v=qAHSUTB5BJc

When I did that, I lost the player controls and it completely buggered everything and now I could no longer get the player controls back. Reloading the tab didn't fix it. Restarting Firefox didn't fix it. But disabling Youtube+ restored the player's controls which is why in my original report, I stated disabling Youtube+ fixed the problem. While it is bugged, when I re-enable Youtube+, I lose the player controls again.

To make it even more interesting, I disabled all my addons except Youtube+ and NoScript.

I restart Firefox, have my controls again, but as soon as I go load that specific video, I lose player controls and now I am stuck with the bug again.

Interestingly, it seems like when it becomes bugged, the only way for me to fix the problem is enabling or disabling an addon then restarting Firefox and making sure not to view that specific video!

So apparently, the replication process isn't "watch any video", it's watch that specific one with Craig Ferguson and his robot puppet!

**Comment by ParticleCore** [comment]
I've tested that video and nothing happens of the sort. I asked to disable everything except YT+, NoScript might be causing a conflict which is why disabling everything (except YT+) should be followed through to rule out a conflict caused by another add-on.

Additionally this could also be caused by stream format (DASH-disabled, something else in the Firefox preferences) which is why it is a good idea to follow the troubleshooting guide to see what might be causing this problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

Plenty of issues here have been solved by following that guide because it allowed users to discover that the problem did not lie with YT+ but with something else, like a conflict or browser setting they changed in the past, VPN settings even, etc.

**Comment by keLston** [comment]
Everything disabled but Youtube+: http://i.imgur.com/aPdKtRA.png

Problem replicated: http://i.imgur.com/NIPIfKR.png

**Comment by mauriciocolli** [comment]
Do you already try wipe your cache?

**Comment by keLston** [comment]
Yes. Both with Firefox's clear data + CCleaner

**Comment by ParticleCore** [comment]
Did you follow the troubleshooting guide I linked?

**Comment by keLston** [comment]
Yep.

Only the final step with a new profile results in the problem not being able to be replicated.

I don't know what browser setting would cause the conflict as I have not modified any settings in over half a year.

**Comment by ParticleCore** [comment]
So we can assume with a reasonable degree of certainty that this is being caused by something external to YT+, now to find out what might be hard.

From the graveyard of YouTube problems leading to back when HTML5 was being first tested out, a problem very similar to this one was link to the Java **plugin**, so try disabling **any** plugins you have on Firefox in your default profile, restart and see if the problem shows up.

If it does then it might be a browser setting, in which case you will have to find the important ones that have been changed and reset each one individually until the problem disappears. To find this list of important changed settings go to `about:support` and scroll down to the *Important Modified Preferences * table. Start with settings that might sound like the ones that could cause this problem, related to video, audio, network communications, etc.

**Comment by keLston** [comment]
I set each of the Plugins to "Never Activate" but the problem still occurs.

I went to the about:support page and uh, there are quite a load of Important Modified Preferences and i'm not even sure where I would start since i'm not sure what the default setting of these are based on Googling them (as most of these settings only comes up in results for other troubleshooting forum posts with no suggestions to modify the settings).

**Comment by mauriciocolli** [comment]
Go to `about:config` and see the default, or reset

**Comment by keLston** [comment]
I'm not sure what that means. When I go to about:config, all I see for any of the modified values is that they are "user set" with no indication of what the default was supposed to be.

For example, all of these: http://i.imgur.com/AUMOyU9.png

**Comment by ParticleCore** [comment]
@keLston Simply right click the preference you want to reset and select "Reset"

**Comment by mauriciocolli** [comment]
Oh sorry, I mean see if them are on default or not, and reset to see the Default value

**Comment by keLston** [comment]
I reset all the gfx and network ones that either differed or didn't appear at all from the unbugged "new" profile. There are some that are added there that look like they were because I disabled the plugin like adobe.enabled is set to 0 so I didn't reset that.

However, the problem persists.

**Comment by ParticleCore** [comment]
You have to go through each one that is not with its default value, all of them. There's no guarantees that it might be one that looks like the culprit, it can be another one that is completely unrelated.

When you did the last step and you saw that the problem could not be replicated you confirmed that something in your previous profile was causing the problem and not YT+. You already disabled the other add-ons, the plugins and the problem persists. Now all that is left (as far as I can see) is to reset each setting individually until the problem disappears. It can be the last *user set* preference of the entire list, it could be the first, we can't tell until you go through all of them and see when the problem disappears.

**Comment by keLston** [comment]
I'll be completely honest here.

I like fixing bugs and figuring out the cause. However, there are some settings that I look at them like "Driver Version" or "DeviceID" and in all honesty, i'm not going to reset those for what essentially is a minor annoyance since it matches the new profile that doesn't bug out and for lack of desire to break something else since Googling these settings has apparently no documentation for what any of them do.

**Comment by ParticleCore** [comment]
Of course those kinds of preferences shouldn't be reset, but whatever the cause might be it is very likely one (or more) of those preferences that might have been modified either by yourself, an add-on or a software "optimizer" (those are very known to break more things than optimize, especially network optimizers).

Alternatively you could do what others chose to which is to use the new profile, however you have lots of configurations and add-ons so I don't think it would be very practical to do this, and using a profile migration would not be a good choice since it would most likely also migrate the problem to the new profile.

Either way it is up to you what you prefer. From YT+ there is nothing that can be done since this isn't related to the add-on as it has been confirmed.

One last suggestion, in the `about:config` page search for `media.` (with the dot included). Reset all user set values of the ones that show up *except* `media.hardware-video-decoding.failed`, `media.youtube-ua.override.to` and those that contain `media.gmp-`.

**Comment by mauriciocolli** [comment]
One last suggestion too,go to `about:support` click on Profile Folder - `Show Folder`, close Firefox completely, in the folder is a file:
`prefs.js` rename to whatever you want or backup to an other folder, and delete the original. Try to open Firefox, if it didn't work just rename or copy the backup file back.
Backup of the entire folder is useful too.

And the last thing you could do is to use the Firefox Sync to migrate to a other profile, but without the preferences checkbox check.

**Comment by keLston** [comment]
Okay so I went through and reset everything with the Refresh Firefox button from: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

From there, I reinstalled all the addons I had previously (I think I actually missed a couple like the Hide Fedora and MEGA addons but no big deal) to get it as close to the previous state except for the defaulted browser settings and the sanitized profile.

The result is... the problem can be replicated.

**Comment by ParticleCore** [comment]
A fix for this issue has been released in 1.1.6, let me know if it works for you too.

And thanks to all the help you people provided, it was very valuable to solve this problem.

**Comment by keLston** [comment]
Tested with both the sanitized and the new profiles, both appear to have 1.1.6 working without issue on both videos that I was able to get the problem to crop up.
