### ISSUE TITLE
Few options are broken

### ISSUE THREAD

**Issue by JourneyOver** [ParticleCore/Particle#224]
Browser Name: Chrome

Browser Version: 48.0.2564.109

Operating System: Windows 10 64bit

Software Type: script

Software Version: 1.1.5  /  1.1.6

Userscript Manager: Tampermonkey

Userscript Version: Beta 4.0.5070

Problem Description: Options - `Fit to page in theater mode` (doesn't work)
`Fit to page max width` (doesn't work)
There may be others but these ones I noticed right off the bat.

(the floating player seems to have been moved as well (it used to pop up to the right over the "next video and the video list" but now it pops up to the left in the corner) as you scroll down reading comments 

Steps to reproduce: Have YT+ enabled and try different widths in the `fit to page max width` or try `fit to page in theater mode` while in theater mode both these just cause the video to pop out to its floating player in the top left corner (if the popout player option is enabled otherwise it just doesn't do anything).

**Comment by ParticleCore** [comment]
Ah, I see the problem, you are using a number without `px` in front. In the `Fit to page max width` add the width you want together with `px`, which in your case I assume is `1645px`

Try it out and see if it starts working for you too.

After that it should work correctly for you. This allows users to enter either percentages (`80%`for exampe) or pixels. Perhaps I should make it more clear in the wiki.

Regarding the floating player, it has no longer a predefined position, it shows on the top left because you haven't moved it yet. You can simply click and hold the player to move it around to where you prefer.

But I guess it would be better to place it on the bottom right corner as default position instead of top left.

**Comment by JourneyOver** [comment]
@ParticleCore Ah no wonder it wasn't working as expected, swear before I never had to enter the px into the field for it but maybe I'm just being forgetful haha... I should know this stuff since I do a lot of css coding...

Didn't know the floating player no longer had a predefined position, only noticed that it got moved this morning glad I can move it around though now. so guess these two issues are resolved then >..<

**Comment by ParticleCore** [comment]
Glad to hear that, then I will publish the new version with the fix for the previous -NaN:NaN issue.
