### ISSUE TITLE
Cogwheel missing in floating player

### ISSUE THREAD

**Issue by dfgdfg12** [ParticleCore/Particle#225]
Hello,
here's the system:
Browser Name: Firefox
Browser Version: 38.6.1 ESR
Operating System: Win 10 x64

Problem Description: Since version 1.1.3 the cogwheel is missing in the floating player. Resetting the settings doesn't help, only going back to v1.1.2 does.

**Comment by mauriciocolli** [comment]
I think it's a bug on this Firefox version, but you can workaround set the Float Width player value greater than 400, on the latest version of Youtube+:
Youtube+ setting -> Video ->
![width](https://cloud.githubusercontent.com/assets/13389907/13152046/46a517b8-d654-11e5-92ae-f44abbc7e378.PNG)

But this only resolve this bug, the title bar, the Watch later and Share Button is missing I recommend you to update your Firefox, look:
In Firefox 38.6.1 ESR:
![fix](https://cloud.githubusercontent.com/assets/13389907/13152139/be01c31a-d654-11e5-8e07-e1aa3bd30c3e.PNG)

In the latest version of Firefox:
![fix2](https://cloud.githubusercontent.com/assets/13389907/13152144/c8399236-d654-11e5-9816-fd5b068923ec.PNG)

**Comment by ParticleCore** [comment]
It is by YouTube design, the smaller the player the less controls are visible. Previously if you were to use a size smaller than 350px it would not show the volume slider, which is why I limited the minimum size it can have.

A workaround is to set a bigger size for the floating player.

@mauriciocolli Will do, thanks for the suggestion.
