### ISSUE TITLE
YouTube Live Dashboard Problem

### ISSUE THREAD

**Issue by HKpKsON** [ParticleCore/Particle#231]
Browser Name: Firefox (But it is a cross-platform problem)

Browser Version: 44.0.2

Operating System: Windows 10

Software Type: Add-on

Software Version: 1.1.6

Problem Description: Unable to load YouTube Live Dashboard

Steps to reproduce: Access https://www.youtube.com/live_dashboard

Additional details: Possible fix is to prevent this page from loading the plugin
![ytplus](https://cloud.githubusercontent.com/assets/2476306/13250039/ae7104e4-da62-11e5-93f3-648387b7ce70.png)

**Comment by ParticleCore** [comment]
I cannot test this on my end because I do not have a phone to pass the required verification steps in order to access the live dashboard.

White listing is not a good option because I cannot guarantee they won't change the URL since it is a beta and I don't care much for ending up with lists of white listed URLs. The embed page was already enough.

I will try one fix that should work but first I will need your help. In that Live dashboard page open your console (Ctrl + Shift + J) and enter the following:

`document.getElementById("creator-page")`

Does it show any `div` element?

**Comment by ParticleCore** [comment]
Nevermind the previous, a friend allowed me to use his account to test the problem. Is the problem just related to the "Loading" areas never loading or are there more problems?

**Comment by HKpKsON** [comment]
That's just it. Hope you got your solution done and fix it!
PS. You replied quickly!

Happy Coding,
KEN

**Comment by ParticleCore** [comment]
This has been fixed in version 1.1.7, let me know if it works for you too.

**Comment by HKpKsON** [comment]
It's been fixed, thank you.
