### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ThisIsTooHardStepToTake** [ParticleCore/Particle#239]
Did YouTube change something or is this a bug in Chrome or YouTube itself?

![untitled](https://cloud.githubusercontent.com/assets/17030424/14001441/84cac708-f14e-11e5-84d3-341ddde25899.png)

Screenshot above shows that there's times under the progress bar, obviously there's no bug in YT+ because this happens also with YT+ disabled. I just wanted to ask this question because you might know things about the latest YouTube stuff.

Chrome Canary 51.0.2688.0 x64
YT+ 1.1.9
Windows 7 Enterprise x64 SP1

**Comment by ParticleCore** [comment]
I cannot replicate it in current Chrome Stable, but that does not mean it isn't a problem with YouTube since it usually tests new changes to certain users and not others. I'd suggest reporting it by clicking on the "Send Feedback" link found at the bottom of the YouTube page and report it on the Chrome forums since you are using a canary version, the bug could also be related to a new browser change.
