### ISSUE TITLE
Position of scrolling video

### ISSUE THREAD

**Issue by Ingrido** [ParticleCore/Particle#24]
Would it be possible to add an option to reposition the scrolling video (so instead of it being locked mid-height, you can position it higher up or lower down) or better yet being able to freely customise the x and y position/size of the scrolling video?

**Comment by ParticleCore** [comment]
It was my initial intention, but due to too many variables and complications I decided to stick with the simpler method which is less memory intensive than the other.

I am still considering adding the custom floating player as a new option in the future, as long as it doesn't degrade the overall experience.

**Comment by ParticleCore** [comment]
Also I just want to let you know that closing this does not mean that I rejected the request, it's mostly to keep the issue tracker focused on the issues. I will have to build a better system just for feature tracking.

**Comment by ivantyr** [comment]
![2015-06-18_09-29-29](https://cloud.githubusercontent.com/assets/6587147/8232298/89c93a7a-159c-11e5-8797-d60e85a46948.png)

Can I request for this to be an option too? At least to have the video overlay on the opposite side of the screen, so that browsing the sidebar is possible

**Comment by ParticleCore** [comment]
@ivantyr I'd appreciate if you'd make your request in a new thread since it isn't related to this one, otherwise if I need to re-read your request I cannot find it easily via the search form.

Regarding that request, I am working on improving the floating player, my goal is to provide an interface which will allow the user to move the player around, stick to the sidebar or turn off the floating player. It will take some time to finish since it ads lots of variables that need to be tested before release.

**Comment by ivantyr** [comment]
My bad, I thought the title and description referred to this

**Comment by ParticleCore** [comment]
Disregard my previous request, I thought this issue was completely unrelated to yours, you did well in posting here.

**Comment by ivantyr** [comment]
I've already deleted the comment, here

![2015-06-18_09-29-29](https://cloud.githubusercontent.com/assets/6587147/8232298/89c93a7a-159c-11e5-8797-d60e85a46948.png)

Option to have the video overlay on the opposite side of the screen, so that browsing the sidebar is possible

**Comment by ParticleCore** [comment]
Sorry for the mistake, the email chain I had showed a different issue above yours leading me into error. About the request, it is like I said, I am still working on it and will take some time to be completed, quite a few aspects to consider and make sure that it works as best as possible, hopefully with no errors once it is finished.

**Comment by ParticleCore** [comment]
@Ingrido and @ivantyr I have added the ability to move the floating player around or stick it to the default position on the sidebar in the recent version 0.2.3, do let me know if it works correctly.

**Comment by Ingrido** [comment]
I don't think the two new buttons are appearing for me.

**Comment by ParticleCore** [comment]
@Ingrido are you using the version 0.2.3?

If you are then this is what should look like:

![ss](https://cloud.githubusercontent.com/assets/9222661/8280887/bbfa74c2-18d1-11e5-92a8-35a4b76459fa.png)

**Comment by Ingrido** [comment]
Yes, i'm using 0.2.3, mousing over the scrolling player doesn't show anything.

**Comment by ParticleCore** [comment]
Could you give me more information?

Are you using Firefox or Chrome?

Are you using the userscript version of YT+ or add-on/extension?

Is the YouTube player the flash version or HTML5 version?

If you have any other userscript/extension running could you disable them all except YT+ and see if the buttons appear again?

I just tried on both browsers and they show up correctly.

**Comment by Ingrido** [comment]
Firefox 39b7
Using the 0.2.3 version of YT+ from the Mozilla Add-ons website
Youtube player is HTML5
The only add-ons I use are SpeedDial, DownThemAll, uBlock Origin and YT+, tried disabling every add-on but YT+ and restarting browser but still nothing.

**Comment by Ingrido** [comment]
I've noticed that if I disable Autoplay and click play on the scrolling video the buttons do appear for a second or two on the black loading screen before disappearing.

![YT+ Scrolling Video 1](http://i.imgur.com/jqrkzU8.png)
![YT+ Scrolling Video 2](http://i.imgur.com/kv82QeR.png)

**Comment by ivantyr** [comment]
In my case I found no issues or bugs so far
I'm on 40.0a2 using the userscript version, using the HTML5 "new" Youtube player
Autoplay was already disabled for me, so I don't know if that could affect anything too

**Comment by ParticleCore** [comment]
So it seems that the issue is related to the player version. Once again I forgot to check if the buttons were working correctly with the standard player (I too am using the new transparent player). Will address this issue on the next version, sorry for the inconvenience, @Ingrido

**Comment by ParticleCore** [comment]
@Ingrido I've released the new version 0.2.4 which should now show buttons with the default YouTube player, do let me know if it works if possible.

**Comment by ParticleCore** [comment]
@ivantyr So I take it that for you the moving feature is working correctly and remembering its position?

I might still improve it in the future, make it so that it remembers the position in relation to the middle of the page instead of the entire page, but for now it should be enough the way it is which is simpler.

**Comment by Ingrido** [comment]
Seems to work perfectly now, thank you very much :)

**Comment by ivantyr** [comment]
@ParticleCore yes, the player stays in position even after a page reload, didn't notice anything wrong

**Comment by Betsy25** [comment]
Sorry to bump this up, I had the "small" player up when showing comments, and using the drag icon, I dragged it too far up, showing only the bottom of the video & controls, and now it stays there and I find no way how to reset the original position. I tried disabling the option "Player always visible when reading comments" or even restarting the browser, but now I'm left with a screwed up screen when scrolling the comments into view. Only thing I could do is a complete config reset, it would be better to have some "reset position" button next to the option.

**Comment by ParticleCore** [comment]
@Betsy25 It is a problem and the only way to fix it is to reset the settings, remember to save your blacklist somewhere because it will also be erased.

The feature was implemented with a bit of hurry so the player remembers its position according to the page instead of the center, which would be preferable, but I will probably add a Reset position button in front of the Always visible option to allow the user to fix this issue by himself without having to reset the entire settings.

**Comment by ParticleCore** [comment]
@Betsy25 I've just released the version 0.2.6 which should prevent the problem you described from happening again, you should be able to freely move around the entire page with no concerns, try it out and let me know if it works well.

**Comment by Betsy25** [comment]
@ParticleCore It works wonders ! Thank you so much ! :+1:
