### ISSUE TITLE
 360° videos and player always visible mode

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#247]
The issue is on player always visible mode in 360° videos, when you try to look around the video moves (it works how the feature is supposed to).
A fix that I've been thinking is exclude the `webgl` div, that is present on 360° videos, and it's already implemented for the `yt-chrome-bottom`, in my tests it works as expected.

**Comment by ParticleCore** [comment]
It was an accounted situation during the development and moved forward regardless. The floating player feature is mostly present to provide the user with the ability to continue watching the video when scrolling down to the comments and it allows movement in order to read something that was blocked by the player. The 360º functionality is an extra that wasn't worth the trouble to make it compatible with the floating player, the experience is more appropriated in normal viewing mode and not in the floating player mode.
