### ISSUE TITLE
Background turns dark.

### ISSUE THREAD

**Issue by OddmarDam** [ParticleCore/Particle#251]
Hi.

Is it possible NOT to darken the background. I would like to be able to see the suggested videos and comments. But all i see is a black background arround the video ?
![capture](https://cloud.githubusercontent.com/assets/4441007/14586356/c453d5e0-0495-11e6-8a1a-5c728e478436.PNG)

**Comment by ParticleCore** [comment]
That's because you enabled the cinema mode: https://github.com/ParticleCore/Particle/wiki/Features#adv_cinema

To turn it off click on the cinema mode button available in the advanced options below the video player, it is the second button from the right

![c453d5e0-0495-11e6-8a1a-5c728e478436](https://cloud.githubusercontent.com/assets/9222661/14586403/83408170-0486-11e6-8127-5e40175f63d3.PNG)

**Comment by Gotolei** [comment]
Bit of a bump, but is there a way to prevent it from activating? I tried it out just once, and now every single time I watch a video it re-enables. Even if I turn it off, as soon as the video's playing again it dims back down, and there's no apparent way to stop it from happening.

**Comment by ParticleCore** [comment]
@Gotolei Please follow the troubleshooting guide to see what might be causing this problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

It should not be turning dark if you disabled the Cinema mode via the button marked in the image above, something else might be causing that problem.

**Comment by Gotolei** [comment]
Hm, seems to be behaving now that I'm actually poking at it. It was acting up as I was going through a playlist and using full-browser mode extensively, but once I started messing around in another tab the problem with cinema mode seemed to right itself.
Guess I'll keep an eye for if/when starts happening again, and if it's reproducible somehow.
