### ISSUE TITLE
Cosmetic issue, shadow of floating player

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#254]
_This is just a cosmetic issue._
This happen when you click in the gap (of the floating player) between the volume and the setting button.
The shadow of the floating player disappear and only reappears when you click outside or the other parts of the player.
I'm pretty sure that is the cause:
`:focus {  box-shadow: initial !important;` - _[YouTubePlus.css:543](https://github.com/ParticleCore/Particle/blob/gh-pages/stylesheets/YouTubePlus.css#L543)_
https://i.gyazo.com/0104bfa5e6311bdc673c21b9754c0c21.mp4

Another solution (I think is better)  is add a `!important` on the `box-shadow` of the floating player:
 _[YouTubePlus.css:48](https://github.com/ParticleCore/Particle/blob/gh-pages/stylesheets/YouTubePlus.css#L48)_

Happens on both Chrome and Firefox

**Comment by ParticleCore** [comment]
Thank you for the report, the fix has already been implemented but the Firefox add-on will have to wait for a new version because due to AMO restrictions it ships with it's own CSS file. The other versions (Chrome extension and Userscript) use the remote CSS file which can be re-downloaded by pressing Ctrl + F5 on a YouTube page.
