### ISSUE TITLE
Checkboxes are invisible with extension enabled

### ISSUE THREAD

**Issue by Skellingtor** [ParticleCore/Particle#263]
Browser Name: Chrome

Browser Version: 50.0.2661.102 (64-bit)

Operating System: Mac OSX 10.11 El Capitan

Software Type: Extension

Software Version: 1.2.5

Problem Description: Checkboxes disappear when using extension. They're still there, but invisible. They return to normal once the extension is disabled or removed. This is a big bother because I use other extensions that are affected by this. The annotations section is also.

Steps to reproduce: Have the extension enabled.

<img width="216" alt="screenshot 2016-05-23 03 30 55" src="https://cloud.githubusercontent.com/assets/19526287/15462157/1ef9e616-2097-11e6-960d-71e0ff49a09d.png"> <img width="218" alt="screenshot 2016-05-23 03 31 48" src="https://cloud.githubusercontent.com/assets/19526287/15462158/1efa2dc4-2097-11e6-8364-aa2b7430d081.png">

**Comment by ParticleCore** [comment]
I am unable to replicate this. In which YouTube pages exactly are check-boxes disappearing?

Regarding the conflict with another extension I am sorry but that means they are not compatible with each other. From what I can see vidIQ is overriding the default YouTube check-box layout which results in the problem you mentioned with YT+, to solve this vidIQ needs to make their extension's stylesheet persistent so that their essential elements are not modified by other extensions. From my end there is nothing I can do to solve this.

**Comment by ParticleCore** [comment]
I will close this for now, if you still need help follow up on my previous reply.
