### ISSUE TITLE
Middle clicking channel name doesn't work.

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#267]
Browser Name:  Google Chrome 

Browser Version: 52.0.2743.24 beta-m (64-bit)

Operating System: Windows 10

Software Type: Userscript

Software Version: 1.2.9

Userscript Manager: Tampermonkey

Userscript Version:  4.0.69

Problem Description: Middle clicking a channel name doesn't lead to the videos section of that channel.

Steps to reproduce: Go to subscriptions or any video and middle click the channel name. It opens a new tab but not in the videos section as it used to.

Additional details: This is with the 'default channel page' setting set to 'videos'.
It used to work before today.
I tried the extension version of YT+ as well, same problem. Even with all other extensions disabled.
I reset the YT+ settings and only changed the 'default channel page' to 'videos'. Still had this problem.

It works normally when just left clicking the channel name.

**Comment by ParticleCore** [comment]
I cannot replicate this on Chrome stable 51.0.2704.79, the predefined channel page is changed correctly using middle-click on the channel name. However I was able to replicate it on Chrome beta and since it is an experimental version I will wait for it to reach stable before making any code changes because this behavior might not be intentional, and without any sort of release notes I cannot confirm this besides waiting for it to reach stable which should be on 26th this month.

Until then I will mark this as invalid for now and will be watching for the stable release, if the behavior persists then I will try to push a fix.

**Comment by ParticleCore** [comment]
It looks like this change has been intentional:

>Regarding the spec, here is the link to the spec:
>https://www.w3.org/TR/DOM-Level-3-Events/#event-type-click
>as it's stated the click event should only be fired for primary button of the mouse

https://bugs.chromium.org/p/chromium/issues/detail?id=611972

I will try to push a fix for this as soon as I can

**Comment by ParticleCore** [comment]
This has been fixed in version 1.3.0, let me know if it works correctly for you now.

**Comment by Eisys** [comment]
Yep, it works now.
Thank you very much.
