### ISSUE TITLE
Show Comments

### ISSUE THREAD

**Issue by Superluigi6** [ParticleCore/Particle#268]
Browser Name: Vivaldi (it can run Chrome extensions though)

Browser Version: 1.2.490.39

Operating System: Windows 10 

Software Type: Extension

Software Version: 1.3

Userscript Manager: N/A

Userscript Version: N/A

Problem Description: Is there a way to show comments on YouTube automatically, without the need to press a button?

Steps to reproduce: Go onto a YouTube video and scroll down to where the comments would be. A button to enable the viewing of comments is there.

Additional details: [Here ](http://prntscr.com/bcslkn)is a photo.

**Comment by ParticleCore** [comment]
YT+ has a feature that allows you to either hide comments (can be shown via the button), remove them completely or show by default: https://github.com/ParticleCore/Particle/wiki/Features#comments

You probably have the option set to hide thus the button is showing in its place, change the option in the YT+ settings to "Show".

Be mindful that just because the browser can run Chrome extensions it doesn't not mean the extension is compatible with it and YT+ is only supporting Firefox and Chrome.
