### ISSUE TITLE
No Resource URI Leak addon breaks YT+

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#273]
Browser Name: Firefox Developer Edition

Browser Version: 49.0a2

Operating System: Windows 10

Software Type: Addon

Software Version: 1.2.8

Problem Description: When [No Resource URI Leak](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/) is enabled, all the icons and checkbox ticks from YT+ disappear, making it difficult to use.

Steps to reproduce: 1) Install [No Resource URI Leak](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/) 
2) Visit [YouTube](www.youtube.com) and look at the top bar (you can't see the YT+ panel icon but you can click where it was supposed to be).
3) Open YT+ panel and see that there are no ticks on the checkboxes although you can still see the blue borders which means those are ticked.

**Comment by ParticleCore** [comment]
Unfortunately I cannot do anything about this, the style sheet used by the add-on is using the sprite image that is included in it, the internal works of the browser are converting the relative path URL into paths that begin with `resource://`, which is being blocked by the add-on you mentioned. In its description it even warns users

>It may break some extensions which depend on this leak.

This is one of those cases. Hopefully with webextensions this problem can be avoided, but until then it's just something I cannot change especially because AMO does not allow the use of remote content, so using an external sprite is not a solution. Alternatively the userscript version should not be affected by that add-on since the userscript version does not use local resources.
