### ISSUE TITLE
Floating player and YouTube Ui fix script, change and add option

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#277]
As was discussed in [this thread](https://greasyfork.org/en/forum/discussion/comment/24215/#Comment_24215), there are a couple of problems when these 2 scripts are enabled.

1. The floating player dragging feature. It just drops the player as soon as it is clicked. A fix was posted in the thread, you will only need to add a couple of small changes to YouTube+.

2. The height of the floating player was partially fixed in the other script. In order to make this completely compatible, an option to set the height of the float player is needed.
So instead of automatically calculating the height by ratio, we need option to unlock auto ratio and manually set the height of the player.

I hope you take care of these issues.

**Comment by ParticleCore** [comment]
As it was previously explained I cannot extend support for other extensions, otherwise the work alone just for inter-extension compatibility would be immense. Additionally, while the solutions provided could fix the linked issue it would cause more problems, it would leave the floating player with a black gap of 35px for all the other users that are not using the linked userscript.

If the author has the time and interest he could instead focus on the css floater trigger which is added to the `documentElement` whenever the floating player is initiated and removed when the player is restored.

The class to observe is `"floater"` and it is used on the `document.documentElement` element

Lines https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L919 
and https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L924

With that any userscript can know exactly when the floating player is active and when it is not active, and apply any changes or styling accordingly.

**Comment by q1k** [comment]
I understand that adding 35px to the player is going to show a black bar to people who don't use the linked script.
That's why I proposed to add an option to manually set the height of the player.

**Comment by thegrandpow** [comment]
I second this, please add the .dragging-mode class.
Whenever I move the player (accidentally or deliberately), I have a hard time positioning it back..
Please do something.

**Comment by ParticleCore** [comment]
@thegrandpow The player can now be snapped to the edges of the browser, so if you move accidentally from where it was you can just drag it against the edges and it will stay there now.

**Comment by thegrandpow** [comment]
But I don't have it touching the edges... It's so difficult positioning it back... argh!!
