### ISSUE TITLE
Autoplay is enabled on playlist overrided by video autoplay and repeat

### ISSUE THREAD

**Issue by maingi2** [ParticleCore/Particle#290]
Browser Name: Firefox
Browser Version: 47.0.1
Operating System: Windows 7
Software Type, Software Version, Userscript Manager, Userscript Version: Don't understand

Problem Description: When Repeat is enabled or Autoplay is disabled, but the playlist's Autoplay is enabled, the video will not autoplay as the playlist controls mark, but instead will either repeat the video (if Repeat is enabled) or not autoplay the video (if Autoplay is disabled)

Steps to reproduce: Have Repeat enabled or Autoplay disabled.

Additional details: None

**Comment by ParticleCore** [comment]
This is intended behavior. It would not make sense to override those two options because of an unrelated third option. If a user wants the video to repeat then it is obvious the video will repeat once it reaches the end, it makes no sense for this to behave differently. If the user wants the video to not play automatically then it will not play automatically once it is changed, again the opposite would not make sense.

Playlist autoplay only controls whether the video should change to the next one in the playlist after the current video ends playback, nothing more. It does not control video repeat or video autoplay, unless I did not understand what you were trying to say, in that case I would appreciate if you could make it more clear.

**Comment by maingi2** [comment]
I think I understand. This is an annoyance to me because I keep those Repeat and Disable-Autoplay options on, and have to turn them off when I watch a playlist, which happens much more infrequently than regular videos. I thought when the Autoplay button was off it would use the regular settings as if the playlists were just a list of videos instead of videos that played in order, and when Autoplay was on, would play them as normal. As it is the button won't make any difference if Repeat is enabled or (video) Autoplay is disabled. Thanks.
