### ISSUE TITLE
[Critical] This addon totally breaks YouTube's new Material design

### ISSUE THREAD

**Issue by mario77777** [ParticleCore/Particle#295]
This addon totally breaks YouTube Material design, which was introduced recently and is enabled by default by now (at least for me). This addon totally breaks it, I can not use YouTube anymore. No videos are shown, YouTube doesn't react to my mouse clicks and so on. I had to uninstall this addon to watch videos again.

Do you have any plans to fix your addon?

**Comment by ParticleCore** [comment]
As I explained to your AMO review, as far as I know it is not yet possible to use the beta layout in Firefox, at least I have not been able to launch it so far so I am literally unable to test this under Firefox, however I have been testing it under Chrome and the layout is constantly changing on a daily basis making it impossible for me to make YT+ compatible with the new layout until it stabilizes. Until then the only workaround is to either delete the VISITOR_INFO1_LIVE cookie or go to the 3 vertical dots button and select "Restore classic YouTube".

Until the beta layout stabilizes I am completely unable to make YT+ compatible with it.

**Comment by mario77777** [comment]
I didn't use any beta cookies or so, just used YouTube normally and for weeks or so I randomly get this new layout, but as of today, I get this new layout more frequent, so I assumed that they switched permanently today. YouTube was totally unusable today. I see that you can't really work under these circumstances, when you don't receive the new layout in your location. Probably Europeans get it a little bit earlier than other or I don't know. I will delete my AMO review, because it's totally not your fault.

**Comment by ParticleCore** [comment]
It's not your fault either, the cookie is assigned by YouTube randomly, which appears to be more frequent now as you explained. I am currently trying to work on disabling the beta layout while using YT+ as a temporary patch, but I cannot guarantee anything since this is not the right way I would like to solve this, the best option would be to finally make it compatible which will eventually be inevitable and, hopefully, possible.

If I manage to work on the patch I will inform you here to see if it works for you as well.

**Comment by ParticleCore** [comment]
Version 1.3.7 contains a workaround for this problem that relies on having cookies enabled because there is no other way around it. If you want to try it out you can find the new version 1.3.7 which is pending review here: https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/versions/

Let me know if it works for you too.
