### ISSUE TITLE
Infinitescroll not working for watch later

### ISSUE THREAD

**Issue by cg9999** [ParticleCore/Particle#297]
Browser Name: Chromium

Browser Version: 51.0.2704.106

Operating System: Linux

Software Type: Userscript

Software Version: 1.3.8

Userscript Manager: Tampermonkey

Userscript Version: 4.0.69

Problem Description: Infinite scroll stops working on the watch later playlist page after the first automatic reloading is done. It only shows button to load more.

Steps to reproduce: Scroll down on watch later playlist page. It automatically loads more once. Then nothing

Additional details:
Changing the infiniteScroll() function like this (remove the else) fixes it for me. Not sure if this is the right thing to do, though...
```javascript
        function infiniteScroll() {
            var observer,
                loadMore = document.getElementsByClassName("load-more-button")[0];
            if (loadMore && parSets.GEN_INF_SCRL) {
                if (!loadMore.classList.contains("infiniteScroll")) {
                    loadMore.classList.add("infiniteScroll");
                    observer = new MutationObserver(infiniteScroll);
                    observer.observe(loadMore, {attributes: true});
                }
                if (!loadMore.classList.contains("scrolldetect")) {
                    loadMore.classList.add("scrolldetect");
                    loadMore.dataset.scrolldetectCallback = "load-more-auto";
                }
            }
        }
```

**Comment by ParticleCore** [comment]
YouTube frequently changes how playlists are displayed. When I tested the load more button was a different method and it was for this reason the feature was focused only on Feed pages, not playlists.

However, since playlists now share the same method and the improvement you suggested does not appear to break the feature in feed pages I can see no problem on adding it, but be aware that this might stop working at any time for the reason I mentioned in the beginning. The focus of this feature has always been and will continue to be for Feed pages.

**Comment by ParticleCore** [comment]
Version 1.3.9 should improve this feature, let me know if it works for you too.

**Comment by cg9999** [comment]
1.3.9 works great. Thanks!
