### ISSUE TITLE
Floating player + click on timestamp = unnecessary jump to top of page

### ISSUE THREAD

**Issue by jimbo1qaz** [ParticleCore/Particle#302]
Firefox 47.0.1 on Windows 10.
Youtube+ 1.4.0 as Firefox Extension.

Clicking on comment/description timestamps normally jumps to the top of the page to expose the video. This causes you to lose your position. (Backspace doesn't work because Youtube doesn't actually navigate to #mm:ss anymore.)

However, with the floating player, the video is already visible. Can you add an option to disable "jump to top of page"?

**Comment by ParticleCore** [comment]
I've never thought of that, I will investigate what can be done about it.

**Comment by jimbo1qaz** [comment]
Yes.

**Comment by ParticleCore** [comment]
I already found a simple solution for this and am about to release it, however it will be available for YT+ versions that are no longer compatible with Firefox <48, so to make use of this improvement (once it is released) you will have to either update Firefox to 48 or use the userscript version instead of the add-on (extension).

**Comment by jimbo1qaz** [comment]
I'll update to 48 as soon as I restart my browser. But do you really rely on features of Firefox 48, which was released literally days ago?

**Comment by ParticleCore** [comment]
They are Webextension APIs that were not available in previous versions, delaying the migration of the Firefox Jetpack type add-on to Webextension type add-on. I had already tested them as soon as they were made available in Nightly 48 and they proved to be very stable since March until now. So, techincaly, these features were released about 6 months ago.

**Comment by ParticleCore** [comment]
I've added the change for this situation in version 1.4.4, however if you are using the AMO store version it will not update automatically until the reviewers have time to review and approve the add-on. If you don't want to wait you can download it directly from the version history list: https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/versions/

Or use the version hosted here on GitHub: https://github.com/ParticleCore/Particle/wiki/Download

Once you click on a video timestamp while the player is floating it should no longer scroll the page to the top, let me know if it works for you as well once you have a chance to test it.

**Comment by jimbo1qaz** [comment]
woops "Due to time and framework limitations I am unable to accept any more feature requests."?

**Comment by ParticleCore** [comment]
The add-on hosted on GitHub is signed so it can be installed on any Firefox channel, including the one you have.

Regarding the requests, people can always make the requests, but these will be archived until I have some spare time to see if I am interested in adding them, if they are worth adding and so on.

**Comment by jimbo1qaz** [comment]
I tried installing from Github, it downloaded the XPI instead.

Also, I don't see any checkbox for clicking on timestamps. Did you combine it with the existing floating player checkbox?

**Comment by ParticleCore** [comment]
To install the downloaded XPI go to the add-ons tab (or enter `about:addons` in your url bar), click on the cogwheel button next to the search field and select "Install add-on from file".

There are no checkboxes since this was not a feature addition but a feature enhancement, the setting is active by default as long as the floating player is active.

**Comment by jimbo1qaz** [comment]
I actually somewhat regret this feature request... Now when I click a link, I can't see the video clearly. Can I disable the feature? Can you add a "jump to top" link to the timestamps? Can you allow "history back" to jump to previous position? Would "go to top anchor" work? But if you click one comment, scroll down, and click another, maybe the browser wouldn't recognize the second comment as a history entry (because the anchor's the same?).
