### ISSUE TITLE
Remove bar below player?

### ISSUE THREAD

**Issue by DAOWAce** [ParticleCore/Particle#31]
Just switched over from YouTube Center as I was sick of it, well, not working.

Initial setup was fairly quick, but had to troubleshoot the player size issue; wouldn't actually save its size unless I unchecked the memory option.

Anyway, I don't see an option to be able to enable/disable the bar below the player.  It can be minimized, but unfortunately the icon is white and clashes with my dark Youtube theme (https://userstyles.org/styles/62289/black-youtube-by-panos).

Could we get an option to remove this or even have a light/dark selection?

Hope to see more YTC features (static header, quality/ratings on thumbnails, and being able to change the video render mode was incredibly useful in the Flash player; no more direct mode anymore so there's a big pause on fullscreen toggle), but otherwise it's nice to actually be using something that works well again and doesn't cause a massive delay in page load and other issues.

**Comment by ParticleCore** [comment]
The white background on the advanced options has to exist to work correctly over the title, but I will try to see if I can find a different way of achieving the same result in the future.

About the other extra options, I don't intend on adding many more because I want to keep this small and light. This doesn't mean that I won't add more features, it will only be those that I find to be useful.

Regarding the issue you mentioned with the player size, could you be more specific?

**Comment by ParticleCore** [comment]
Are you using the flash player with YT+? Because I do not provide support for it: https://github.com/ParticleCore/Particle/wiki

**Comment by DAOWAce** [comment]
So, an enable/disable option for the bar then?

When the "memorize player mode" is checked, it doesn't memorize it; it goes back to the default tiny size.

Yes, I am (commented in my first post about not being able to change the flash render mode anymore).  I'm forced to use flash as I use Pale Moon, which did not implement MSE, so it cannot play HTML5 videos properly.

**Comment by ParticleCore** [comment]
Sorry, but like I said I do not provide support for the flash player, this is why the memorize player mode is not working correctly for you since it depends on specific functions that only the HTML5 player provides and I'm also only supporting Firefox and Chrome.

Adding an option to disable/enable the advanced controls is not something I'd want to do, but I will try to find a different way of placing the advanced controls without a white background or I might even finish working on the night mode for YT+ if I see that it will be worth the work load and trouble, although the former might take more time to complete.

**Comment by ParticleCore** [comment]
@DAOWAce In version 0.2.5 I have improved the advanced controls' background so that it uses whichever color its container has so it shouldn't clash now. Update whenever possible and let me know if it works correctly for you.

**Comment by DAOWAce** [comment]
Oh cool, it's black now.

..and unfortunately it's completely black to the point where it's invisible. I can still mouseover it and select things, but just can't see it.

http://i.imgur.com/SD8BO7t.png

The grey color changes too?  I think if that stayed grey it would be perfectly fine.

To clarify here was the old version: http://i.imgur.com/FFSyoCK.png   (when minimized it would still have a white background around the button too.)

**Comment by ParticleCore** [comment]
It wasn't gray before, it was always black with different opacity. Now each user is completely free to manipulate the YT+ style interface, otherwise if I change the buttons to a different color now it will cause issues with other users that already set their style according to the previous colors.

In your case, all you have to do is add this to the current userstyle right after the YouTube rule found at the start of the style:

````css
@-moz-document domain(youtube.com)
{

#console-button, #player-console > div{
    filter: invert();         /*This one is for Firefox, should be the same with Pale Moon*/
    -webkit-filter: invert(); /*This one is for Chrome, just in case it is needed*/
}
````

And it will look like this:

![ss](https://cloud.githubusercontent.com/assets/9222661/8343825/41f3f79e-1ac9-11e5-8f53-0065e990506e.png)

**Comment by DAOWAce** [comment]
Very late bump.. but this actually just never worked for me.  Dealt with it being invisible all this time! Even onward to Chrome.

Attempted to look into it again and it looks like there's been a lot of changes to things, so the code snippet is probably invalid, and upon testing now it still doesn't seem to do anything.

Any chance you can look into this again?

**Comment by q1k** [comment]
```
div#advanced-options svg {
    filter: invert();
}
```
