### ISSUE TITLE
fullscreen have some problem

### ISSUE THREAD

**Issue by Jason4774** [ParticleCore/Particle#311]
today,fullscreen have some problem,please fix it .it't normal yesterday

**Comment by mauriciocolli** [comment]
I think you meant the Fullbrowser Mode...
Where should be black, is transparent:
![bug](https://cloud.githubusercontent.com/assets/13389907/17685637/445d3b50-633c-11e6-871b-7824772bbd07.PNG)

I found that in Firefox when you enter the Fullbrowser mode, you can scroll the page with the `Space` (if the option "Shortcuts always active" is not enable, because the focus stay in the page itself), `PgUp` and `PgDown`, or even `Ctrl + Home or End`, breaking the feature if you have the "Player always visible" enabled, I couldn't replicate in Chrome.

Other thing that I notice is when the window is small, the player go to the "Floater form", interfering with the Fullbrowser mode, because the searchbar appears on top of the video when it is enabled:
![full](https://cloud.githubusercontent.com/assets/13389907/17686385/6f51069c-6342-11e6-84e6-cb6d6495ac44.PNG)

**Comment by Jason4774** [comment]
Thanks for your reply ,
YES,I mean the Fullbrowser Mode,so can you fix it ? the Fullbrowser Mode is very nice .
google chrome
![image](https://cloud.githubusercontent.com/assets/19594338/17686689/38fe7bc4-63a1-11e6-9902-f9b2b717f581.png)
Firefox
![image](https://cloud.githubusercontent.com/assets/19594338/17686702/49496e58-63a1-11e6-8e01-66542484131e.png)
Thanks again.

**Comment by ParticleCore** [comment]
It is a recent YouTube change, for some reason they decided to remove the video player black background. Will push the fix with the next update.

**Comment by Jason4774** [comment]
great ,and thank you.

**Comment by ParticleCore** [comment]
This should be fixed in version 1.4.8, let me know if it works well for you too.
For userscript users please press Ctrl + F5 inside YouTube to load the updated CSS file.

**Comment by Jason4774** [comment]
YES, it works .thank you
