### ISSUE TITLE
Huge Click Radius 

### ISSUE THREAD

**Issue by SingularityRS** [ParticleCore/Particle#315]
I've noticed this after constantly opening random videos when I know I haven't hovered my cursor over the video's title.

Here: http://i.imgur.com/mIdMc0Y.png

As you can see, the click radius is huge (cursor turned to a hand to indicate it's click-able) on this page for some reason. This results in me misclicking on videos. 

This appears to be a chrome-specific issue. It only appears on this specific page (when searching for videos). 

Firefox does not have this problem. The hand cursor only appears when you hover over the title of a video as it should.

**Comment by ParticleCore** [comment]
Glad to hear you worked it out, if it happens again and you find a way to replicate with YT+ enabled please let me know.

**Comment by q1k** [comment]
For me this happens all the time (on firefox), and whenever I right click or even do a middle click to scroll (or to open in a new tab) it just opens the video in the same tab. It's so annoying...

But this has been happening for a long time now.
It's probably because youtube made the links tied with the div, (btw, I don't have this new material layout they keep talking about, I've seen it and I don't like it.)

**Comment by ParticleCore** [comment]
@q1k Make sure this is not something caused by YT+ by disabling it, it could be a YouTube change for touchscreen interface they have been/were testing (larger click areas = easier to use with fingers).

**Comment by ParticleCore** [comment]
Well, I just disabled YT+ in Firefox and Chrome, searched for videos and all of them are fully clickable so this is a YouTube change. Not only in search results but in any page where videos are listed in list layout (subscriptions, for example). So this is not caused by YT+, in fact I think I included a change to reduce the click area for this exact reason.

**Comment by q1k** [comment]
Well I don't need the blacklist and I don't use pop-out, so can you disable this large clickable area anyway, maybe through an option?

**Comment by ParticleCore** [comment]
You can either of them enabled without having to use it and you will get the behavior you want. I am not interested in making this a dedicated feature. I am sorry but this was a way to make those features work, not the other way around, it might even stop doing that soon with the upcoming major YouTube layout change.

**Comment by q1k** [comment]
OK, I guess I'll be blacklisting accidentally. Thanks for that  :disappointed:

**Comment by ParticleCore** [comment]
It does not have to be blacklist, I clearly said "either of them". If you are worried you might blacklist channels by mistake then enable pop-out mode instead and your only worry will be opening videos on a dedicated window by mistake.

**Comment by q1k** [comment]
I hid them with stylish :grinning: 

the css for anyone else that might need it:

```
.yt-lockup-dismissable .yt-uix-menu-container.yt-lockup-action-menu, /* remove YT hide button on the right side */
.blacklist.ytplus_sprite, /* YT+ blacklist */
.popoutmode.ytplus_sprite /* popout */ {
  display: none !important;
}
```
