### ISSUE TITLE
Updating progress bar and time

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#318]
Is it possible by any chance to make the progress bar and the time update even when the control bar is hidden?

**Comment by ParticleCore** [comment]
There are ways, the simplest one I saw was a stylish someone made for video controls always visible + a bit of code sending "mouseover" events every couple of seconds. The new player controls are wired to the mouse over and movement status, when the mouse isn't moving everything else doesn't need to work since it is hidden.

**Comment by q1k** [comment]
But sending mouseover event will cause the title bar to become visible.

Is it possible to completely ignore the no-update progressbar that youtube adds by default?

**Comment by ParticleCore** [comment]
Just as you send the events you can also keep the controls hidden using javascript. Other than that you will have to find a way to override the YouTube player source code responsible for that specific behavior.
I am sorry but I would appreciate if the issue tracker is used for things related to YT+, if you want tutorials for building userscripts or anything else unrelated to YT+ there are more appropriate places.
