### ISSUE TITLE
Option to color rating bar & download ability ?

### ISSUE THREAD

**Issue by Betsy25** [ParticleCore/Particle#32]
Coming from YouTubeCenter, this is a fine (& very resource friendly) extension.
Those 2 things I really miss : 
* an option to give your own colors to the rating bar & up-down thumbs.
* A download button to save clips in a desired resolution.

Only a request, If not interested, close issue at will :+1:

**Comment by SW1FT** [comment]
That would be awesome and it would attract a lot more people to use YT+. YT+ is very light in terms of resource usage and could use some features that people miss from YTC without compromising its lightness.

**Comment by ParticleCore** [comment]
Sorry, but coloring the feedback area is not a feature that I find to be useful.

Regarding the Download option, it would grant me a ban from the Chrome webstore since it is against their TOS and would bring me way more problems than not; users complaining that they can only download up to 720p, higher qualities have no audio, etc. It's just not worth it, the users are way better off using a third party service for that, such as clipconverter.cc which allows the download of any quality with both video and audio in one file.
