### ISSUE TITLE
Scrolling down auto maximises the videos?

### ISSUE THREAD

**Issue by pgbearensen** [ParticleCore/Particle#324]
Browser Name: Firefox

Browser Version: 48.0.2

Operating System: Windows 10

Software Type: extension

Software Version: 1.5.0

Userscript Manager: n/a

Userscript Version: n/a

Problem Description: Firstly apologies if i've missed something related to this but i have searched the issues and settings. The problem is that every time i scroll down the video maximises and unless i scroll up repeatedly, it will not minimise even upon clicking the full screen icon.

Steps to reproduce: Go to a youtube video and scroll down and have the video maximise instantly.

Example: http://puu.sh/qXtzy/57924bbea8.png

**Comment by ParticleCore** [comment]
Please pay attention to the troubleshooting guide that was linked in here so that users would read before posting a new issue, it specifically says:

- Make sure you are not using the Flash player. Right click on your player and see if it lists "About Adobe Flash Player <Number>..."
 - The extension works with the Flash player, but many features do not simply because they are not compatible or possible to work with the limitations imposed by this player type. The only solutions are to use the HTML5 player by visiting this link and activating it: https://www.youtube.com/html5 or to use the Flash player without using the incompatible features


https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting


Your screenshot shows the YouTube flash player, which is why you are having the problem you reported. Change the player to HTML5 and the problem will be corrected.
