### ISSUE TITLE
Auto Pause tabs while videos keep buffering

### ISSUE THREAD

**Issue by svefn** [ParticleCore/Particle#328]
Hi, just found this great addon and first time using it.

One thing I miss though is the ability to pause by default all youtube video tabs, while they buffer in the background.

I tried disabling Auto Play and it disables buffering altogether too unless clicking play manually. 

I'm using this set to Auto Play + Youtube Control Center to Auto Pause, so that tabs keep buffering. Not ideal though due to possible conflicts.

Just a suggestion.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by ParticleCore** [comment]
You can achieve this without the need of any extension. In Firefox, for example, you can defer media playback until you switch to the opened tab: 

 - Open `about:config`

 - Search for `media.autoplay.enabled`

 - Change its value to `false`

Now every time you open a video in a new tab (and you haven't switched to it yet) the videos will never play until you switch to that tab, but they will buffer.

**Comment by svefn** [comment]
using media.autoplay.enabled breaks the youtube playback buttons, where it dos not play when clicked. have to click it a few more times, or use the seek bar to play the video.

**Comment by ParticleCore** [comment]
It doesn't play when clicking the video area, but it starts playing when you click the play/pause button twice.

I simply suggested that method because it allows you to have what you want without having to install any other add-on, you don't have to use it if you don't want to.

**Comment by svefn** [comment]
it also autoplays the video when you switch tabs, which is different from not auto playing anything.

guess we'll just be stuck with either options for now.

**Comment by ParticleCore** [comment]
>it also autoplays the video when you switch tabs, which is different from not auto playing anything.

That is something that should definitely not be happening since it defeats the whole purpose of that setting. I just tested it and no YouTube videos play automatically while that setting is disabled, even after switching tabs like you mentioned. Make sure you don't have other settings conflicting with `media.autoplay.enabled` or an add-on overwriting it. If it still keeps doing it try troubleshooting it in safe mode https://support.mozilla.org/kb/troubleshoot-and-diagnose-firefox-problems#w_3-restart-firefox-in-safe-mode
