### ISSUE TITLE
Hide watched videos

### ISSUE THREAD

**Issue by dmnrmr** [ParticleCore/Particle#33]
Could you implement a feature to hide watched videos?

I am currently using YTC + Subscription grid to achieve this. I would like to use your addon, but am missing this important feature.

![1](https://cloud.githubusercontent.com/assets/7805266/8382021/5efda8ce-1c38-11e5-92c9-5c49b4684653.jpg)
![2](https://cloud.githubusercontent.com/assets/7805266/8382022/5f00b460-1c38-11e5-8c33-31da223d78d2.jpg)

**Comment by ParticleCore** [comment]
As it is now it requires the software to save every single watched video which will occupy disk space and slow the browser performance. For this feature to work well YouTube would have to fix their watched labeling system. Until that happens I will not add this feature since it would have negative impact, YT+ is focused on being light and fast (as far as my limited knowledge allows me...).
