### ISSUE TITLE
Subscription playlist -  increase the "max. 20" value

### ISSUE THREAD

**Issue by digitalattorney** [ParticleCore/Particle#333]
_"Enable subscription playlist - This feature will place a new button in your subscription feed, clicking on it will load the most recent videos in your subscription feed into a playlist with up to a maximum of 20 videos."_

Is there any way at all to increase this "max. 20" value?

If not, may I please request that you make this a user controlled variable? With the number of subscriptions I have, this number is far too low for me to get my latest subscriptions over the last 24 hours to play.

**Comment by ParticleCore** [comment]
There is no way of increasing the maximum value. The feature makes use of YouTube's temporary playlists (to prevent playlist spam overall) and it is limited to 20 videos. This is something imposed by YouTube itself.

YT+ actually fetches all videos visible in your subscription page and sends them to YouTube in order to generate the temporary playlist in case they change the limit.

Until they change this limit, it will remain limited at 20 videos max.

**Comment by digitalattorney** [comment]
Great feedback. Thank you for your reply.

**Comment by mauriciocolli** [comment]
Just a little issue, when you load more videos, at least once, the url get too many videos ids, and exceeds the 2000 characters limit, giving a `400 bad request`, just adding the 20 videos limit (or as you said, in case they change, a little higher) should fix:

`i = subPlaylist.video_list.length > 20 ? 20 : subPlaylist.video_list.length;`  https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L1469

**Comment by ParticleCore** [comment]
@mauriciocolli Never thought there was such limitation. Also I can't use your fix because the array containing the recent subscriptions is in reverse, so it would cause the playlist to load the last 20 videos instead of the recent 20 videos. I will push a fix for this on the next update.
Still, the characters include video titles, so if there are videos with titles that are too long, even 20 could result in bad request. I will have to study this further.
