### ISSUE TITLE
DASH

### ISSUE THREAD

**Issue by ruhaizad** [ParticleCore/Particle#341]
heloo. i do really love your work man. but why did u remove DASH? i don't have the internet speed to load the video. so the DASH really really help me. i hope u can make this feature work again. thank you guys for your hard work.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Particle/releases/tag/1.5.0

**Comment by HibGut** [comment]
@ParticleCore  Found this looking for why DASH disabling had been deprecated. Took me a while to find. Would be nice if you could link the deprecation note on the Disable DASH playback entry on your Features wiki page.

That said, I also miss the feature. I'm not an expert and don't know all the technical details, but I understand DASH is what prevented videos from buffering completely. But that's what I want - buffer completely to the end, so that I could take my laptop offline and still watch an hour-long video in the open browser window. Limitations to 30 fps and 720p don't bother me. 

You say I could disable media.mediasource.enabled in Firefox. I searched a bit to understand what exactly mediasource is and how it relates to what I want, but it's still not very clear. https://html5test.com/ for example still shows Dynamic Adaptive Streaming / MPEG-DASH (isn't that DASH?) as off even when Media Source extensions is on. How are they related? Media Source extensions seems to have a lot more functions than DASH, what else would I lose if I disable it?

Would be nice if you could elaborate a bit on your Feature removal page. BTW, I'm on Firefox 53 with YTPlus 1.8.6. Thanks!
