### ISSUE TITLE
"Fit to Page in Theater mode" suddenly stopped working.

### ISSUE THREAD

**Issue by Rynslet** [ParticleCore/Particle#362]
Browser Name: Firefox
Browser Version: 49.0.1
Operating System: Windows 7
Software Type: YouTube +
Software Version: 1.5.8
Userscript Manager: Greasemonkey
Userscript Version: 3.9
Problem Description: YouTube+ Theater mode no longer fits to window.
Steps to reproduce: Open a YouTube video.
Additional details: I was watching a playlist, and suddenly between videos, it stopped stretching to fit the window. Maybe it updated during that first video? I'm not sure. It only happened maybe a half an hour ago.

**Comment by Eisys** [comment]
I had this happen as well. Update to the newest version. 1.5.9 is out. That fixed it for me!

**Comment by Rynslet** [comment]
Took a while to figure out how to force greasemonkey to update the script, but updating it worked. Ty Eisys.

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Particle/issues/360

This is just to keep the issues organized, glad to hear the fix works for you as well.

**Comment by Eisys** [comment]
Out of curiosity, how did an update to a newer version affect an older version like this?

**Comment by ParticleCore** [comment]
This wasn't caused by YT+ changes but by YouTube website changes. They changed how their player behaves for "mobile" layout (small windows) which in turn was incompatible with the method I was using before (purely CSS). I fixed it once, they changed it again so I had to move to javascript to control the player resize method and ditch CSS. It should be more stable now, but I worry it might be heavy on slower computers when resizing the window.
