### ISSUE TITLE
Reversing a YouTube playlist will only persist for two videos

### ISSUE THREAD

**Issue by PartlyAwesome** [ParticleCore/Particle#367]
Browser Name: Chrome
Browser Version: 53.0.2785.143 m
Operating System: Windows 7 x64
Software Type: Extension
Software Version: 1.6.0

Problem Description: The reverse playlist function will only persist (stay on) for the video of when it is activated and the first video afterwards.

Steps to reproduce: As far as I can tell, it looks like this issue can be reproduced on my machine in 2 ways.

Activate reverse playlist function.
Click YouTube's next button on the video player twice.

Video: https://a.pomf.cat/jpbsft.mp4

Activate reverse playlist function.
Watch to the end of the video twice. (shown here by skipping to the end, however this does happen when watching all the way to the end)

Video: https://a.pomf.cat/nnhemz.mp4

Both of these videos were recorded on a new Chrome user with only YouTube Plus installed.

Additional details: This doesn't happen on my Windows 10 machine, which has all of the same extensions that this machine had when I first found the issue. Don't know if that could help or not.

I'm happy to provide extra details if some are missing, I'm not sure how I can be more detailed.

**Comment by ParticleCore** [comment]
I am still unable to replicate this issue on the same configuration (Win7x64 Chrome 53).

Did you follow the troubleshooting guide like it was requested, especially the step where you try to replicate this problem on a new Chrome profile with just YT+ installed?

**Comment by ParticleCore** [comment]
I completely missed your last info about the new Chrome profile with just YT+ installed. Can you share your YT+ settings? No need to include your blacklist if there is any.

**Comment by PartlyAwesome** [comment]
`{
  "BLK_ON": true,
  "GEN_BLUE_GLOW": true,
  "GEN_BTTR_NTF": true,
  "GEN_INF_SCRL": true,
  "GEN_PPOT_ON": true,
  "GEN_SUB_LIST": true,
  "VID_DESC_SHRT": true,
  "VID_DFLT_QLTY": "auto",
  "VID_END_SHRE": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_HTML5": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_POST_TIME": true,
  "VID_PPOT_SZ": 533,
  "VID_VID_CNT": true,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "firstTime": false,
  "floaterX": 2000,
  "floaterY": 2000,
  "plApl": true,
  "plRev": "ULuLOg3r7PNK0",
  "volLev": 50
}`

**Comment by ParticleCore** [comment]
Can't replicate with the same settings so we can rule out YT+ features conflicting with each other. Does this happen on any playlist or just private playlists?

Try to see if the problem happens with this one: https://www.youtube.com/watch?v=34Na4j8AVgA&list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj

**Comment by PartlyAwesome** [comment]
It doesn't seem to happen on that playlist
https://a.pomf.cat/gwgzai.mp4
https://a.pomf.cat/mjvvgw.mp4

This was the playlist I was using in my previous videos: https://www.youtube.com/watch?v=a9fUV7uA2_s&index=19&list=ULlbgYAyzaT8w

The interesting thing about this playlist is that it was accessed by going on a video and adding `&list=UL` as the channel doesn't have a playlist of uploads. Just for confirmation, I am not experiencing the issue on every type of upload playlist, for example the playlists which you can access by clicking this button: http://i.imgur.com/lnJogmE.png do not have the problem of the playlists provided by `&list=UL`.

**Comment by ParticleCore** [comment]
I was finally able to replicate this, I had to use that exact playlist you showed on your second video. I will investigate to see what is causing this problem now. Thank you for the feedback.

**Comment by ParticleCore** [comment]
I see now, for some very odd reason the place where the list id is stored (which YT+ retrieves to memorize which playlist has the reverse option active) is giving a different id than the actual playlist id in use.

So, in your example, the actual playlist id is `ULacCtVq4QW2Y` from `https://www.youtube.com/watch?v=wanYwHSKng4&list=ULacCtVq4QW2Y`, but the ID YouTube is giving to YT+ is `ULwanYwHSKng4`.

And the strange thing is that both playlist IDs are valid and work for the same playlist. Even more strange is that there is a third different playlist ID inside that playlist, which also works for the same playlist list: `UL5v63cWxFw18`.

And as if that wasn't enough, the actual playlist itself can never be accessed directly, which means that neither of these links work:

https://www.youtube.com/playlist?list=UL5v63cWxFw18

https://www.youtube.com/playlist?list=ULwanYwHSKng4

https://www.youtube.com/playlist?list=ULacCtVq4QW2Y

But they work if they are directed to a video from that playlist:

https://www.youtube.com/watch?v=5v63cWxFw18&list=UL5v63cWxFw18

https://www.youtube.com/watch?v=5v63cWxFw18&list=ULwanYwHSKng4

https://www.youtube.com/watch?v=5v63cWxFw18&list=ULacCtVq4QW2Y

Since in cases like this there is no way to memorize which playlist you enabled the reverse mode for (their ids vary) I can see no other solution besides enabling the feature permanently (when the user activates it) and it will only disable when the user turns it off.

It is a bizarre situation and I am sorry that the solution will have to be that way, but I can see no other way of fixing this.

**Comment by PartlyAwesome** [comment]
That's super weird, why would that even be like that? Thanks for looking into it though.

**Comment by PartlyAwesome** [comment]
Looks like it works to me.

https://a.pomf.cat/ivnixh.mp4
https://a.pomf.cat/whfqrh.mp4

Thanks for the fix!
