### ISSUE TITLE
Keep fullbrowser mode active

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Particle#369]
In fullbrowser mode while playing a video, when I click on **Theater mode** button to close the video player, it closes Fullbrowser mode and also **disables** the fullbrowser button underneath the player, so it needs to enabled again on next video. Is there a way to keep Fullbrowser always enabled even after exiting the video player like that?

**Comment by ParticleCore** [comment]
The behavior for this feature had to be designed like this for one reason and will remain like this. When you exit theater mode **and** click the fullbrowser mode button again, there is no way of knowing whether you want to turn the feature off or enter fullbrowser mode again. The way it currently is implemented avoids this problem because every time you want to enter fullbrowser again during playback you can do it because it has been  turned off when you exited that mode.
