### ISSUE TITLE
Scrub/scroll bar doesn't work when casting

### ISSUE THREAD

**Issue by Jambe** [ParticleCore/Particle#372]
Chrome 54.x on Windows 10.

This may be related to #368  but I'm not sure.

To reproduce: cast to any compatible device and notice that progress/played indicator no longer appears (red bar ending with red dot at current time), and hovering over the bar doesn't produce a preview of the video or a time indicator.

**Comment by ParticleCore** [comment]
I don't have any casting devices to test this, so I cannot say whether I will be able to fix it or not since I have no way of seeing what is happening so that I can try to fix it. For the moment I can't fix this intentionally, hopefully any future changes might correct this as consequence, such as fixing the issue you mentioned also fixing the issue you are experiencing.

**Comment by q1k** [comment]
It doesn't happen to me.
Share your settings here.
Or it might be caused by some other addon/script you are using.

**Comment by Jambe** [comment]
@q1k: just reinstalled and it wasn't happening with default setting, so I went through each of the options I wanted (reloading individually after each settings save) and discovered that unchecking the "Autoplay Videos" option in the Video section of the menu reliably reproduces the problem.

**Comment by ParticleCore** [comment]
So that means it is very likely linked to the new method I had to use for autoplay off so that I could fix this issue: https://github.com/ParticleCore/Particle/issues/350

Which means that if I am able to fix the issue you linked, which requires a different autoplay control method again, it should fix your issue as well, so I'll ask you to try the new version with the fix to see if it fixes your problem as well.

**Comment by ParticleCore** [comment]
@Jambe I have released version 1.6.3 which fixes the issue you linked, which I hope is related to yours. Let me know if it works correctly now.

**Comment by Jambe** [comment]
@ParticleCore it works correctly now.
