### ISSUE TITLE
Mini-player persists after leaving video page

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#39]
When I leave the video page and go back to the subscription feed (for example), the mini-player stays there, even if there's no video playing. This could be a feature, you could have a mini-player playing the video and browse YouTube, but at the time this is a bug.

Here is a screenshot:
![miniplayer bug](https://cloud.githubusercontent.com/assets/6627739/8476359/76b2cab0-20b8-11e5-88cd-6562fa557176.png)

EDIT: Actually, this only happened to me once, and I couldn't replicate it again... Also, might be another bug with SPF?

**Comment by ParticleCore** [comment]
My initial intention was for a feature that does just that, the player would remain visible and working while the user navigated to different pages (just like with the Android YouTube player), but due to too many variables and conflicts I decided to no go forward with it for the time being. This shouldn't be happening, I will try to see in which cases the player might be lingering when exiting the video page.

**Comment by ParticleCore** [comment]
I was unable to replicate the issue, however I implemented a few modifications which will hopefully prevent this from happening again.
