### ISSUE TITLE
"Watched" tag and Greyout No Longer Working

### ISSUE THREAD

**Issue by RadioActiveLobster** [ParticleCore/Particle#401]
Videos are no longer showing the "Watched" tag on them or appearing grayed out anymore.

Pretty sure this was something YouTube updated but would be nice to have the option to turn that back on.

**Comment by ParticleCore** [comment]
It is a new YouTube feature, it is being replaced with a watched time red line:

https://www.reddit.com/r/youtube/comments/58q7qf/woke_up_to_this_red_line_underneath_videos/

https://www.reddit.com/r/youtube/comments/550xmf/does_anyone_know_what_these_red_lines_mean/

As for the request, please read the [readme](https://github.com/ParticleCore/Particle/blob/master/README.md):

> Due to time and framework limitations I am unable to accept any more feature requests.

**Comment by Eisys** [comment]
Oh god no.. I hope this change never gets implemented because [I need the 'watched' tag](http://i.imgur.com/Ug09Arx.png)

@ParticleCore any idea how 'sure' something like this is? Meaning how likely is it that it will indeed replace the watched tag?
And if it will, will there be a way to somehow recreate an overlay like I have with Sylish or sth else? Cus it will be a pain in the A looking through alot of videos for ones I haven't yet watched.

**Comment by ParticleCore** [comment]
@Eisys Not sure, but it is very likely since it is something coming from their Android app: www.androidpolice.com/2016/05/11/youtube-is-testing-a-new-progress-bar-showing-how-far-you-were-in-a-video/

Should be easily reverted since the thumbnail must contain some sort of identifier to show the red line or not, so using that in a simple userstyle should be enough to restore the "WATCHED" behavior.

**Comment by RadioActiveLobster** [comment]
Apparently it'll still show the "Watched" tag but only if you actually watch the video to the end (or somewhere near it, my guess would be 90%). It seems a bit finicky at the moment.

**Comment by q1k** [comment]
This is the CSS needed to get the white overlay and the WATCHED tag as well
```
.contains-percent-duration-watched .video-thumb::after {
    background: rgba(255, 255, 255, 0.5) none repeat scroll 0 0 !important;
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    display: block;
    height: 100%;
    width: 100%;
  }
  .contains-percent-duration-watched::before {
    background: black;/*rgba(255, 255, 255, 0.5) !important;*/
    content: "WATCHED";
    color: white;
    font-weight: 500;
    box-sizing: border-box;
    width: auto;
    height: 18px;
    line-height: 15px;
    padding: 2px 4px;
    display: inline;
    position: absolute;
    left: 1px;
    top: 1px;
    z-index: 10000;
    opacity: 0.85;
    pointer-events: none;
  }
```

If you want to get rid of the red line on the bottom, add this too:
```
  .resume-playback-background, .resume-playback-progress-bar {
    display: none;
  }
```

**Comment by q1k** [comment]
For those of you who can't be bothered to copy the code,
I have posted it on [userstyles](https://userstyles.org/styles/135529).
