### ISSUE TITLE
Remove excess part of links

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#412]
So on the watched videos the links are different from the normal format.
There is the time appended to it (&t=0s).
Now this interferes with the visited behavior, so I ask of you to remove that part of the link.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by Piter432** [comment]
@ParticleCore: So maybe you will “hire” additional code/programmer to your script/extension?

**Comment by ParticleCore** [comment]
@Piter432  I think I already explained a few times that this extension was not an extension focused on the users, not all feature requests will be implemented unless I find them interesting and, even then, if I have the possibility to include them, if they are feasible at all and if the extension isn't already getting too bloated. Especially with the store restrictions in Firefox, letting anyone contribute to the code source would force me to inspect every bit of code added, forcing me to spend even more time that I do not have to spare, and even more explaining the code design, and how it must be followed, otherwise it will end up a complete mess and result in being rejected from the Firefox store, as it happened with a few other add-ons.

Plenty of users assume that this is a YouTube Center replacement, where everyone can request new features to be included, but it is not. This is a hobby of mine that I developed for myself and chose to share publicly after multiple requests. Anything to be added, removed or changed is up to me, but this does not forbid anyone from forking the project and make their own modifications themselves if they really want something that I am not willing to add or don't have the time for it.
