### ISSUE TITLE
Conflict with Floating for YouTube™ addon

### ISSUE THREAD

**Issue by brodycas3** [ParticleCore/Particle#419]
This addon conflicts with the addon. *or does this addon conflict with it?*

Here is a gif of the problem,
https://u.nya.is/wcqqlq.gif

As you can see the buttons overlap each other.

**Comment by Piter432** [comment]
The most simple way (I think) to fix this is to give option in “Floating for YouTube™” (if this feature isn't there) and YouTube+ to change the position of these white elements on thumbnail (“Watch later” button, “Add to blacklist” button, etc.). I mean about the similar way in YouTube Center of configuring YouTube's thumbnails, if you know what I mean 😛

**Comment by mauriciocolli** [comment]
A workaround for this problem, is disabling the "BlackList" feature.

And better yet, if you click on the icon on the bottom left, it opens the video in "Pop Out mode".
https://github.com/ParticleCore/Particle/wiki/Features#enable-pop-out-mode

So having this "Floating for YouTube™" is a little redundant, as it is essentially the same.

**Comment by q1k** [comment]
You can use Stylish and move one of those buttons

**Comment by ParticleCore** [comment]
Like @mauriciocolli  suggested, YT+ already has a feature which does the same as the other extension, with the only difference being the inability to set always on top unless using a macro: https://github.com/ParticleCore/Particle/wiki/Features#popout_on

The cross has been placed on the top right because it is an intuitive position, similar to Windows window buttons, so that will not be changed in this version. However, I am planning on allowing what @Piter432 suggested for the current alpha version that is in development for the YouTube Material layout.
