### ISSUE TITLE
Frame-By-Frame with the , and . keys no longer works.

### ISSUE THREAD

**Issue by Artix3000** [ParticleCore/Particle#422]
Browser Name: Firefox

Browser Version: 50.1.0

Operating System: Windows 10

Software Type: Add-On

Software Version: 1.7.3

Problem Description: Frame-by-Frame with the , and . keys no longer works, it is now 1 second at a time. I remember earlier versions of this plugin allowed frame by frame through the add-on, would be nice to set those functions to other keys until YouTube reenables frame by frame.

Steps to reproduce: Pause any youtube video and press the , or . keys. (I tested on this video: https://www.youtube.com/watch?v=tendhUkomS0 )

Additional details: A problem on YouTube's end, though a simple solution would be to reimplement this addon's frame by frame features.

**Comment by ParticleCore** [comment]
It is still working, tested on https://www.youtube.com/watch?v=jVSy_5M3NTc

However, in the video chain of the one in your example, I discovered no video whatsoever had frame by frame working for videos that were published before October 2014, meaning that while the video above has the frame by frame working, the one that YouTuber uploader just the day before that does not have the frame by frame working correctly: https://www.youtube.com/watch?v=_iRj5bfEnYQ

And all the videos I tested before that time show that problem, other channels show the same behavior:

https://www.youtube.com/watch?v=S7_I0SmC1Nc
https://www.youtube.com/watch?v=81Dj3hUmeLw

Strangely, there are some that are old as well but don't show this problem, as long as they have their FPS expressed in their info (right click video, select "Show stats for nerds" and see fps after @ in resolution):

This one has 15fps expressed and frame by frame works correctly https://www.youtube.com/watch?v=zYB-B9goado
This one is the same https://www.youtube.com/watch?v=tJTc5SnlrGU
This one has 30fps expressed and frame by frame works correctly https://www.youtube.com/watch?v=UXP5shvE9Jw

So the problem appears to be a combination of videos older than October 1st 2014 and not having the FPS in their video info. Strangest part is, it should always be default to 30fps if no fps info is present, at least that is what I did and what their source code appeared to do last time I checked here https://github.com/ParticleCore/Particle/issues/353#issuecomment-252492082

In that last code block it can clearly be seen the fps falling back to 30 when no fps is available
````javascript
(c.fps || 30)
````

Which is still the case to this date, with the current code block in my most recent YouTube source code

````javascript
    d4 = function(a, b) {
        if (g.Q(g.dm(a.g), 4)) {
            var c = a.g.getVideoData().A;
            c && (c = c.video) && a.g.he(b / (c.fps || 30))
        }
    }
````

https://s.ytimg.com/yts/jsbin/player-en_US-vfla6wgHS/base.js

Problem is, for the old videos with no FPS info, the code is receiving their fps value equal to 1, while the newer videos correctly receive the value as 30. Because the old ones are receiving the fps value as expected, the fallback of 30 is never used, resulting in 1/1 = 1 fps, which is not good.

So, going further down the rabbit hole, I discovered that all of those videos with that problem are always videos that have the WEBM codec being served with the fps value equal to 1, meaning that the problem source is in the YouTube servers themselves, which added fps of 1 to all old WEBM streams.

For example, in the first video I linked we have this stream info being served:

````txt
clen=448988290
projection_type=1
fps=30
quality_label=1080p
init=0-712
index=713-6348
bitrate=4173550
size=1920x1080
lmt=1416712423388214
itag=137
xtags=
url=<unnecessary code>
````

With the correct fps value, but the one uploaded the day before that has this stream info:

````txt
itag=248
index=235-10053
lmt=1412154160074725
xtags=
type=video%2Fwebm%3B+codecs%3D%22vp9%22
size=1920x1080
quality_label=1080p
url=<unnecessary code>
fps=1
clen=561149773
projection_type=1
init=0-234
bitrate=3232737
````

With the incorrect fps value of 1, but for the same video the MP4 stream info has the correct fps value:

````txt
itag=137
index=713-7308
lmt=1416709343818662
xtags=
type=video%2Fmp4%3B+codecs%3D%22avc1.640028%22
size=1920x1080
quality_label=1080p
url=<unnecessary code>
fps=30
clen=986654129
projection_type=1
init=0-712
bitrate=4242539
````

Confirming what I said, only the 30 fps webm streams older than October 1st 2014 had their fps info replaced with 1, resulting in the problem you described.

Seeing that I already reported this problem a few months ago to YouTube (although not in so much detail, I thought it was happening just to very few videos) and they haven't fixed it, I will be restoring the Frame by Frame feature to the extension to correct this problem permanently on our end.

**Comment by q1k** [comment]
The `shift` + `arrow` combo is still working btw.

**Comment by ParticleCore** [comment]
It has to, that removed YT+ feature was designed independent of YouTube's frame by frame workings.

**Comment by ParticleCore** [comment]
Seeing that this problem hasn't been fixed on YouTube's end, I have restored in YT+ v1.7.4  the previous feature with the same old behavior (Shift + arrows).
For now I have no plans to remove this feature again, seeing that YouTube's is not reliable and YT+ pausing automatically is quite handy, as someone mentioned before.

**Comment by mleyen** [comment]
Cyberfox 50.1.1, YT+ 1.7.6 (downloaded from dist/ in the repo), shift + arrows shortcut is not working.
As per #359, ',' to skip backwards works, but neither ';' nor '.' (i.e. shift+';') works on the AZERTY keyboard.

**Comment by ParticleCore** [comment]
@mleyen YT+ support exists only for Firefox and Chrome, not Cyberfox. Please read the readme file: https://github.com/ParticleCore/Particle/blob/master/README.md
