### ISSUE TITLE
1.7.4 stopped working in Pale Moon

### ISSUE THREAD

**Issue by sergeevabc** [ParticleCore/Particle#423]
Tested with the fresh profile of [Pale Moon 27.0.3 x64][1]: **userscript** no longer works.
Rolling back to [1.7.3](https://github.com/ParticleCore/Particle/archive/1.7.3.zip) until something good happens.
Sad beginning of a new year.

[1]: http://www.palemoon.org/palemoon-win64.shtml

**Comment by ParticleCore** [comment]
YT+ support exists only for Firefox and Chrome, which is clearly explained everywhere the userscript is officially available: https://github.com/ParticleCore/Particle/wiki

**Comment by sergeevabc** [comment]
What is Pale Moon if not a fork of Firefox, the most trending out there?
Greasemonkey and tons of scripts on Greasyfork.org work perfectly fine here.
Except for your latest inbreed experiment introduced with 1.7.4.

**Comment by ParticleCore** [comment]
Pale Moon is not Firefox, it is a fork of Firefox which makes it _not_ Firefox and I have no intentions of expanding support to all Firefox forks that exist to this date, no matter their popularity.
I would appreciate that insults would not be used, especially when the fault lies on you not reading the browser requirements and assuming that Firefox fork is the same as the Firefox browser itself, which is clearly not, also refusing to read the troubleshooting guide and problem reporting instructions, which is especially requested before any issue can be posted, which would inform you that the current support is only available for Firefox 48+ and Chrome 42+: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

> - **This extension is only being supported for Firefox 48+ and Chrome 42+**, there are no plans to support any other browser in the future. If you are using a different browser then try running the extension in one of the two supported versions.

>  - If the problem still persists move to the next step.

If you insist on using a browser that is not supported by this extension that is fine by me, but don't demand support with insults like "inbreed experiment" when I explained very clearly, in multiple locations, which browsers I  support.

For the moment I have reverted the "let" statement due to Chrome 43 incompatibility and I assume that this was also the cause of your problem, so version 1.7.5 should work again for you, but in the future it might break again because I am not supporting anything besides Firefox and Chrome, both of which can also change the minimum required version.

**Comment by sergeevabc** [comment]
You could state whatever you feel necessary like enterprise companies publish ToS which are never read. Point is average user believes fork is a slightly altered version of a known browser, therefore he feels betrayed when support is broken for no obvious reason, especially when developer is rocking the boat because he wants to play with bleeding-edge features whereas majority does not change horses (upgrade browsers) every now and then. So I am ready to accept your quirks, but raising a voice worth a try, right? But others, oh well, some of them will hate you, bear that in mind too.

**Comment by Zarggg** [comment]
Are you aware that this userscript isn't being released as a product, but as a personal project of his that he is merely making publicly available? He's under absolutely no obligation to offer support of any kind and trying to guilt or demean him into making changes for you is actually kind of rude.

**Comment by sergeevabc** [comment]
> @Zarggg 
> He's under absolutely no obligation to offer support…

Public issue tracker implies developer’s attitude to gather feedback and fulfill public expectations.
Want to share with no further responsibility? State it honestly in the first place and mute the feedback.

**Comment by ParticleCore** [comment]
If users cannot take the time to read the browser requirements when installing the userscript, or even 2 lines before opening an issue, perhaps it will be best to just make the userscript not run on any browser that is not Firefox and Chrome. This way we can prevent any further misunderstandings caused by users that prefer to not read the information that is made available and as short as possible, and if any users wish to use it on a different browsers they can fork it on their own.
