### ISSUE TITLE
My chromecast playlist skips to next item on its own

### ISSUE THREAD

**Issue by Xananax** [ParticleCore/Particle#424]
Browser/OS: Chrome 55 on windows 10
Userscript Manager: Tampermonkey 4.2.7 (included because you asked for it, but disabled in this case)

Problem Description: Youtube+ advances my chromecast playlist seemingly at random, but definitely as soon as it is paused (i.e, the "pausing" thing is reproducible with 100% chance of it happening) .

Steps to reproduce: Cast youtube to chromecast; chromecast playlist gets created. Add more than one item to playlist. Press "pause", playlist pauses for less than a second then immediately jumps to the next item. Even without pressing pause, just hanging in the tab will make the playlist advance. Switching tabs will not, so the problem only happens when the tab is in focus. It also seems as if the problem doesn't happen if the tab is *only* in focus; the mouse needs to be moving.

**Comment by ParticleCore** [comment]
I am unable to test this problem because I have no way to cast YouTube, so I would ask you to try the troubleshooting guide to see if you can either isolate the problem or fix it by yourself: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

Outside of that I cannot do anything else.
