### ISSUE TITLE
youtube Volume controlling over Mouse problem

### ISSUE THREAD

**Issue by saivamsi01** [ParticleCore/Particle#432]
Browser Name: Vivaldi

Browser Version: 1.6.689.40 (Stable channel)

Operating System: Win 10 Pro 64

Software Type: YouTube Plus

Software Version: 1.7.5

Problem Description: controlling the volume over mouse gesture enabled by me in the YT plus. Not working.

Additional details: sound just go to 10% and  stops going up  and i can't control the volume. But i can with by clicking with the mouse.

**Comment by SuitYourself** [comment]
I got the exact same issue happening.

**Comment by ParticleCore** [comment]
Please read the description, YT+ is currently only supporting Firefox and Chrome:

https://github.com/ParticleCore/Particle/blob/master/README.md

This is also explained in the troubleshooting guide which is asked to be followed before users open new issues:

>This extension is only being supported for Firefox 48+ and Chrome 42+, there are no plans to support any other browser in the future. If you are using a different browser then try running the extension in one of the two supported versions.

https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by SuitYourself** [comment]
I am using the latest chrome.

**Comment by SuitYourself** [comment]
Love how u close the thread assuming the issue is solved.

**Comment by saivamsi01** [comment]
NO it's the same issue happening with all the chrome browsers.

i'm also using the Yt Plus extenion. on chrome Version : Chromium 54.0.2840.99

Please look into the issue.

**Comment by SuitYourself** [comment]
Thank you.

**Comment by saivamsi01** [comment]
YT plus is the only youtube extension used by many of  the users. 

this is happening with lots of my friends as well. you'll lose'em. So please look into the issue. it's a great extension i recommended this to all my friends.

**Comment by ParticleCore** [comment]
I just did a hard refresh to force the download of any new YouTube files and could replicate this problem, will try to fix it as soon as I can.

In the future please indicate that this problem exists in the supported browsers, otherwise it will be dismissed since it is under an unsupported browser, such as Vivaldi or any Chrome and Firefox forks.

**Comment by SuitYourself** [comment]
Sorry mate. I did mean to add my broswer. My apologies

**Comment by ParticleCore** [comment]
Looks like the new player code YouTube is using is not reflecting the real volume the player can go, it is limiting it artificially, making it appear that full volume is 100% when it is in fact just 60% or so, depending on the situations. The solution for now appears to be to change the volume directly on the HTML5 player instead of using the YouTube api since that's what is controlling this behavior, but I am having a bit of difficulty making the volume slider adjust when the volume is changing like this. I will try to correct this behavior and push the new version today.

**Comment by SuitYourself** [comment]
No rush. Whenever you can get it working. I just wanted to make sure you knew about it.

Thanks again mate.

**Comment by saivamsi01** [comment]
Thank you Particle for looking into issue

**Comment by Aphedron** [comment]
I have the exact same problem with [Chromium](http://chromium.woolyss.com/#windows-64-bit). Thank you for looking into it.

**Comment by ParticleCore** [comment]
Version 1.7.6 contains a fix for this problem, let me know if it works for you as well. YouTube recently introduced yet another method for controlling loudness on the client side which uses relative loudness algorithm instead of linear. This problem not only caused the feature to not work properly as it also made the max volume videos play lower than what they could actually play, meaning that 100% volume on the player did not equate to 100% volume the HTML5 player could reach, but about 60% or so instead.

**Comment by Sek0n** [comment]
Seems to be working good now, for me.

Thanks for the quick patch. :)

**Comment by ParticleCore** [comment]
Marking this as duplicate of original issue posted earlier: https://github.com/ParticleCore/Particle/issues/430

**Comment by SuitYourself** [comment]
All good on this end mate. Thanks again!

**Comment by Matthewus** [comment]
Can you upload the updated version on AMO?

**Comment by ParticleCore** [comment]
@Matthewus The AMO version is updated, but because of their review process it is waiting for approval, currently sitting on position 43 in a queue of 93 add-ons. For some reason they also removed the ability to download unreviewed versions so the only two options are to wait until they approve the add-on or use the add-on version hosted in GitHub, which has no delays: https://github.com/ParticleCore/Particle/wiki/Download
