### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by XCelticX** [ParticleCore/Particle#442]
Saving settings doesn't work, when I save settings and get back again on script I see that nothing is changed like I was change, everything is on default.

**Comment by ParticleCore** [comment]
Quite a few settings do not take effect until you refresh the page, have you tried refreshing the page after saving the settings?

If you have and the problem still persists then follow the troubleshooting guide, which was asked to be followed before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by ParticleCore** [comment]
I will close this for now, if you still have any difficulty read the previous reply.

**Comment by Zettt** [comment]
@ParticleCore I'm experiencing this bug on all my machines. I had this since the beginning when I started using YT+ but somehow, the settings sometimes were saved. Today I had to reinstall Tampermonkey, and now I can't get YT+ to save its settings anymore. Is there a trick to make sure it saves its settings?

**Comment by ParticleCore** [comment]
@Zettt Please open a new issue if needed after following the instructions here: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Zettt** [comment]
Thanks for the help.
