### ISSUE TITLE
Please support Flash player.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#45]
Yeah, I know that YouTube+ works very good with HTML5 player, but some people, like me, because of hardware and/or OS, can't switch to HTML5 and watch videos, especially very smooth videos (60 FPS or less but more than 30 FPS), because that videos with this framerate aren't smooth (Chrome) or the image is re-buffering (audio is playing fine; Firefox).

Please, SUPPORT Flash player :)
I can send you some money if you will support that and/or wish this :)

**Comment by ParticleCore** [comment]
I appreciate the support offer, but this wasn't a choice, I did try to extend support for the flash player for  [162 versions during testing](https://github.com/ParticleCore/Particle/commit/7b8cc0047bbc79543441f5ce766be052458a1fe3) since I also have a lappy that struggles with HTML5, but limitations present with the Flash player were too many to be worth supporting it. The software does work with the Flash player (last time I checked), but most YT+ player features just won't work because it just isn't possible with that player type.

**Comment by Piter432** [comment]
Hmm, so maybe someone will focus on functional YouTube+ with Flash player, while you will support HTML5 player? Normally I could do it, but I don't how to "coding" in software ;P

**Comment by ParticleCore** [comment]
Anyone is free to fork one dedicated to the Flash player, as long as they respect my short license conditions, especially the first linel: https://github.com/ParticleCore/Particle/blob/master/LICENSE

But to anyone that might read this in the future: YouTube is trying to stop using the Flash player once and for all, so while support for it might be possible (however very limited due to its nature) be aware that one day there won't be any Flash player on YouTube at all.
