### ISSUE TITLE
Feature Idea: Frame-less pop-out mode

### ISSUE THREAD

**Issue by Spongar141** [ParticleCore/Particle#456]
I was wondering for the pop-out mode can there be an option to make that window frame-less something like this:
![image](https://cloud.githubusercontent.com/assets/25761898/22916929/be4618c2-f24f-11e6-8c9d-10ec97ccca54.png)
this image was from the extension floating for YouTube, 
I think this would look nice for the player.

**Comment by ParticleCore** [comment]
While this would be possible to make in an extension, it is absolutely impossible to make in the userscript version and for that reason it has never been implemented because all YT+ versions must have the same features.

**Comment by Spongar141** [comment]
Ahh I see. Thanks for the quick response.

**Comment by ParticleCore** [comment]
An additional detail, what you show in that picture isn't even possible do make in an extension because Chrome never made an api to allow such customization, in that picture you are showing a Chrome app which is completely different from an extension. So not even as a Chrome extension this would be possible to make.
