### ISSUE TITLE
fix video title width error on user owen video

### ISSUE THREAD

**Issue by bluelovers** [ParticleCore/Particle#470]
#advanced-options buttons block video title and ajax edit button too
tweak width for make it work when #advanced-options is show

## before

![20170310-060305-2](https://cloud.githubusercontent.com/assets/167966/23773052/7d3b7b8a-0558-11e7-8869-8e69626c9218.png)
![20170310-060521-3](https://cloud.githubusercontent.com/assets/167966/23773054/7d3dea32-0558-11e7-8321-3225ca14577a.png)
![20170310-060719-4](https://cloud.githubusercontent.com/assets/167966/23773053/7d3d9b5e-0558-11e7-9b88-0ebafe2fd864.png)

-----------

## after

![20170310-060913-5](https://cloud.githubusercontent.com/assets/167966/23773059/85b53026-0558-11e7-95e8-f28314b5e410.png)

```
    .player-console #watch7-headline{
        max-width: calc(100% - 270px);
    }
    #watch-headline-title-form .yt-uix-form-input-container{
        width: calc(100% - 100px);
    }
    #watch-headline-title-form .yt-uix-form-input-text{
        width: calc(100% - 20px);
    }
    .watch-title-container{
        width: auto;
    }
```

**Comment by ParticleCore** [comment]
The title is behaving correctly on my video test, please follow the guide like it was requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by bluelovers** [comment]
do u test title on video that upload by u self?

**Comment by CyberMew** [comment]
Is there a URL for the video? I can double check on my side to see if I also have the problem.

**Comment by mauriciocolli** [comment]
@CyberMew you have to own the video, but you can test it putting the title 

The culprit is this property (`white-space`):

> ![culprit](https://cloud.githubusercontent.com/assets/13389907/23823399/5459b55e-0640-11e7-900d-839ff731a93d.png)

**Disabling it:**

> ![culpritp](https://cloud.githubusercontent.com/assets/13389907/23823401/573d64dc-0640-11e7-928f-662f017d46e3.png)


I guess it's because the japanese characters are usually much bigger, and the developers didn't test it, look at the size difference in this example of 59 characters:

- 千年戦争アイギス　シャルロット交流クエスト☆3　覚醒王子＋低レベル版 sm29627586 niconicoGINZA
- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ve

But that's an error of YouTube (as you can see, the css come from YouTube), because in normal page (user not own video), it doesn't have this property, I recommend you report this to them.

And of course, you can create this stylish as a temporary fix:
```css
#watch-headline-title {
    white-space: normal !important;
}
```

**Comment by ParticleCore** [comment]
@bluelovers Yes I have tested with a video that I uploaded, the title problem you described does not occur. 

With YT+ option ["Compact title in video description"](https://github.com/ParticleCore/Particle/wiki/Features#video_title) enabled:

![ss1](https://cloud.githubusercontent.com/assets/9222661/23824329/1c0cb4d4-0664-11e7-88b9-2d0dd617487d.png)
____
![ss2](https://cloud.githubusercontent.com/assets/9222661/23824330/1e015d6c-0664-11e7-9e02-16ff5bf52d0d.png)

With that option disabled:

![ss3](https://cloud.githubusercontent.com/assets/9222661/23824333/27c21878-0664-11e7-8433-ab84377f6c2a.png)

Not once the title becomes empty.

If you are also referring to the title being cut at the end, that is a YouTube problem and should be reported to them via the "Send feedback" link available at the bottom of any YouTube page.

**Comment by bluelovers** [comment]
don't case about empty title (that is one of random error

but YouTube+ will block button when we ajax edit title ( when we click video title will open ajax edit

**Comment by ParticleCore** [comment]
There is nothing here being blocked if you close the advanced options when you want to edit the title:

![ss](https://cloud.githubusercontent.com/assets/9222661/23825561/96f60e7c-067b-11e7-94b5-b41af35ce34c.png)

I cannot replicate your problem, I cannot understand what you are actually trying to say or what you are saying is not clear.
For the last time, please follow the instructions as it was requested before opening the issue, otherwise this issue will be closed.

**Comment by bluelovers** [comment]
that is why i post this fix, let us can display button well, when  advanced options is "open"

but sure this not a important fix, just a very little fix

**Comment by ParticleCore** [comment]
Sorry, but this is not a problem at all, the advanced options provide the ability to be closed whenever the user wants, such as this case.
If you want a behavior of your choice you should implement it on your end.
