### ISSUE TITLE
[Firefox] Playlist autoplay does not work

### ISSUE THREAD

**Issue by ganego** [ParticleCore/Particle#48]
Browser Name: Firefox

Browser Version: 42 nightly

Operating System: W7x64

Software Type: userscript from greasyfork

Software Version: 0.3.9

Userscript Manager: Greasemonkey

Userscript Version: Greasemonkey 3.2

Problem Description: I load my playlist with music and at the end of one video, the next video loads but it does not start playing. "Autoplay videos" is disabled, because I normally do not want to start any newly opened videos (I open like 10 or so at the same time). But this should not affect playlist, because I want the playlist to run of course. The little play button above the playlist is enabled.
Without the script, the autoplay works as expected. It's the HTML5 player. If I enable "Autoplay videos" it works.

Steps to reproduce: ...

Additional details: -

**Comment by ParticleCore** [comment]
This is the expected behavior, playlist autoplay is related to letting the playlist go to the next video when the current one ends, not related to letting the video play. If you want the videos playing then you'll have to do it the way you already discovered, enable "Autoplay videos" while you play the playlist, but you don't have to do it via the YT+ settings all the time, you have the advanced options below every video which will allow you to enable/disable quickly certain features, including the video autoplay:

![image](https://cloud.githubusercontent.com/assets/9222661/8941312/5b209e8e-355e-11e5-846d-2a88ebce8f35.png)

This makes it easy to control wether or not you want the current playlist to play videos automatically or not play newly opened videos.

I have corrected the wiki explanation regarding this feature: https://github.com/ParticleCore/Particle/wiki/Features#playlist_autoplay

**Comment by ganego** [comment]
I see thanks for your answer.
Would you be interested in changing this behavior for playlists?
For example by adding something to the URL, that then could be detected and autoplayed?
For example all playlist entried get their link appended with *&youtubeplusautoplay=enabled* and then when the page load you check for *window.location.href* and if it has the autoplay=enabled in it it will start the video.

**Comment by ParticleCore** [comment]
The behavior would have a negative impact to the users that want the playlist autoplay on, but video autoplay off. The initial behavior I set was to have the videos playing automatically if the user enabled playlist autoplay, but quite a few users complained that they wanted to have the ability to control video autoplay independent of the playlist autoplay, which was impossible at that time. Having the condition on the link or in a setting would make no difference, but I will consider this in the future, but no promises are made.
