### ISSUE TITLE
Unknown config settings break YT+

### ISSUE THREAD

**Issue by Zoss0** [ParticleCore/Particle#480]
Browser Name: Firefox

  Browser Version: 53.0b6 - 64 Bit

  Operating System: Windows 8.1 - 64 Bit

  Software Type: Add-on

  Software Version: 1.8.3

  Userscript Manager: N/A

  Userscript Version: N/A

  Problem Description: 
Youtube Plus Button is invisible but still able to be clicked. Most things are broken.

![2017-03-31 14_44_18-youtube](https://cloud.githubusercontent.com/assets/5527179/24536265/cffdaa5e-1620-11e7-8a35-0c2ba90de2cc.png)

  Steps to reproduce: Create new profile - Download https://github.com/ghacksuserjs/ghacks-user.js - Visit Youtube. See brokenness.

  Additional details: Obviously the config template messes with YT+. However it is not known what config settings YT+ relies upon to function correctly.

**Comment by ParticleCore** [comment]
One (or more) of those settings is blocking the ability for the addon to load UI resoures, just like https://github.com/ParticleCore/Particle/issues/273. I do not know exactly which setting (or settings) is causing that problem and I will not go through all of them, but I suggest that you try in half blocks until you manage to find the one that breaks. Load just half the settings, check if the problem is still there, if it is then load half of that half of the setting, check again and repeat the progress until the problem disappears.

Whatever it might be, it is not a YT+ problem, but a browser imposed restriction.

**Comment by Zoss0** [comment]
Just thought I'd follow up with the solution. SVG disabled was causing the issue. Changing it back to the (assumed) default - false fixes the issue.

This is part of the offending user.js change:

// 2671: disable SVG (FF53+)
   // https://bugzilla.mozilla.org/show_bug.cgi?id=1216893
// user_pref("svg.disabled", true);

Hopefully anyone else bumping into this issue will stumble across this.

**Comment by ParticleCore** [comment]
Thanks for letting us know, it will certainly help anyone with the same issue in the future.
