### ISSUE TITLE
More permissive license and contributions

### ISSUE THREAD

**Issue by LennyPenny** [ParticleCore/Particle#497]
It would be awesome if the new material version would include a more permissive license. 
This would greatly improve the speed of development as people can actually contribute instead of just reporting problems.

**Comment by ParticleCore** [comment]
The decision to only ship code developed by me was made due to my limited time and extension store restrictions. Seeing that I don't have much time to inspect contributed code for possible unsafe code as well as understand what the contributor did, on top of risking getting the extension rejected from where it is hosted, I simplified the process and limited contributions only for locales / translations.

Allowing public contributions would not speed up the developing process since I would still need to inspect and study all contributed code, I prefer it this way for the lack of a better alternative.
