### ISSUE TITLE
playback options

### ISSUE THREAD

**Issue by b3n9ti** [ParticleCore/Particle#52]
hello there, really loving your script!

the last version broke the compatibility with Yet Another Youtube Script (Yays!), which I'm solely using for it's playback options. Would it be possible to get something like this for Youtube+? I'd make it perfect!

I was thinking along the lines of:

---
Playback
You can set the default playback state:

START	The video starts as soon as possible. (default)
PAUSE	The playback is paused but the player keep buffering.
STOP	The playback is stopped and the player doesn't buffer either.
AUTO PAUSE	Like PAUSE but only for videos opened in a background tab, and also the playback will automatically be started when the tab gets focus.
AUTO STOP	Like AUTO PAUSE but the playback will be stopped instead of paused.
---
Quote from https://eugenox.appspot.com/script/yays

**Comment by ParticleCore** [comment]
I do not know how it could have broken compatibility since the past few updates did not include any change related to the player or its playability, or any other aspect of YAYS that might have been affected.

It is possible that YAYS is requiring an update due to a possible YouTube change, in which case you can test this by disabling all extensions except YAYS and see if the problems still persist.

Regarding your feature request, they have been requested before and I am not interested in adding them to YT+ for now.

**Comment by b3n9ti** [comment]
"Also, did you remember to set YT+ to autoplay videos so that it lets YAYS control the videos correctly?"

That was it. Misinterpreted the "Autoplay videos" option. Thank you, it's working fine again.

**Comment by q1k** [comment]
I'd like to see "Auto-Pause" option, to pause the playing of a video until switched to that tab, similar to what Chrome does by default.

When using yays, "player shortcuts always active" of yt+ are not working, There could be other problems, but I haven't looked..

**Comment by DumbJoe** [comment]
Oh so I guess someone did beat me to it first....hahahaha.....my search skill was not high enough to pass this.... ☹

Aww, why not add it? Because it's just not your style? That was over two years ago, perhaps you would like to revisit this? Or is your answer still a no? ☹

**Comment by ParticleCore** [comment]
@DumbJoe 

>Due to time and framework limitations I am unable to accept any more feature requests.  

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by DumbJoe** [comment]
Ohh......thanks....I wasn't aware there was a readme file.......because I got your extension straight from mozilla's addon page and not from here...and I don't think this was mentioned on that page either or was it and I must have overlooked it...? mmm...

**Comment by ParticleCore** [comment]
@DumbJoe 

>Due to time and framework limitations I am unable to accept any more feature requests.

In the "About this extension" section: https://addons.mozilla.org/firefox/addon/youtube-plus/

**Comment by pep0w** [comment]
Just wanted to let everyone know that since FF 56 (the one I skipped to :D ) the videos are automatically paused until switched to the tab.
On older Firefox, for example 52 ESR, go to about:config and enable `media.block-autoplay-until-in-foreground` it will hold off on playing until switched to tab or clicked on the play icon on the tab.

**Comment by DumbJoe** [comment]
Oh well then I did overlook it.... 😅 hee hee...

@q1k I also wanted any and all videos that are opened in a new tab to passively buffer (and all the way if I happen to be afk for some while) whilst the video is autopaused on page load which is apparently not featured in this addon and will not be due time and framework limitation according to the developer.... ☹
