### ISSUE TITLE
Full browser mode switches on by itself

### ISSUE THREAD

**Issue by maxoku** [ParticleCore/Particle#522]
Firefox 52.2.1 esr. Web extension v. 1.8.7.

Full browser mode is switching on by itself after page loads in case when I close the previous video tab with full browser mode on. Or if I watched the video in full browser mode and it ended switching to normal mode (automatically) after that and then closing the tab. The option 'Memorize player mode' is turned off, but it seems to not include the full browser mode and for it it always remembers.

**Comment by ParticleCore** [comment]
The option is not linked with the "Memorize player mode", please read the feature descriptions: 

>The last player mode you used (theater or normal) will persist whenever you return to YouTube.

https://github.com/ParticleCore/Particle/wiki/Features#remember_mode


>Whenever the video starts playing the player will fill the entire space available in the browser. Once the video ends the player will return to its normal size. To return to the normal mode before the video ends simply press the Esc key or click the resize button present in the player, next to the Fullscreen button.

https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

**Comment by maxoku** [comment]
I know it's not linked to the option, I wrote that. I'm asking you to fix the problem and instead of that you focused on explaining to me something I already stated. Please include the full browser mode to the option or just disable memorizing the full browser mode at all.

**Comment by ParticleCore** [comment]
It has been stated and distinguished that the "Memorize player mode" is only and only for the player theater state, it has nothing to do with the Fullbrowser mode. It has also been stated that once activated the Fullbrowser mode will stay activated and return to normal state once playback ends, goes back to fullbrowser mode again by itself when another video or the same begins playback. To turn it off just press Esc while in fullbrowser mode, or the resize button.

There is nothing to fix because there is no problem, this is how these two features are suppose to work and they are very clearly explained in the wiki.

Again, once enabled, fullbrowser mode will stay enabled unless you specifically turn it off or press Escape or press the resize player button while in Fullbrowser mode. If you do not do any of that, once you play another video the Fullbrowser mode will fill the video to the window as it is suppose to, until you turn it off.

**Comment by maxoku** [comment]
Did you read my first post? Obviously you didn't. I wrote exactly how to reproduce it. I also wrote that the switching to full browser mode by it self for new videos, not already opened is a problem. I don't need anyone or anything to decise for me how I should watch videos and it decides for me that I should watch in full browser mode only because I watched video in that mode last time.

**Comment by ParticleCore** [comment]
And I already explained twice that the feature was exactly built to behave exactly like that. If you don't want to have the fullbrowser always on, just disable it when you don't want it. However, for the users that do want it always on after turning it on, if it were behaving the way you wanted then those users would have no way to leave it on, they would be forced to always turn it on after watching a video. Curiously enough, a user recently asked for this without knowing that it was already available: https://github.com/ParticleCore/Particle/issues/519

And another: https://github.com/ParticleCore/Particle/issues/369

Nothing about this was hidden or mislead to you in any way, all the information is available in the feature description which explains exactly how it behaves, which is exactly how you experienced and reported here.

If you don't like the way the feature currently works you can modify the source code to change it to the way you prefer, that is what userscripts are for. Not everyone has the same preferences and there are always features some users would prefer to behave differently, such as your choice to not have Fullbrowser always on and perhaps even more features you would like to work in a different way, and that can be achieved by modifying the userscript.

**Comment by maxoku** [comment]
For first I can't modify script inside the extension. For the second I don't know how. If I was good with scripting I would write script for myself and wouldn't use your extension. 

It is very annoying and I'm asking you to do something with it. I suggested that maybe it would be included in that option. Or make a new one. You are claiming that it gives more freedom, but that is taking that freedom completely from me. For me it's a bug or undesirable forced option. 

And it's obvious from that issues you linked here that users want an option to decise whichever they want it on or off at the start. Instead of being so blind and that stubborn you should just add that option.

**Comment by ParticleCore** [comment]
If what you want is to make a request instead of reporting an issue then please read the readme file:

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

I add the options that I want, the way I want, when I want, when I can and if possible. This is not a bar where you can order someone to serve you, this is a hobby of mine that I decided to share publicly after learning to program this on my own when the vastly superior and incredible YouTube Center was down for a while. I am not being paid to do this and every feature request or suggestions are welcome, but they are not by any means guaranteed to be implemented, especially not because someone keeps insisting after being told that it will not happen.

If you don't like using the extension I would suggest using other similar and better extensions, this is not worth the trouble, the goal is for you and everyone looking for this to have a better experience on YouTube, not worse, be it with the help of this extension or another.
