### ISSUE TITLE
Full page screen blocks access to the page after start playing a video

### ISSUE THREAD

**Issue by GuardianMajor** [ParticleCore/Particle#531]
**Browser Name:** Firefox
**Browser Version:** 54.0.1 (32-bit)
**Operating System:** Windows 10 Pro x64
**Software Type:** Userscript
**Software Version:** 1.8.2
**Userscript Manager:** Greasmonkey
**Userscript Version:** 3.11

I know you are in the middle of reworking everything and I understand things might break but this is something that should be relatively easy to fix, as it really only requires you to add a dismiss action to the modal screen.

**Problem Description:** 
Whenever you go to a video page and click play, the black screen fills the page and will not allow you to go back and interact with the page anymore, no matter what you do you are trapped. While the page DOES scroll and the video scrolls down with it, the black screen locks out access to the page itself, you can't do anything to get back to it once the video has started playing and no way to get back to it, including stopping the video. The only way to fix this is to go back to your last page by using the back key or simply reloading the page which is very annoying to say the least. The "screen" should be dismissable when you click on it or any place on the page that is NOT the video. The permanent modal state of it is bad UI/UX because it serves no purpose but to lock the user out.

**Steps to reproduce:** Go to any video on YouTube, click play and then you are no longer able to access the page, simple and consistently. You can scroll and do what you need, but you can't go back to the page anymore.

**Additional Details:** Not sure what else I can say that hasn't been said but here are the settings in case it matters - all I can think at this point - something in the configuration is causing this inconsistent state or there is a logic miss in the code responsible for dismissing it. Let me know if I can provide anything else my friend, I tried to be thorough.

> {
>   "GEN_BTTR_NTF": true,
>   "GEN_SUB_LIST": false,
>   "GEN_INF_SCRL": true,
>   "GEN_BLUE_GLOW": true,
>   "GEN_PPOT_ON": false,
>   "VID_END_SHRE": true,
>   "VID_DFLT_QLTY": "auto",
>   "VID_PLST_ATPL": true,
>   "VID_PLST_RVRS": true,
>   "VID_PLR_ATPL": false,
>   "VID_PLR_ALVIS": true,
>   "VID_PLR_SIZE_MEM": true,
>   "VID_PLR_VOL_LDN": true,
>   "VID_POST_TIME": true,
>   "VID_VID_CNT": true,
>   "VID_DESC_SHRT": true,
>   "VID_PPOT_SZ": false,
>   "VID_PLR_HTML5": true,
>   "BLK_ON": true,
>   "floaterX": 2000,
>   "floaterY": 2000,
>   "firstTime": false,
>   "volLev": 0,
>   "advOpts": true,
>   "blacklist": {},
>   "extLang": {},
>   "GEN_HDE_CHN_SDBR": true,
>   "GEN_HDE_SRCH_SDBR": true,
>   "GEN_HDE_RECM_SDBR": true,
>   "GEN_HIDE_FTR": true,
>   "GEN_CMPT_TTLS": false,
>   "GEN_DSB_HVRC": true,
>   "GEN_GRID_SRCH": false,
>   "GEN_GRID_SUBS": false,
>   "GEN_CHN_DFLT_PAGE": "playlists",
>   "GEN_SPF_OFF": true,
>   "GEN_REM_APUN": true,
>   "GEN_YT_LOGO_LINK": false,
>   "GEN_DSBL_ADS": true,
>   "GEN_LOCL_LANG": true,
>   "VID_LAYT_AUTO_PNL": false,
>   "VID_HIDE_DETLS": true,
>   "VID_TTL_CMPT": false,
>   "VID_HIDE_COMS": "1",
>   "VID_PLR_FIT_WDTH": false,
>   "VID_PLR_FIT": true,
>   "VID_PLR_DYN_SIZE": true,
>   "VID_PLR_INFO": true,
>   "VID_PLR_HFR": false,
>   "VID_VOL_WHEEL": true,
>   "VID_PLR_ALACT": true,
>   "VID_PLR_VOL_MEM": true,
>   "VID_PLR_ANTS": true,
>   "VID_PLR_CC": false,
>   "VID_PLR_ALVIS_WDTH": "420",
>   "VID_SUB_ADS": false,
>   "VID_PLR_ADS": true,
>   "lightsOut": true,
>   "fullBrs": false,
>   "theaterMode": true
> }

**Comment by ParticleCore** [comment]
Fullbrowser mode is built to behave exactly like that, there is nothing wrong with it. To exit during playback you can simply press Esc or click the resize player button located next to the Fullscreen button.

All of this is detailed in the feature description: https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

If you are talking about the Cinema mode then you should have been more specific. To turn it off simply click on the same button again that you used to turn it on: https://github.com/ParticleCore/Particle/wiki/Features#cinema-mode

Screenshots would have helped explain what your issue is because your description did not help much.

**Comment by GuardianMajor** [comment]
Just for the record, that may have been your intention, but it is not working that way in practice. Clearly you don't want to look into it and that's fine but what you said is not the solution nor is it accurate in practice here. What I am seeing cannot possibly be something that was done by design. I have used this long enough to know better. Thanks anyway.

**Comment by ParticleCore** [comment]
Like I said, screenshots will help explain what your issue is, because by your description it sounds exactly how the feature is suppose to behave and that is what I used to reach my conclusions. If there is more to it than that or I am misunderstanding what the problem is, then please do provide examples so that I can understand exactly what the problem is.

**Comment by ParticleCore** [comment]
By the way, did you remember to update YT+? You said that you are using version 1.8.2 but the latest version is 1.8.7: https://github.com/ParticleCore/Particle/releases/latest

This was a step in the instructions provided before reporting a problem: 

> - Make sure that you are using the most recent YouTube+ version. If you aren't then update it, restart the browser and see if the problem has already been fixed.
>
>   - Quite often problems have already been fixed in a recent version that your browser hasn't had the time to updated YouTube+ yet. To check which version is the latest visit the latest release tracker located here: https://github.com/ParticleCore/Particle/releases/latest


https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by GuardianMajor** [comment]
My friend, this is not a screenshotable issue as it will provide nothing more than I have already explained in detail. If it wasn't a real issue, I would not have wasted my time reporting it, especially that I have used this long enough to know it's quirks.

The script is supposed to update itself, so no I was not aware there is a version 1.8.7 and manually triggering update doesn't grab anything either, so you might want to look into fixing that. I will now remove it and manually install the update and let you know if it changes anything.

Plus, be it the first line of anything, if you are asking for the version, then not everyone is expected to be using the latest version, just in case you want to lower that high horse a bit.

**Comment by ParticleCore** [comment]
The version detail is exactly for cases like these when users are using an older version and didn't even bother to follow the instructions as they should before submitting an issue.

The description of your issue does not help me in any way to replicate it, if anything it describes exactly how a feature should work.

If I cannot reproduce your problem then it becomes impossible for me to solve a problem that I don't have. The screenshots could help clue in on the issue, or a short video, since I still have no idea whether you are talking about the Cinema mode or the Fullbrowser mode feature or something else completely different. I have no doubt that you do have an issue on your end, but the information you provided thus far is insufficient for me to even begin to understand what it is, let alone to help me fix it. I only asked for more because what I have is not enough for me to find out what the problem is.

**Comment by GuardianMajor** [comment]
What exactly constitutes people didn't even bother following instructions when I gave you everything you asked for and the fact that the version was not the latest is because I did exactly that and checked for update but nothing showed up, even now I had to do it manually. So you need to can the attitude, you have made yourself so self important that you are rudely attacking people who have supported you and have taken time to help you. Just forget it dude, you are not worth the trouble.

**Comment by ParticleCore** [comment]
I am sorry, I was not insinuating anything, it's just how it is, plenty of users don't even bother to follow the instructions and result in time waste, I was not trying to say that you are one of them, but I can clearly see how it might have sound like that.

The instructions also explain where to verify which version is the latest, there is a link pointing directly to the latest release just in case the automatic updates are not working for the users, some times userscript managers or even the browsers can take time or not work properly when trying to update the extension.
