### ISSUE TITLE
Youtube plus not working on startup with Firefox (55?)

### ISSUE THREAD

**Issue by EchoDev** [ParticleCore/Particle#539]
Browser Name: Firefox

  Browser Version: 55

  Operating System: Windows 7 x64

  Software Type: Addon

  Software Version: 1.8.8

  Userscript Manager:  -

  Userscript Version: -

  Problem Description: Youtube plus does not seem to load on a cold boot of Firefox and requires a refresh of the tab

  Steps to reproduce: 
1. Install Youtube Plus
2. Disable Autoplay of youtube videos with the addon
3. Go to a video e.g. https://www.youtube.com/watch?v=Kp7eSUU9oy8
4. Make Firefox restart. Do not shutdown and start Firefox again, make it actually restart. Normally you are not able to do this as far as I know but restart can happen when updating Firefox, installing addons that require a restart or by force stopping Firefox in task manager, for testing this is probably the easiest way, force stop Firefox and start it up again.
5. Firefox will automatically open the tab and Youtube video on start.
6. Result, Youtube plus does not seem to work, the video autoplays. After a refresh of the tab Youtube plus start working.

  Additional details: 

I don't know if this is intended or just not possible to fix but thought I should report it.

**Comment by ParticleCore** [comment]
I cannot replicate this using the same setup as yours. The add-on is always able to prevent autoplay when opening Firefox after force stopping it in task manager. I also restarted using the disable/enable add-ons that require restart, the add-on still did not fail to prevent autoplay after restarts.

Please follow all the troubleshooting steps exactly as detailed to make sure that this is a problem caused by the add-on and not by something else outside the add-on, such as a browser setting that you might have changed, which can cause add-ons to take some time to start after cold shutdowns.

**Comment by EchoDev** [comment]
Hmm I can't seem to reproduce the issue with my original and the new profile. When I opened this bug I was able to reproduce the issue with both my original profile and a profile on a VM (Not fully clean, had uBlock origin installed). 

This ticket can prolly be closed untill I can reproduce it again. Is there anything I need to pay attention to when/if this happens again?

**Comment by ParticleCore** [comment]
Nothing in particular, just remember to follow the troubleshooting instructions as requested the next time you open a new issue.
