### ISSUE TITLE
player size wrong when scroll down for comments

### ISSUE THREAD

**Issue by DJYeh** [ParticleCore/Particle#54]
Browser Name: firefox

Browser Version: 39.0.3

Operating System: Ubuntu 14.04

Software Type: Userscript

Software Version: 0.4.6

Userscript Manager: Greasemonkey

Userscript Version: 3.3

Problem Description: When I scroll down to comments, the player becomes the size of the entire screen and there's no way to disable it or move it. After resetting the script to default settings, the size is still that big, but it's now at the lower right side of the screen, with much of it off the screen. 

Steps to reproduce: Go to any youtube video and scroll down.

Additional details: It was working fine yesterday, but not anymore. I don't recall doing anything.

**Comment by ParticleCore** [comment]
This sounds very similar to https://github.com/ParticleCore/Particle/issues/37 and https://github.com/ParticleCore/Particle/issues/28 especially since this one was also with Ubuntu.

Right click on the player and see if it is the flash player or the HTML5 player. If you are being served the flash player then go here to activate the HTML5 player: https://www.youtube.com/html5

**Comment by DJYeh** [comment]
Ah, apparently something happened to my Youtube cookie and the player reverted back to Flash. Problem solved after reactivating HTML5 player. Thanks!
