### ISSUE TITLE
onYouTubePlayerReady issue

### ISSUE THREAD

**Issue by anonym24** [ParticleCore/Particle#540]
Youtube + extension doesn't work if some other extensions uses next function in their scripts:

`function onYouTubePlayerReady(player) { ... }`

**Comment by ParticleCore** [comment]
This is not something I can magically do on my end. The extension already shares that function to prevent other scripts from working, but it cannot make other scripts share it as well. Those scripts are the ones that need to share that function back and not override it.

This is something that I literally cannot fix because the problem lies on any other script that hijacks the function after mine uses it, you will have to ask the other script developers to not hijack that function and instead share it. Until then this extension is not compatible with any script that hijacks that function.
