### ISSUE TITLE
The old instructions on how to get back to old youtube no longer work and need updating.

### ISSUE THREAD

**Issue by BobbyMcBobMcBobby** [ParticleCore/Particle#551]
Title says it all. The instructions say to contact you here if they need updating.

**Comment by Corruptinglyneedful** [comment]
They only slightly need updated.  Instead of clicking the three dots, you have to click your profile picture, then choose, restore old youtube, and then say submit; filling out the feedback as you wish.

**Comment by dacohe** [comment]
I have the same issue.  However, I do not see "restore old youtube" as an option (hidden by the blue box), but I have clicked on the line and exited.  However, the blue box is still there.  How do I delete it?

**Comment by Corruptinglyneedful** [comment]
What blue box?  What are you talking about?  This is what current Youtube looks like outside of the material layout. http://i.imgur.com/PN9pFIZ.jpg

**Comment by ParticleCore** [comment]
It is possible the new layout has become permanent for a few users, in which case there is no way to go back, but I will gladly update the instructions with more recent examples.

**Comment by Corruptinglyneedful** [comment]
Couldn't they delete Youtube cookies in that case?

**Comment by ParticleCore** [comment]
They can, it's just not guaranteed to revert the layout anymore.

**Comment by Corruptinglyneedful** [comment]
Well without images, we can't tell what their layout is and if they are
forced into material or not.

Even if they are, now we have Iridium.

**Comment by dacohe** [comment]
The blue box shown in the attached picture

**Comment by DarionGey** [comment]
I already told you to move the blue box as it was covering up the option to revert in a thread you closed as solved when it wasn't. This is what happens when you cut corners. Just move the box from the right to the left - it's literally one word of code!! - so people can see how to revert without having to come here. I have no idea how to code anything and I managed it just by searching the code and replacing 'right', with 'left'. This is what happens when you ignore issues!

![ty - copy](https://user-images.githubusercontent.com/31485812/29930954-c9c807be-8e67-11e7-9eee-76b77665efe9.png)

**Comment by ParticleCore** [comment]
@DarionGey Do not insist on this anymore, I will not push an update just for that. The exit options have already moved places at least 5 times since the layout was first released, I will not change anything just for that again. Also do not cross post issues, this is not the place for this discussion.

**Comment by DarionGey** [comment]
dacohe is having the same issue in this thread, they say the blue box covers the option to revert. At least you've given an explanation this time instead of ignoring the issue. You don't want to update? Fine, I've done it myself anyway. I'm just warning you that if you ignore these issues you will make more work for yourself in the long term. My final message, I will say no more. Good luck and thanks for the script.

**Comment by dacohe** [comment]
First, you did not "already tell me".

Second, I was not trying to "cut corners", I was just trying to follow the
instructions in the box.

Three, I do not and have not used "code", or even where to find it.  I
downloaded the add-on from Mozilla Firefox.  You are probably asking, why
the hell did I go to github.  Answer:  From Mozilla Firefox to ask about an
issue, I had to log into that site.

Four, all I wish to do now is get rid of YT+ and any of its remnants.  Is
was good while it lasted but is now a PITA.  But being as ignorant as I am,
I do not know how to go about that.

I apologize for cross posting issues.

**Comment by ParticleCore** [comment]
@dacohe I was not talking about you. Notice the username I mentioned in my previous reply.

**Comment by dacohe** [comment]
Sorry about that.  I will try to post a separate issue thread.

**Comment by JF0603** [comment]
**Give them some time**. The update of the UI is `fairly recent`, you can't possibly expect an update if there if permanent material design change was in fact made, to be suddenly written and committed in mere hours. Rome took more than a day to code [or applicable cliche]... They are aware of the issue clearly and trust me when I say I am suffering from the lack of that crucial darkening feature as much as anyone with the migraines I get thus rendering anything but full-screen video unusable at the moment :weary:. I do however think that the team who gave us YT+ is not cutting corners and that we should give them a fair chance to see if there is or is not a solution to the problem at hand before going mad. Just give them some time to assess and make a statement regarding the state of the new site update and whether or not what has changed is still "fixable." or whether it is not. I for one hope for the continued use of the plugin but will be forced to slowly analyze the situation on my own if there is not on the off instances in which free time avails itself...

**Comment by ParticleCore** [comment]
A fix has already been found, but it is hacky and not the best option. I am still trying to find a good fix that won't compromise most of the player's functionalities.

**Comment by Artain** [comment]
You can check out my script maybe you can implement a option so the new youtube layout will no longer be loaded. https://greasyfork.org/en/scripts/32906-get-me-old-youtube

**Comment by ParticleCore** [comment]
Re-opening, closed incorrectly.

**Comment by ParticleCore** [comment]
@aberingi No one can do that except you. Go to the right section of this issue and click on the UNSUBSCRIBE button under the NOTIFICATIONS label to stop receiving emails from this issue.
