### ISSUE TITLE
Feature Request: Pause the playing video using spacebar

### ISSUE THREAD

**Issue by hamkah2c** [ParticleCore/Particle#56]
Cause I think its very easy than click the video

**Comment by ParticleCore** [comment]
YouTube already has a global shortcut key to pause/play the video without having to click the player, press the `K` key. As you might understand it would be pointless to add a feature that duplicates what YouTube already offers.

Here you have a table of all the global shortcuts and their functions currently native in YouTube:

|Key|Function|
|:--|:--|
|p | Haven't found yet what it does
|n | Haven't found yet what it does
|j | Skip forward 10 seconds
|l | Skip backwards 10 seconds
|m | Mute/unmute audio
|k | Pause/play video
|Shift + , | Reduce playing speed
|Shift + . | Increase playing speed
|f | Enter/exit fullscreen

--

For any developers interested in this, the most up to date shortcuts can be found in the HTML5 player source code file, with the current file having the keys listed in the following function:

````javascript
function AI(a, b, c) {
    var d = !1,
        e = a.j.X();
    if (!e.Ra) {
        switch (b) {
            case 80: // p key
                c && (a.j.jj(), d = !0);
                break;
            case 78: // n key
                c && (a.j.ij(), d = !0);
                break;
            case 74: // j key
                a.j.Lc(-10);
                d = !0;
                break;
            case 76: // l key
                a.j.Lc(10);
                d = !0;
                break;
            case 77: // m key
                a.j.Ac() ? a.j.unMute() : a.j.mute();
                d = !0;
                break;
            case 75: // k key
                yr(sA(a.j)) ? a.j.pauseVideo() : a.j.Kc();
                d = !0;
                break;
            case 190: // . key
                if (c && e.V) // checks if Shift is pressed
                    for (b = a.j.fj(), c = a.j.app.T, e = 0; e < b.length - 1; e++)
                        b[e] == c && (a.j.lj(b[e + 1]), d = !0);
                break;
            case 188: // , key
                if (c && e.V) // checks if Shift is pressed
                    for (b = a.j.fj(), c = a.j.app.T, e = b.length - 1; 1 <= e; e--)
                        b[e] == c && (a.j.lj(b[e - 1]),d = !0);
                break;
            case 70: // k key
                Fz(a.j) && (Iz(a.j), d = !0)
        }
        d && a.F.gb(2, !0)
    }
    return d
}
````

**Comment by Eisys** [comment]
Sorry to comment on a closed issue. I just found this addon and I love it. Does pretty much everything that I wanted from YTC(except this). But I also would like to pause the video with spacebar. To me, adding this as a feature is the complete opposite of pointless. Pressing spacebar to is about 1.874 billion times easier then looking for the K key since it's alot bigger and easier to access. If I want to quickly pause a video, I'd much rather just smash on a big spacebar than find that small K somewhere.

Perhaps you could allow us to re-bind the default Youtube keys? This would be a really nice addition.

**Comment by ParticleCore** [comment]
@Eisys I am sorry, but I don't intend to add that feature for now. It might be useful for you, but I can't add features based on that criteria or I'd have to add any feature that anyone finds to be useful, so instead I consider them for myself and decide wether or not I find worth adding.

Another problem with adding this feature is that it would start with just the spacebar (just like hamkah2c requested) and now there's another request from you for the arrows to be included as well, other users will ask for more global shortcuts and the software begins to become cumbersome.

What I might consider doing is a different approach, make the player always active so that all player shortcuts can run without having to click the player, unless the user is trying to type text. Would this be sufficient?

**Comment by Eisys** [comment]
@ParticleCore Ok, I totally understand.

And yes, that would be absolutely perfect.

**Comment by ParticleCore** [comment]
I have added the new option [Player shortcuts always active](https://github.com/ParticleCore/Particle/wiki/Features#shortcuts_on) in YT+ 0.5.0

Let me know if it works correctly.

**Comment by Eisys** [comment]
Oh thank you thank you thank you. Works like an aboslute charm. Going to say byebye to YTC now.

**Comment by q1k** [comment]
Any chance making this work on flash, I mean Youtube Center works on flash too.

**Comment by ParticleCore** [comment]
@q1k See https://github.com/ParticleCore/Particle/issues/45

**Comment by Eisys** [comment]
Hey. Sorry to bother you again.

I found a bit of a bug with this update after using it for a while.

On a video, if I click anywhere else on the page, it jumps up to the video. If I scroll down and the small video comes up, I can click things again.
If I disable the 'Player always visible when reading comments' then I can't click anything on the video page, it just jumps up to the video.
It seems like it thinks I'm clicking on the video.
It's not that big of a deal to me, specially when using the small player cause everything clickable can be clicked if I scroll down enough. Just letting you know.

Using the userscript version with Tampermonkey, Chrome 44.0.2403.155 m (64-bit)

**Comment by ParticleCore** [comment]
@Eisys It seems that the method I am using brings the player into focus as a consequence of making that element active, I don't know if I will be able to correct this with a different method. If it proves to be too complicated to solve I might remove the feature.

**Comment by ParticleCore** [comment]
@Eisys Could you open a new thread for the issue you reported? This one is already getting filled with cross-talk. Also I believe the issue is restricted to Chrome and might be easily fixed.

**Comment by Eisys** [comment]
Oh.
Well now I wish I never said anything.

It really isn't that big of deal and I rarely notice it.
Please just leave it in and maybe add a small note/warning next to it that it doesn't work quite 100%

**Comment by ParticleCore** [comment]
@Eisys Please read my previous reply, I am able to replicate the issue with certain settings, but not with others. This might be easier to fix than I thought.
