### ISSUE TITLE
Build a Pop - out Queue

### ISSUE THREAD

**Issue by plummt** [ParticleCore/Particle#618]
Is there a way to build something like the google chromecast queue, but with the popped out video. I want to be able to make a playlist on the fly that when I click a video, it will add it to the playlist, and the current window/tab that is playing videos will add it to the queue. 

I don't code in javascript more than a few times a year, but I'm pretty good with CSS and HTML manipulation, but not with anything like this. I have no clue about how difficult it would be to add this in. If there is something I can do to help with this let me know, I've been looking to learn how to build extensions, but never knew where to start, or how to get into it. If you have any suggestions on how to add this, I would be more than willing to help in some of my free time.

**Comment by ParticleCore** [comment]
This is not a place to request custom scripts, you would be better off asking it on dedicate forums such as greasyfork.

**Comment by bvjazz** [comment]
Hi AllStarted asking for help due to the Failure of Firefox getting its act together as the Competition! YouTube works in every other Browser except the most recent FF update. They have no way to co-communicate except on the net.I am believing no one else is kind-hearted enough to remind them that they got a problem and they Link me to Particle?? I am a user, not a programmer. So thanks for the help lots of your group has tried to helpbut no sooner than a new re-install of Firefox and within 5 minutes the same problem repeats. Today Apple put out links for Win 7 user so there updates function ..FF nope??? makes no sense to meThanksBob V
