### ISSUE TITLE
Youtube Plus doesn't view youtube thumbnail preview

### ISSUE THREAD

**Issue by ryuumajin** [ParticleCore/Particle#622]
It just happened recently.
Basically, youtube preview/thumbnail is all blank white.

When I disable YT+ add-ons , the preview comes back.
When I enable YT+ again, the preview's gone.

**Comment by ParticleCore** [comment]
Everything is working correctly here

![ss](https://user-images.githubusercontent.com/9222661/33302080-367f7eac-d3e9-11e7-80f0-4597e236cf04.gif)


Follow the troubleshooting guide as requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by Corruptinglyneedful** [comment]
I just had this happen to me twice as well.  When I disabled it all came back, enabling it made them go poof again.  A browser restart seems to have sorted it out for now and I have the script enabled but I suspect that Youtube is breaking things again x.x

On a side note, how do you get your thumbnails to animate like that?  Mine never do that.  Is it a setting somewhere?

**Comment by ParticleCore** [comment]
@Corruptinglyneedful I don't understand what you are talking about. Those are the video thumbnail previews YouTube is rolling out, users either have them or don't, but I don't understand how you are saying that it has happened to you twice when you don't even have this YouTube feature.

Please be clear exactly what issue is happening, examples are very important, otherwise I can never understand what the issue is. Follow the instructions for reporting a problem as it is requested before opening any issue.

**Comment by Corruptinglyneedful** [comment]
Perhaps I am misunderstanding the issue.  My static thumbnails disappeared.  I was under the impression that this also happened to OP.

I do not yet have the animated thumbnails, as you do @ParticleCore 

I hope that clears the confusion.

**Comment by ParticleCore** [comment]
Please follow the instructions for opening an issue, especially the troubleshooting guide and providing examples that show what the problem is.

**Comment by ParticleCore** [comment]
Looks like this is a YouTube bug, not caused by this extension: https://www.reddit.com/r/firefox/comments/7g0xor/firefox_has_stopped_showing_youtube_thumbnails/
