### ISSUE TITLE
Particle WebExtension - Can't Access Settings

### ISSUE THREAD

**Issue by dufferzafar** [ParticleCore/Particle#627]
```
  Browser Name: Firefox

  Browser Version: 57.0.1

  Operating System: KDE Neon

  Software Type: Extension

  Software Version: 1.9.5

  Problem Description: Can't access Particle's settings. There should be a preferences button, right?

  Steps to reproduce: Open FF's list of addons. No Prefs button.

  Additional details: I've been using Particle for about 2-3 months, and on FF 56 I was able to access the settings.
```

![image](https://user-images.githubusercontent.com/1449512/33552045-72bb09ba-d919-11e7-9c44-65d32d3c09a1.png)

**Comment by dufferzafar** [comment]
Ugh. Sorry for being a stupid ass. I knew I was doing something wrong. Found that YT+ Settings button. It was right in-front of my eye, maybe that's why I didn't see it.

To be honest, would it hurt to just add the preferences button in the FF Addon list? That's how I access settings for all other addons. Why should YT+ be any different?

**Comment by ParticleCore** [comment]
The settings are not built in an independent page, they are embedded in every YouTube page making it a nightmare to handle from that point of view, so yes, it would hurt to "just add" the preferences button in the list, especially when taking into account that it had serious problems in the past from Firefox side, rendering that button completely useless.

YT+ is different because it was not well thought of from my part in that aspect.
