### ISSUE TITLE
Add feature to load local resorces in youtube+ addon

### ISSUE THREAD

**Issue by lychichem** [ParticleCore/Particle#64]
Now the extension only support English, right? I wish you could add the feature of loading locale resources in your extension and drag out the strings to translate and then I can start my work of translating this extension. You know, some users have translated your script version of this extension. I bet they will be happy to see this extension be localized.

**Comment by ParticleCore** [comment]
As I have said in the greasyfork thread, I am looking for a way to allow custom language loading which will allow the user to insert any translation he wishes, either a custom translation (made by the user or someone else) or an already approved translation which I will probably store in this GitHub repo.

However, this will only let the user use one custom language besides the default one (english), which I hope will be enough.

Also if the translations are not actively updated there will be non-translated labels whenever new features are added, another similar problem will arise when an already translated label is modified which will cause all translations to not be correct until they are updated.

This isn't something easy to do and if I find the task too big and cumbersome I will choose to not  implement it.

**Comment by lychichem** [comment]
Don't worry. I translates firefox nightly language pack at the same time. I have some time to translate this addon. You will not add strings more than mozilla to this addon at one time, right?
And as for addon localization, it reads pref general.useragent.locale, which will only be a specified value for firefox. So users can only use one locale.

**Comment by ParticleCore** [comment]
That is great to know, the help will be greatly welcomed, but until and if I manage to create a functional system I won't start a language package in the repo, so any translations being made will have to be hosted by whoever translated it in a place of his/her choice.

No, I don't intend to add large amounts of new text, it's always the new labels for new features, nothing that can be considered extensive.
And I don't intend to use a browser specific method for the language detection, it currently detects YouTube's language, if YouTube is in english then YT+ shows english, if it is in Portuguese then it shows in Portuguese, etc.

**Comment by SW1FT** [comment]
I support this and can help, I currently translate projects such as uBlock Origin and Firefox to Portuguese. Also, I recommend using Crowdin as it's easier to work with.

**Comment by ParticleCore** [comment]
For a free plan, Crowdin (and similar services) requires an approved open source license. Unless I can find an open source license that is the equivalent to my custom license, I will be unable to make use of the translation platforms without paying. I also do not know yet wether it will be worth using it over directly converting in GitHub, especially since forcing GitHub contributors to create an account on Crowdin to participate might discourage them.

I can handle the portuguese (pt-PT) and english translations, but that's about it.

**Comment by ParticleCore** [comment]
@lychichem Is shevchenko's translation `zh-CN` or is it a different dialect (Taiwan, Hong Kong)? Are [laincat's modifications](https://greasyfork.org/en/forum/discussion/5890) correct or does the file contain incorrectly translated labels as well? I do not wish to make use of translations that were made using web translators, I'd appreciate if you could verify it and if you find any incorrect/erratic translations please correct them.

When you are done please post here between these tags:

<pre>````json
{
    translations go here
}
````</pre>

So that it displays like this:

````json
{
    "label1": "translation1",
    "label2": "translation2"
}
````

if you find it more practical you can use the already available translation examples: https://github.com/ParticleCore/Particle/tree/master/Locale

**Comment by lychichem** [comment]
Okay , I've checked the translation, it has good quality, I only need to modify a few strings. But please wait for me to publish the patch to forum and let users to check,after a week I'll make a pull request.

**Comment by ParticleCore** [comment]
There is no worry, I am still testing the feature and it doesn't depend on this translation, take the time you need.

**Comment by ParticleCore** [comment]
I've added this [feature](https://github.com/ParticleCore/Particle/wiki/Features#custom_lang) in version 0.5.9, let me know if it works correctly.

**Comment by ParticleCore** [comment]
@lychichem I don't know if you read [my comment in your pull request](https://github.com/ParticleCore/Particle/pull/66#issuecomment-137743784), but there are some labels missing so I haven't yet added the `zh-CN` locale to the list yet.
