### ISSUE TITLE
Youtube material design

### ISSUE THREAD

**Issue by Zetat** [ParticleCore/Particle#655]
Add: if new youtube material design = true { SCRIPT STOP};

There are some bugs on the player, so I have to disable the script.

Thanks bro.

**Comment by Zarggg** [comment]
This script it not intended for the Material layout. If YouTube has switched to Material for you, then you should be using [ParticleCore/Iridium](https://github.com/ParticleCore/Iridium)

**Comment by ParticleCore** [comment]
The extension already does a check for material, but it cannot do so as fast as before since the changes they made, which causes some things to be changed before it can detect the new layout. This is why the blue message information asking to disable either the extension or the new layout is persistent since leaving it always on with Material layout is not a good option.
