### ISSUE TITLE
Feature Request: Lowest/highest quality preference

### ISSUE THREAD

**Issue by zaniar** [ParticleCore/Particle#72]
Browser Name: Opera

Browser Version: 31.0.1889.174

Operating System: Windows 7 64-bit

Software Type: Userscript

Software Version: 0.6.0

Userscript Manager: Violentmonkey

Userscript Version: 2.1.10.4

Problem Description: 
Why lowest quality?
* You have slow internet connection
* You have limited internet data plan (and limited budget)
There are no need to explain why highest quality, I think.  

For the highest quality preference, I think there is no problem as it seems the intended behavior of youtube and YT+. Just select the highest quality as the default quality and it will play next highest quality if the first one not available. There is problem with lowest quality preference. I select 144 as the default video quality. Then I play a video that does not have 144 quality. The video played at highest quality (there is red HD icon on gear icon, no check mark on quality list. Also happen on when the default quality is the highest). 

Steps to reproduce:
1. Set default video quality to 144.
2. play [this video](https://www.youtube.com/watch?v=nGPIOz1QMEo) (or other video that does not have 144p quality)
3. take a look at player setting button (the one with the gear icon), there is a red circle with HD text indicating it plays in HD.

Additional details:
Is it possible to load available qualities of a video without playing it? If possible, it can the method to avoid playing unavailable quality.
It  nice to have an option to prioritize highest or lowest quality. If the highest one selected, it will try the next highest quality (which is lower than the default) when the default quality not available. If the lowest one selected, it will try the next lowest quality (which is higher than the default) when the default quality not available.

**Comment by ParticleCore** [comment]
This is a YouTube player bug, if the pre-defined quality does not exist the YouTube player itself should select the closest one automatically like it used to in the previous player, but is failing in the new one.

This can be confirmed by testing this behavior with YT+ disabled, follow these steps:

Open a video that has the 144p option, for example: https://www.youtube.com/watch?v=6XTed0NyCDM

Select the 144p quality. If you have cookies enabled it should memorize it automatically, so if you refresh this video it will start at 144p by itself.

Now open the video you linked: https://www.youtube.com/watch?v=nGPIOz1QMEo

Notice how it selects HD instead of 240p, just like you described despite the fact that YT+ is disabled.

Since this is a YouTube bug it should be reported to them, so I ask you that you send them your feedback so that they can correct this issue. You can do so by going to the bottom of any YouTube page and click on "Send feedback", describe the problem and hopefully they will fix it soon.

This wasn't a problem with the previous player, however it isn't working correctly with the new one.

Also be advised that I only support the following platforms: https://github.com/ParticleCore/Particle/blob/master/README.md

So in the future if any issue occurs that is specific to either Opera or Violentmonkey I will not fix it.
