### ISSUE TITLE
Doesn't auto fit height in threater mode

### ISSUE THREAD

**Issue by quyleanh** [ParticleCore/Particle#77]
In default, the max width of theater mode is 1280px, but my screen resolution is 1366*768 so when I turn on "Fit to page in theater mode" the video will be cut. I need to modify 1280 to 1066px to fit with height.
Please fix or add auto fit height function.
Thank you.

**Comment by ParticleCore** [comment]
This is not something that can be fixed, the feature takes into account the width of the page and is aimed at screens that have bigger resolutions than 1366x768 to provide a more full view experience. With that said, any page with a resolution smaller than 16:9 will cut the player height when the player is set to fill the page width, there is no way around that.

If the screen resolution is too small for this to be useful then the feature shouldn't be used, instead the default YouTube behavior should be used since it already accounts for the height and adjusts the player to fit to the respective size natively.

The other alternative is to set a custom width to your own preference, just as you did, if you dislike the native YouTube player sizes.
