### ISSUE TITLE
Hidden comments section shouldn't be loaded.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#79]
Currently, no matter is comments section show or hidden (except removed them from code in YouTube's video page), they're always loaded. I think they shouldn't be loaded when they're hidden, if user set them to hide them by default in settings or they're set up by the user in settings to show them, but later user clicked "hide comments" button to hide them (in short: they should be "unloaded" [not sure about proper action name :P] if showed comments are hidden again by the user; I'm thinking of unloaded tabs effect in Firefox by "UnloadTab" extension).

**Comment by ParticleCore** [comment]
Before YouTube migrated the comments section from iframes to editable divs they would not load if they were shrunk into a tiny size, however as you could see for yourself this is no longer the case.

I will try to work on a new way of restoring this functionality, however I don't intend on making the discussions to "unload" everytime the user hides the comments, this would cause a significant increase in bandwidth usage since it would load the comments again every time the user toggled the comments.

**Comment by ParticleCore** [comment]
I have uploaded a new version containing a fix for this issue, let me know if it works correctly.

**Comment by Piter432** [comment]
Works correctly for me :) Thank you :+1:
