### ISSUE TITLE
Player does not appear for 30 seconds on page load

### ISSUE THREAD

**Issue by OdinGitDat** [ParticleCore/Particle#94]
Browser Name: Firefox

Browser Version: 42.0b2

Operating System: Windows 7 x64

Software Type: any (tried all types)

Software Version: 0.7.0

Userscript Manager: Greasemonkey

Userscript Version: 3.4.1

Problem Description: Player takes 30~60 seconds to load, not just the video, the entire movie_player div does not appear in the page source before this time has passed. During this time the tab indicates it is loading and the status bar says that it is "Waiting for xxxxxxxxxxxxxx.googlevideo.com...". After the player is loaded the video plays fine. I have followed the entire troubleshooting procedure, the problem only occurs when youtube+ is enabled.

Steps to reproduce: Open any youtube video page and the problem occurs. Problem can be bypassed by refreshing the page while the delay occurs. After the refresh there is no delay and the player works as normal. Problem does *not* occur on embedded players on other domains. Problem stops occuring once the youtube player has been loaded within current session. So the only steps to reproduce are to open any video page via link or address bar that has *not* been visited before within the current session.

Additional details: Most notable is that any refresh method works in bypassing the problem, even ctrl+f5. And every video that is in the history of the current session works fine as well.

Upon closer inspection of the firefox network monitor it seems to be a GET request of the html type to this link: 
https://r12---sn-25ge7n7z.googlevideo.com/generate_204
("r12---sn-25ge7n7z" is variable)
Image below shows the request in question that is causing the delay
![](https://dl.dropboxusercontent.com/u/13296383/ShareX/2015-10-01_03-41-42.png)
When the response headers for that request are recieved the player appears and starts playing.

**Comment by ParticleCore** [comment]
I have tested the add-on and userscript in both FF 41.0.1 and FF nightly, the player did not suffer the reported delay.

I have to ask this because users in the past were sure they followed this step but actually didn't do it correctly; did you try disabling all add-ons and userscripts except YT+ to see if this is not a conflict being caused by some other software?

Share your settings so that I can test again using your exact settings (you don't need to share the blacklist).

Make sure YouTube is not trying to use the Flash player, open `about:config` and change the value of `plugin.scan.plid.all` to `false`, restart the browser and see if the problem still persists.

**Comment by ParticleCore** [comment]
According to the request headers in your console screenshot you are using Linux and Firefox 38, do you have some sort of user agent modifier installed or are you running the browser in a virtual machine? Because if it was using the correct UA string (according to the information you listed about your OS and browser) it should show something similar to this `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0b2) Gecko/20100101 Firefox/42.0b2`.

**Comment by Piter432** [comment]
Confirmed on Windows XP SP3 in Firefox. I thought this is because I'm using
Flash player type instead of HTML5 player type (videos doesn't play in my
Firefox on XP with HTML5 player type).

**Comment by ParticleCore** [comment]
@Piter432 Then this is most likely a problem with the Flash player. Could you post your YT+ settings so that I can try to replicate the issue with the HTMl5 player and confirm this to be restricted to the Flash player?

**Comment by ParticleCore** [comment]
@Piter432 Does the problem still exists if you use YT+ 0.6.8?

**Comment by OdinGitDat** [comment]
@ParticleCore Yes I have disabled every addon and only ran youtube+ and the problem still persists. I can send you my settings but they do not make any difference, I have tried a lot of combinations of settings and the problem still persists. It should be replicatable with the default settings.

I changed the plugin.scan.plid.all to false and restarted my browser and the problem still persists. 

Yes I am using a ua-spoofer, at the time of that screenshot I enabled my add-ons again so that's why it is showing the wrong ua string. As I said I have tested it with all my addons disabled (and thus also the correct ua string). My system is exactly as I stated it in my OP, no VM in use.

**Comment by ParticleCore** [comment]
@OdinGitDat This issue you described has been reported plenty of times in the past, but the causes have been plenty and most were related to the YouTube player trying to fallback to the Flash Player. However since you checked with plugin set to false (which supposedly disables the flash plugin) then I think we can rule this one out.

Install YT+ version 0.6.8 and see if the problem also exists with that version, if it does then try the next step.

Try using Firefox with a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager) and install just YT+, nothing else.

**Comment by ParticleCore** [comment]
I just noticed in your console log that your browser is loading the webm streams, Firefox is still not fully compatible with webm/MSE streams, it still has problems playing that type of codec which is very likely what is happening to you.

Did you change the `media.mediasource.webm.enabled` or `media.webm.intel_decoder.enabled` setting to `true` in `about:config`?

**Comment by OdinGitDat** [comment]
Ok, so I have been trying different things for an hour now. Going back to 0.6.8 does not fix the problem. I had media.mediasource.webm.enabled set to true, setting this to false and restarting the browser also does not fix the problem.

If it is an ipv6 problem than it should not apply to me, I have disabled any form of ipv6 in my network settings. Also if it was a problem with ipv6 then the problem should also occur when I'm not using youtube+ right?

So at about this time I get a message that my vpn subscription has been expired. I disable the vpn client for a moment and continue trying to replicate the problem. And whaddaya know, it stops occuring. So the updated replication atm is: being connected with my cryptostorm vpn client AND using youtube+ with ANY settings.

I swear this is getting stranger the more things I try.

**Comment by ParticleCore** [comment]
Some of the YouTube streams are probably being served through ipv6, which fails since you have disabled it in your network, or some other conflict related to your local net <> vpn <> YouTube.

They are usually the streams with higher quality and I assume that you had a video quality set in YT+ which was causing the player to try and load the non-standard quality and when YT+ was disabled the player would load the normal quality, which was not having network issues.

At this point it is clear to me that this is not something being caused by YT+, it is a network issue on your end which you will have to identify and solve. My suggestion is to try to enable IPV6, otherwise try my last suggestion which was to test Firefox with a new profile and only YT+ installed.

**Comment by OdinGitDat** [comment]
Enabling ipv6 does not make a difference. A new firefox profile works though. 

So I have tested it with my current profile and all the addons disabled which did not work. If an entirely new profile works, can I conclude that is has to do with my profile preferences? Do you know of any preferences other than the ones you mentioned before that could fix this problem for me?

**Comment by ParticleCore** [comment]
It is very likely that you had a preference(s) causing this problem, to find out which might be hard.

On your previous profile (the one which was having the problem) open `about:support` and scroll to the table named `Important Modified Preferences`, it shows all the settings which you (or a software) have changed.

Now to find out which one(s) exactly is the culprit I am afraid that you will have to try them out one by one in the new Firefox profile (or resetting in the current profile) until the problem appears again, start with the ones that sound like they might be related to the problem, anything related to media playback or network communications.

**Comment by ParticleCore** [comment]
On another note, there is also the possibility that this issue is related to your cache or temporary files, so clear them first in your current profile and see if the issue goes away.

**Comment by OdinGitDat** [comment]
Alright, I imported all my preferences into a clean firefox profile and the problem occured again. So I did what you said and started removing user-set preferences. Good news, I found the culprit. These are the settings that caused the problem
`user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.ssl", true);`
Settings these to the default value fixed it. (I dont even remember why I changed them)

**Comment by ParticleCore** [comment]
Thank you for letting me know, this will be of great help for anyone else that might face the same problem!

**Comment by walls50** [comment]
big up to OdinGitDat. setting "network.http.pipelining" and "network.http.pipelining.ssl" to default fixed my issues. i did change this values after a watched a youtube video made by a kid that had a super duper solution to accelerate youtube. this was back when i was raised by wolfs in the forest and had 5mb/sec internet.... since then i grew up and my 90mb/sec connexion does not need this "tour de magie" ( magic trick ). so, ParticuleCore, thanks for the awesome YouTube plus.. it's perfect.

**Comment by ParticleCore** [comment]
@walls50 I am glad to hear it worked out for you as well. I will mark yours as a duplicate of this to make it easier for other users to find this solution in the future.
