### ISSUE TITLE
trying to move from YTC, some things i miss + some stuff

### ISSUE THREAD

**Issue by MammothJerk** [ParticleCore/Particle#95]
* Auto-buffer videos
* Hide header when video is playing
* Default player size to Fill (like the Fullbrowser mode but you can still scroll down to the description & comments)
* Hide watched videos in the subscription box
* Downloading video

In Fullbrowser mode the header doesnt hide when i run this [Stylish theme](https://userstyles.org/styles/105165/youtube-dark-2015), not sure what the cause is.

auto resolution to "Original Definition", the 8k options looks a bit silly but it serves the same purpose.

the "advanced options" buttons below the player are hard to see with a dark theme, could change their colour in the options perhaps.

Fill the page with the subscriptions grid layout so there is not so much negative space
![](http://puu.sh/kvdLH/b9ffbc89af.jpg)

Can you possibly add a button to the video frame which from you can quickly turn annotations on/off?

----

These were some things I could think of within about 20 minutes, maybe i'll think of some more but hopefully Particle will stay around for long enough and won't become abandoned like YTC =)

**Comment by ParticleCore** [comment]
Some of these features have already been requested:

 - Auto-buffer https://github.com/ParticleCore/Particle/issues/52

 - Download videos https://github.com/ParticleCore/Particle/issues/32

Regarding the other features I don't intend to add them for now, YT+ already feels like it has too many features for my liking and I don't want to risk reaching a point where maintenance is a nightmare (especially with YouTube changing so frequently) and having memory leaks hard to track.

If a userstyle is having some issues with YT+ and they are not related to unique YT+ elements (such as YT+ images) then these problems must be solved on the userstyle, otherwise I would have to account for all the different themes that exist which would be impossible since fixing things for some themes would also ruin it for other themes.

YouTube no longer uses "Original Definition", so to avoid confusion YT+ also uses the same label as YouTube's - 4320p (8k).

The advanced options section has been made in such a way so that users can invert the button colors for dark themes, this has been explained here: https://github.com/ParticleCore/Particle/issues/31#issuecomment-115045913

Fill the subscription page is something that can be done via Stylish, I don't find it to be a useful feature.

Another annotation button on the player would be redundant, there already exists one for this purpose in the player options.

Understand that YT+ is not meant to be a replacement for any software, it is simply another option which aims on being light and packs only the features that I find to be useful.
