### ISSUE TITLE
Option to have non-transparent player.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#97]
I was thinking about something like [this] (https://greasyfork.org/en/scripts/11485-youtube-new-ui-fix). Hovewer, when using this script with YouTube+, the video is slightly covered by non-transparent player, which I don't like :/

**Comment by ParticleCore** [comment]
Hello Piter432, I am sorry but I am not interested in adding this feature, it is not so simple as to modify the player, it also requires lots of other page elements to be modified so that the new player height works correctly with them and this requires a certain degree of maintenance on top of the already existing code, which I am not willing to take.

**Comment by q1k** [comment]
[Youtube New UI fix](https://greasyfork.org/en/scripts/11485-)
